### ISSUE TITLE
rollupTypes leaves empty directories in project root

### ISSUE THREAD

**Issue by hnrq** [qmhc/vite-plugin-dts#100]
Hi, y'all! I'm using `vite-plugin-dts` in [the dev branch of this project](https://github.com/hnrq/draggable/tree/dev). The rolled up `.d.ts` file is succesfully generated, but the plugin leaves a tree of folders in the project root directory. Any ways to get around that?

**Comment by qmhc** [comment]
Are you using a mac or linux system?

**Comment by hnrq** [comment]
> Are you using a mac or linux system?

I'm using Linux

**Comment by qmhc** [comment]
`entryRoot` should be a dir path:

```ts
dts({
  rollupTypes: true,
  outputDir: 'dist',
  entryRoot: 'src'
})
```
