### ISSUE TITLE
Typed defineEmits argument turns into any

### ISSUE THREAD

**Issue by MellKam** [qmhc/vite-plugin-dts#101]
I defined a simple mouse click event with the typed argument e: MouseEvent.

```
const emit =
  defineEmits<{
    (event: 'clickEvent', e: MouseEvent): void;
  }>();
```

But when I built my component and started using it (i build my components library), the handler function had arguments of type any.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/51422045/184498382-7bd9c7d7-57bc-4117-b8ab-dfcbc7673f76.png">

I found these types in the d.ts file of this component. 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/51422045/184498466-9f4cdd36-927c-40c2-9fd0-1040e753421a.png">

I tried using vue-tsc and it works fine. 

<img width="540" alt="image" src="https://user-images.githubusercontent.com/51422045/184498756-8fb88cc8-4215-4a2a-a785-cf330f1b556b.png">

If this is my mistake, please describe to me how to fix it.

**Comment by qmhc** [comment]
It need to use `js` defined method:

```ts
const emit = defineEmits({
  click: (event: MouseEvent) => true
})
```

It's a limitation of vue compiler.

**Comment by MellKam** [comment]
> 

Thank you, now it works ♡

**Comment by emosheeep** [comment]
Can this function be supported in the future? For now, using vue-tsc directly to compile can generate exact .d.ts files. I guess maybe it would be convenient to implement it if we borrow the native capabilities of vue-tsc.
