### ISSUE TITLE
@types/react引起的定义冲突

### ISSUE THREAD

**Issue by wxhccc** [qmhc/vite-plugin-dts#102]
安装vite-plugin-dts的时候会附带安装@types/react，在vue项目里，会导致template模版里出现报错。

**Comment by qmhc** [comment]
项目中没有 `@types/react` 的依赖，你需要提供有详细步骤的最小复现。

**Comment by wxhccc** [comment]
用pnpm安装vite-plugin-dts，安装完后已安装有两项，第二项就是@types/react，然后vue文件的模版里eslint就有红色下波浪线了。我只好手动删掉@types/react了。

**Comment by qmhc** [comment]
这需要你提供一个能稳定复现的仓库，因为当前的依赖，以及我在空白模版的测试都不会出现这个问题，你自己在空白目录下也未能复现。

我先暂时关闭这个 issue，如果有稳定的复现仓库我们可以重新打开。
