### ISSUE TITLE
default entryRoot is inappropriate. 默认的 entryRoot 不合适

### ISSUE THREAD

**Issue by Thy3634** [qmhc/vite-plugin-dts#106]
我的工程结构以及构建成果物如图
dts 生成的路径包含多余的 ‘packages/core’

![image](https://user-images.githubusercontent.com/44743274/188052572-460965c7-ff85-4f7e-940d-5152c8d2cdd7.png)

dts config:
```js
{
    // entryRoot: __dirname, // 加上这句就 ok 了
    outputDir: ['dist'],
    insertTypesEntry: true
}
```
也就是说，根目录字段的默认值不合适
我看了默认值是 “”，不知能否使用 vite.config.js 所在的路径

**Comment by qmhc** [comment]
`entryRoot` 默认值是用 vite 运行时的 `config.root`，经过考虑，还是尽量让插件的默认行为更贴合 vite，而且通过配置可以实现需求，因此暂时不改。
