### ISSUE TITLE
不能生成

### ISSUE THREAD

**Issue by miaozikeji** [qmhc/vite-plugin-dts#109]
![image](https://user-images.githubusercontent.com/61998207/189019596-5e229137-410d-49a6-bc0b-61b36b10debf.png)
![image](https://user-images.githubusercontent.com/61998207/189019635-88493b6e-f44c-4dc5-b135-fe06dd25e723.png)

**Comment by qmhc** [comment]
你应该更具体地描述你的问题是通过什么样的操作后发生的，有哪些具体的异常表现，最好能提供一个复现的仓库。
