### ISSUE TITLE
在类型生成的时候，有些情况没有生成 index.vue.d.ts

### ISSUE THREAD

**Issue by roy-kang** [qmhc/vite-plugin-dts#113]
这个地方有点奇怪，有些组件有 index.vue.d.ts，有些又没有，找了一圈没有找到原因

这种就有
![image](https://user-images.githubusercontent.com/112255758/190621854-c4d5ac6c-0e32-42fb-bacb-da78929284e9.png)

这种没有
![image](https://user-images.githubusercontent.com/112255758/190621915-63453600-3d9e-4819-b1f6-dda19f6441b4.png)

index.d.ts，都是下面的这种格式
```ts
import type { App } from 'vue';
import EpSuspensionFrame from './src/index.vue';
export { EpSuspensionFrame };
declare const _default: {
    install(app: App): void;
};
export default _default;
```

而组件内部的写法就是正常的写法

**Comment by qmhc** [comment]
是否有试过这个 [FAQ](https://github.com/qmhc/vite-plugin-dts/blob/main/README.zh-CN.md#%E6%89%93%E5%8C%85%E5%90%8E%E5%87%BA%E7%8E%B0%E7%B1%BB%E5%9E%8B%E6%96%87%E4%BB%B6%E7%BC%BA%E5%A4%B1)？

**Comment by roy-kang** [comment]
OK，明白了

**Comment by roy-kang** [comment]
还想请问下，下图这种错误怎么解决，有没有好的办法
![image](https://user-images.githubusercontent.com/112255758/190840932-401a6b89-120b-4ef9-9a8e-c313d99fc610.png)

**Comment by qmhc** [comment]
你使用的 vue 版本是多少？

同时你可以看看 #63

**Comment by roy-kang** [comment]
我用的3.2.39的最新版，换回 3.2.26 确实可以了，现在还没法解决么？
