### ISSUE TITLE
error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

### ISSUE THREAD

**Issue by chenyo2691** [qmhc/vite-plugin-dts#116]
程序在打包时报错：
`error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.`
dts并没有使用特殊的配置：
    dts({
      skipDiagnostics: false,
      logDiagnostics: true
    })

从输出的d.ts部分结果看来，发现有两个迹象：
1. 库引入了`import { ElPagination } from "element-plus";`，在结果看来许多地方都引入了ElPagination这个声明类型的源码，导致声明文件非常大，如下图所示。这不应该是我预想的，预想应该是类似是这样引入其他来源的声明文件`type: import("vue").PropType<import("../../queryTable").TableColumnProps[]>;`
![图片](https://user-images.githubusercontent.com/8911831/192496556-01edf4e8-d917-4fd0-9861-33bfe2b308ff.png)
2. 除了第三方库是这样，本地库的引入也会有类似的问题，例如我有两个组件A和B，A引用了B，那么A的声明文件会包含B的声明文件源码。这也不是我的预想，我的预想是B已经构建了声明文件，那么A不应该重新构建，而是引入即可。

请支持

**Comment by diegoazh** [comment]
any update?
