### ISSUE TITLE
[BUG] Changing of exported types will not trigger regenerating

### ISSUE THREAD

**Issue by Fuchsoria** [qmhc/vite-plugin-dts#117]
The problem is that changing of exported types will not trigger regenerating of declaration files.
What I'm using: 

    vite build --config vite.config.dev.ts --mode development --watch

Vite plugins config:
   

    build: {
        chunkSizeWarningLimit: 99999,
        minify: false,
        sourcemap: true,
        lib: {
          entry: resolve(__dirname, 'src/index.ts'),
          name: '@blabla',
          fileName: 'bla',
          formats: ['es'],
        },
      },
    plugins: [
        dts({
          staticImport: true,
          copyDtsFiles: false,
        })
    ],

This change will trigger types regenerate:

    export const requests = {
      getSomething: () => blablabla,
      getSomethingNew: () => blablabla2,
    };

This change will **not** trigger types regenerate:

    export type CustomType = {
      custom_field: string;
      new_custom_field: string;
    };

Versions:

    "typescript": "4.8.3",
    "vite": "3.0.9",
    "vite-plugin-dts": "^1.5.0"

What I found when researched a bit about this situation:

> The way TypeScript handles type-only imports and ambient types
> effectively hides them from Rollup's watch mode, because import
> statements are not generated and changing them doesn't trigger a
> rebuild.Otherwise the plugin should work in watch mode.

**Comment by Fuchsoria** [comment]
How I understood the problem is mostly in .ts files where you just have exported types, and you try to export this types from main index.ts file via `export type { CustomType };`

**Comment by qmhc** [comment]
Will the second change trigger `vite` rebuild?

**Comment by Fuchsoria** [comment]
> 

No, temporary solution is to add another plugin at start of build, but I'm loosing 5x build performance right now.

Import another plugin to Vite config:

    import  typescript2  from  'rollup-plugin-typescript2';


And add to plugins config there:

      plugins: [
        {
          ...typescript2(),
          apply: 'build',
          enforce: 'pre',
        },
      ]

How I understood the issue is somewhere in Vite itself

**Comment by Fuchsoria** [comment]
After upgrade vite-plugin-dts from v1.5.0 to v1.6.1 whole folder with files where I have only exported types is ignored by vite-plugin-dts and dts file missing imports 
![image](https://user-images.githubusercontent.com/43413472/193051538-e1c3a0cd-b1c8-4f04-b06c-c36f6acfd4b8.png)

From:
![image](https://user-images.githubusercontent.com/43413472/193051161-479b02e2-b2dd-48bf-a4af-80fb96160546.png)
To:
![image](https://user-images.githubusercontent.com/43413472/193051195-d07bba54-6029-4d9d-878f-37a6c5665396.png)
