### ISSUE TITLE
Error in systems other than Windows

### ISSUE THREAD

**Issue by ckvv** [qmhc/vite-plugin-dts#119]
错误信息

```
failed to load config from /Users/chenkai/github/ckpack/v-ui/scripts/vite.es.ts
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/chenkai/github/ckpack/v-ui/node_modules/@microsoft/api-extractor/lib/collector/Collector' imported from /Users/chenkai/github/ckpack/v-ui/node_modules/vite-plugin-dts/dist/index.js
Did you mean to import @microsoft/api-extractor/lib/collector/Collector.js?
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:323:11)
    at moduleResolve (node:internal/modules/esm/resolve:916:10)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
 ELIFECYCLE  Command failed with exit code 1.
```
复现地址<https://github.com/ckpack/v-ui>

**Comment by qmhc** [comment]
你可以尝试一下最新的 `1.6.3` 版本是否还存在这个问题。

**Comment by qmhc** [comment]
麻烦你发一下你的 `vite` 配置和 `package.json`

**Comment by qmhc** [comment]
我克隆下来能够正常的打包，或许可能有一些缓存，你尝试重新初始化项目看看。

![image](https://user-images.githubusercontent.com/40221744/193225983-2797a415-a5ee-4caf-9dec-251d7786181a.png)

**Comment by qmhc** [comment]
是在 `1.6.3` 版本下运行的，因为是 `^` 没有锁版本，会安装最新版，已经确认过了。

![image](https://user-images.githubusercontent.com/40221744/193227163-09556f25-d9a4-4de4-99ce-cd179d4a60d6.png)

**Comment by qmhc** [comment]
我已经确定了在我本地的环境下你的这个项目在 1.6.3 版本不会报错，请你按重新初始化项目尝试后再反馈，我们再进一步讨论可能是一些系统环境、node 版本之类导致的问题。

> lock 锁的是内部依赖，这个插件是你的直接依赖，会根据你的版本号规则更新 lock 文件。

**Comment by qmhc** [comment]
![image](https://user-images.githubusercontent.com/40221744/193236653-cefb0227-d29b-4a87-b437-a469414fa1da.png)

依然无法复现。

**Comment by hrachhovsepyanqless** [comment]
> 又有其他问题了
> 
> ```js
> failed to load config from /Users/chenkai/github/ckpack/v-ui/scripts/vite.es.ts
> error during build:
> ReferenceError: __filename is not defined in ES module scope
>     at isFileSystemCaseSensitive (file:///Users/chenkai/github/ckpack/v-ui/node_modules/vite-plugin-dts/dist/index.mjs:11047:46)
>     at getNodeSystem (file:///Users/chenkai/github/ckpack/v-ui/node_modules/vite-plugin-dts/dist/index.mjs:10812:46)
>     at file:///Users/chenkai/github/ckpack/v-ui/node_modules/vite-plugin-dts/dist/index.mjs:11367:20
>     at file:///Users/chenkai/github/ckpack/v-ui/node_modules/vite-plugin-dts/dist/index.mjs:11374:8
>     at file:///Users/chenkai/github/ckpack/v-ui/node_modules/vite-plugin-dts/dist/index.mjs:11389:4
>     at file:///Users/chenkai/github/ckpack/v-ui/node_modules/vite-plugin-dts/dist/index.mjs:172321:3
>     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
>     at async loadConfigFromBundledFile (file:///Users/chenkai/github/ckpack/v-ui/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63495:21)
>  ELIFECYCLE  Command failed with exit code 1
> ```

I have the same issue, FYI. I've tried updating vite to the latest version, but it didn't help. I'm using yarn 1.22.19 and node 16.15.
