### ISSUE TITLE
"@microsoft/api-extractor": "^7.32.0" 7.32.0版本不存在

### ISSUE THREAD

**Issue by SPxiaomin** [qmhc/vite-plugin-dts#121]
7.31+，直接到8了，warning提示说这个v8的版本是错误发布，不要使用

**Comment by qmhc** [comment]
目前在 npm 上看到的最新版为 `7.32.0`，并没有看到你说的 `8.0`，而且你说的这个错误我在多个系统测试中也没有出现，所以请提供一个最小复现。

**Comment by biancangming** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @microsoft/api-extractor@^7.32.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

刚刚卸载旧版本，再次安装的时候出现了这个，不明所以

**Comment by qmhc** [comment]
@biancangming 删除 node_modules 和 lock 文件之后重新安装还会这样吗？

**Comment by biancangming** [comment]
> @biancangming 删除 node_modules 和 lock 文件之后重新安装还会这样吗？

是的，我删除了这两个文件，单独安装，还是出现了这个问题。

https://www.npmjs.com/package/@microsoft/api-extractor/v/7.32.0。
![image](https://user-images.githubusercontent.com/42108047/193284488-96d47d52-5b67-4362-ad3f-84969c386418.png)

我在npm上查看这个包版本是存在的  https://www.npmjs.com/package/@microsoft/api-extractor/v/7.32.0，但是单独安装这个依赖版本竟然提示版本不存在，不知道是不是这个依赖包发布的有些问题。

![image](https://user-images.githubusercontent.com/42108047/193285745-a5ac1d93-392a-4e08-8a83-32c72aed55be.png)

我之前在npm上发版时也遇到过这个奇怪的问题，然后重新发包，之前的版本居然复活了，不清楚是不是npm的bug。
