### ISSUE TITLE
.vue.d.ts 生成失败在包含 as const的时候

### ISSUE THREAD

**Issue by hxdyj** [qmhc/vite-plugin-dts#125]
![image](https://user-images.githubusercontent.com/14368755/194996208-8d08299e-c38a-469f-9747-cf5c09728fed.png)
左侧是包含 常量 as const ，  右侧改成非常量以后就可以生成.vue.d.ts了

**Comment by qmhc** [comment]
是否能提供一个最小复现？我无法复现这个错误。

**Comment by hxdyj** [comment]
> 是否能提供一个最小复现？我无法复现这个错误。
我自己写了个最小的demo，发现可以正常生成。但是在我那个大项目，去掉这个就正常了。

有问题的项目：
https://github.com/hxdyj/img-mark
commitId: v0.0.53
装完依赖后，删除根目录types文件夹，`yarn build` 生成的types文件夹.d.vue就没有

切换到master分支重新打包就能生成了
