### ISSUE TITLE
The component props changed to any after build

### ISSUE THREAD

**Issue by yzh990918** [qmhc/vite-plugin-dts#129]
dev:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/46418596/195775142-22f93fff-a6b7-46fa-84b5-2aad0fb41776.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/46418596/195775175-ea4d4360-fdb3-4218-b3e2-e75b22e590b3.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/46418596/195775202-fbced515-b00f-40b7-ac7c-fddf3d1189a7.png">

production:
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/46418596/195775312-90b2b95d-eccc-4a32-8b8b-6bf546f8def0.png">

**Comment by qmhc** [comment]
Do you try to turn on `skipDiagnostics: true` and `logDiagnostics: false` to see if there are any type errors?

The type of props is defined in the first generic of DefineComponent. The second generic in your screenshot is the type of variables in setup scope. The props here is set to `any` for supporting compatibility with ts + pnpm.

**Comment by said-ahemt** [comment]
Hi ! I'm having the same issue with the latest version of vite-plugin-dts. Adding the `generic="T"` prop solves the issue.

Any idea on why ?
