### ISSUE TITLE
读取tsconfig.json出错了

### ISSUE THREAD

**Issue by jiabinbin** [qmhc/vite-plugin-dts#13]
![image](https://user-images.githubusercontent.com/9244703/122695732-ddd92680-d273-11eb-8488-df217d8d023d.png)
![image](https://user-images.githubusercontent.com/9244703/122695772-fc3f2200-d273-11eb-90e5-222fb60decc9.png)
对应的tsconfig.json配置为
![image](https://user-images.githubusercontent.com/9244703/122695813-1973f080-d274-11eb-98db-381dadbb9e32.png)

**Comment by qmhc** [comment]
`JSON.parse` 解析标准格式 json，标准的 json 格式是不能包含注释的，将 paths 下方的注释去掉即可。

**Comment by jiabinbin** [comment]
非常感谢！
