### ISSUE TITLE
仅有部分文件生成了.d.ts

### ISSUE THREAD

**Issue by Ytiona** [qmhc/vite-plugin-dts#130]
### 问题截图：
![QQ截图20221016003247](https://user-images.githubusercontent.com/43615920/195997687-b67dccc0-8405-471e-9717-f2c13aa4bf9a.png)

### 仓库地址：
https://github.com/Ytiona/jlc-public-backstage-vue3

### vite配置：
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { configAutoImportPlugin } from "./config/plugins/unplugin";
import path from "path";
import dts from "vite-plugin-dts"

export default defineConfig({
  plugins: [
    configAutoImportPlugin(),
    vue(),
    dts(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    outDir: "lib",
    cssCodeSplit: true,
    lib: {
      entry: path.resolve(__dirname, "./src/index.ts"),
      formats: ["es"],
      name: 'jlc-public-backstage-vue3',
    },
    rollupOptions: {
      external: [
        "lodash/merge",
        "lodash/cloneDeep",
        "vue",
        "element-plus",
      ],
      output: {
        entryFileNames: '[name].js',
        preserveModules: true,
        preserveModulesRoot: "src",
        globals: {
          vue: 'Vue'
        },
      },
    },
  },
});

### ts配置：
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "lib": [
      "ESNext", 
      "DOM"
    ],
    "skipLibCheck": true,
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    },
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
  ],
}

### 另外入口文件里面似乎包含了太多ts声明: 
![QQ截图20221016003514](https://user-images.githubusercontent.com/43615920/195997835-2ae1bcd7-ac77-45c1-b75b-635576960391.png)
![QQ截图20221016003540](https://user-images.githubusercontent.com/43615920/195997841-afcad0df-3b6b-4275-91d8-7b1fc4bbfb9f.png)

**Comment by luo-geng** [comment]
应该是第三方外部的lib导致的

**Comment by qmhc** [comment]
你可以添加 `skipDiagnostics: false` 和 `logDiagnostics: true` 的插件选项，进行类型错误的检查。
