### ISSUE TITLE
No JSDoc

### ISSUE THREAD

**Issue by leo91000** [qmhc/vite-plugin-dts#132]
When adding jsdoc comment to setup component, props comments are lost.

```vue
<script setup lang="ts">
const props = defineProps<{ 
    /**
      * JSDoc for my prop
     */
    myProp?: string
}>
</script>
```

--> Component props are typed, however comments disapears

**Comment by hasan-almujtaba** [comment]
You can use this syntax instead

```js

const props = defineProps({
  /**
   * Button Variant
   * @default filled
   */
  variant: { type: String as PropType<Variant> },
  colorScheme: { type: String as PropType<ColorScheme> },
});
```

Comments in compiled build
![image](https://user-images.githubusercontent.com/52339597/198246707-d05a3aac-00e5-4be2-be19-83bb09d373f1.png)
