### ISSUE TITLE
vite配置build.lib.plugins中引入dts插件，始终无法生成声明文件

### ISSUE THREAD

**Issue by yx-plus** [qmhc/vite-plugin-dts#135]
`vite v3.2.0 building for production...
✓ 4 modules transformed.
dist/index.js   0.20 KiB / gzip: 0.15 KiB
dist/index.cjs   0.27 KiB / gzip: 0.20 KiB

[vite:dts] Start generate declaration files...                                                                           
error during build:
TypeError: Cannot read properties of undefined (reading 'length')                                                        
    at transformAliasImport (file:///data/home/Jser/code/clone/vue3-rich-admin/node_modules/.pnpm/vite-plugin-dts@1.6.6_vite@3.2.0/node_modules/vite-plugin-dts/dist/index.mjs:176634:16)                                                         
    at file:///data/home/Jser/code/clone/vue3-rich-admin/node_modules/.pnpm/vite-plugin-dts@1.6.6_vite@3.2.0/node_modules/vite-plugin-dts/dist/index.mjs:177109:21                                                                                
    at file:///data/home/Jser/code/clone/vue3-rich-admin/node_modules/.pnpm/vite-plugin-dts@1.6.6_vite@3.2.0/node_modules/vite-plugin-dts/dist/index.mjs:176507:44                                                                                
    at async Promise.all (index 0)                                                                                       
 ELIFECYCLE  Command failed with exit code 1.
`

**Comment by qmhc** [comment]
请提供一下 `vite.config.ts` 和 `tsconfig.json` 配置。

同时请检查一下是否使用了最新的 lib 模式多入口功能？目前还未支持，请等待升级。

**Comment by yx-plus** [comment]
> 请提供一下 `vite.config.ts` 和 `tsconfig.json` 配置。
> 
> 同时请检查一下是否使用了最新的 lib 模式多入口功能？目前还未支持，请等待升级。

对，多个文件入口，我没看清lib不是一个数组；
lib: LibraryOptions | false

**Comment by jhonjtoloza** [comment]
I'm getting this error as well, I used create-vue to generate my project

**Comment by surister** [comment]
@yx-plus What was the solution?
