### ISSUE TITLE
Support multiple entries for lib mode

### ISSUE THREAD

**Issue by qmhc** [qmhc/vite-plugin-dts#136]

**Comment by polRk** [comment]
Any updates?

**Comment by thednp** [comment]
Also interested.

**Comment by kawazoe** [comment]
@polRk @thednp This feature is available in v1.7. I'm giving it a try *right now* in one of my projects.

@qmhc I'm seeing some weird generation in some edge cases though, If `insertTypesEntry` is enabled, and the entry name doesn't end in `index`, it generates a file for that entry, matching the entry name, but without any file extension. Besides that, it works as expected and generates the correct types.
