### ISSUE TITLE
Ts decorators doesn't work since 1.7.1

### ISSUE THREAD

**Issue by Herethic** [qmhc/vite-plugin-dts#145]
### Describe the bug

Hey!

I see such errors in the console 
```bash
[vite:dts] Start generate declaration files...
src/components/Test.tsx:2:191 - error TS2339: Property 'enumerable' does not exist on type '{}'.

2 function _applyDecoratedDescriptor(target, property, decorators, descriptor, context) { var desc = {}; Object.keys(descriptor).forEach(function (key) { desc[key] = descriptor[key]; }); desc.enumerable = !!desc.enumerable; desc.configurable = !!desc.configurable; if ('value' in desc || desc.initializer) { desc.writable = true; } desc = decorators.slice().reverse().reduce(function (desc, decorator) { return decorator(target, property, desc) || desc; }, desc); if (context && desc.initializer !== void 0) { desc.value = desc.initializer ? desc.initializer.call(context) : void 0; desc.initializer = undefined; } if (desc.initializer === void 0) { Object.defineProperty(target, property, desc); desc = null; } return desc; }
```

I assume the problem is somehow related to property descriptor

Code example

```ts
function first() {
    console.log("first(): factory evaluated");
    return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {
        console.log("first(): called");
    };
}

function second() {
    console.log("second(): factory evaluated");
    return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {
        console.log("second(): called");
    };
}

class ExampleClass {
    @first()
    @second()
    method() {}
}
``` 

I checked different versions and found out that it stopped working from version **1.7.1**. Checked with Nodejs 14 and 16

### Reproduction

-

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.1
    Safari: 16.1
  npmPackages:
    vite-plugin-dts: 1.7.1 => 1.7.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Please ensure include those files that you used in `tsconfig.json` and no type error occurred.

**Comment by Herethic** [comment]
> Please ensure include those files that you used in `tsconfig.json` and no type error occurred.

As I sad, only declaration fails and only with version `1.7.1`. `1.7.0` and below works fine.

**Comment by qmhc** [comment]
`1.7.1` fixed to have correct include/exclude, and [this example](https://github.com/qmhc/vite-plugin-dts/blob/main/example/src/decorator.ts) works well.

**Comment by rafinskipg** [comment]
> `1.7.1` fixed to have correct include/exclude, and [this example](https://github.com/qmhc/vite-plugin-dts/blob/main/example/src/decorator.ts) works well.

the link does not wokr

**Comment by qmhc** [comment]
> > `1.7.1` fixed to have correct include/exclude, and [this example](https://github.com/qmhc/vite-plugin-dts/blob/main/example/src/decorator.ts) works well.
> 
> the link does not wokr

Updated.

**Comment by qmhc** [comment]
This issue seems to have been fixed in past updates, so close it now.

Might reopen if any update.
