### ISSUE TITLE
一个组件在嵌套自己组件的时候在生成 d.ts会报错

### ISSUE THREAD

**Issue by cykcykcykcyk** [qmhc/vite-plugin-dts#146]
### Describe the bug

最近在写一个树状组件，循环中需要嵌套自己。在生成d.ts的时候会提示

> '_sfc_main' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

使用的是script-setup的写法
进嵌套自己的那个组件会报错

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tzvbq2?file=src/App.vue

### System Info

```shell
"vue": "^3.2.41"
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
你需要使用 js 的方式来定义 props，参照: https://stackblitz.com/edit/vitejs-vite-kq2brw?file=src/components/HelloWorld.vue
