### ISSUE TITLE
index.d.ts生成结构动态变化

### ISSUE THREAD

**Issue by micro-bean** [qmhc/vite-plugin-dts#147]
### Describe the bug

打包项目后的index.d.ts生成后的结构随机不一样

第一种结构情况：
declare const _default: {
    new (...args: any[]): {
    ...

第二种结构情况：
const _sfc_main = _defineComponent({
...

第三种结构情况：
生成两个“_sfc_main”，两个“export default”

### Reproduction

#

### System Info

```shell
window10 + vite^3.1.0 + vue^3.2.36
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
你好，能够提供一个最小复现呢？
