### ISSUE TITLE
Module '"react/jsx-runtime"' has no exported member 'jsx'

### ISSUE THREAD

**Issue by intellidev1991** [qmhc/vite-plugin-dts#148]
### Describe the bug

It generate TS2305: Module '"react/jsx-runtime"' has no exported member 'jsx' error. its not true and i cant fix it.
![image](https://user-images.githubusercontent.com/53402331/202412155-c5f284d6-99af-4a6f-9b1b-c416e55b2cd4.png)

 "@types/node": "^17.0.42",
 "@types/react": "^18.0.25",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  
  
 tsconfig.json
```json
  {
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "declaration": true,
    "declarationMap": true,
    "baseUrl": ".",
    "paths": {
      "my-lib": ["./src"]
    }
  },
  "include": ["src"]
}
```

vite.config.ts
```js
import { UserConfig, defineConfig } from 'vite'
import { resolve } from 'path'
import react from '@vitejs/plugin-react'
import dts from 'vite-plugin-dts'
import tsConfigPaths from 'vite-tsconfig-paths'
// @ts-ignore
import { peerDependencies, dependencies } from './package.json'

// https://vitejs.dev/config/
export default defineConfig((configEnv) => ({
  plugins: [
    react(),
    tsConfigPaths(),
    dts({
      include: ['src/'],
      insertTypesEntry: true,
    }),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, './src', 'index.ts'),
      name: 'my-lib',
      formats: ['es', 'umd'],
      fileName: (format) => `index.${format}.js`, // Change this to your library name
    },
    rollupOptions: {
      external: [...Object.keys(peerDependencies), ...Object.keys(dependencies)],
    },
    target: 'esnext',
    sourcemap: true,
  },
})) as UserConfig

```

### Reproduction

,,,

### Steps to reproduce

yarn build

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.34 GB / 15.79 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (100.0.1185.36)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carlosrziegler** [comment]
Same error here :(

**Comment by jky0ung** [comment]
same..

**Comment by victorcalvo12** [comment]
This might be anecdotal, but I think the order of the plugins in `vite.config.ts` matters here. I fixed this by putting dts() before react()

**Comment by wangpin34** [comment]
@victorcalvo12 Save my day. Thanks, dude.

> This might be anecdotal, but I think the order of the plugins in `vite.config.ts` matters here. I fixed this by putting dts() before react()

**Comment by favna** [comment]
I'm not really familiar with the code of this repo, but from a quick scan I can see that the https://github.com/dsherret/ts-morph package is used for the TypeScript compilation instead of just the regular `typescript` package (as described on https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API) and there is an issue on ts-morph that specifically mentions the lack of JSX support: https://github.com/dsherret/ts-morph/issues/240#issuecomment-363217425

My 2 cents to @qmhc would be to ditch ts-morph and just use the TypeScript compiler API directly.
