### ISSUE TITLE
Error: @vue/compiler-sfc is not present in the dependency tree

### ISSUE THREAD

**Issue by Hisioni** [qmhc/vite-plugin-dts#152]
### Description

use vue 2.6.x

`package.json`
```json
"dependencies": {
    "vue-demi": "latest"
  },
  "devDependencies": {
    "@types/node": "^18.11.9",
    "@vue/compiler-dom": "^3.2.45",
    "@vue/composition-api": "^1.7.1",
    "typescript": "^4.9.3",
    "vite-plugin-dts": "^1.7.1",
    "vite-plugin-vue2": "^2.0.2",
    "vue": "~2.6.14",
    "vue-template-compiler": "~2.6.14"
  }
}
```

when build it's report issue as title

### Suggested solution

* use vue-template-compiler instead of @vue/compiler-sfc under vue2.7

* make template-compiler able custom

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Tanimodori** [comment]
It is hard to use TypeScript in `vue<2.7`. Many changes have made it compatible with TypeScript in 2.7. I'll recommend upgrade to 2.7.

**Comment by xbzhang2020** [comment]
I encountered  the same error.  My project uses vue@2.6.x, but "@vue/compiler-sfc" can only be used in vue@3.x. Have you solved the problem? How?

**Comment by Hisioni** [comment]
> I encountered the same error. My project uses [vue@2.6.x](mailto:vue@2.6.x), but "@vue/compiler-sfc" can only be used in [vue@3.x](mailto:vue@3.x). Have you solved the problem? How?

I were use `ttypescript` and `typescript-transform-paths` instead of `vite-plugin-dts`, cuz final I use `rollup` instead of `vite` for build project,too!

**Comment by qmhc** [comment]
Now the supported Vue version is following Volar.
