### ISSUE TITLE
Weird bug with types folder

### ISSUE THREAD

**Issue by ArtursTimofejevs** [qmhc/vite-plugin-dts#153]
### Describe the bug

We have a mono-repository that is using `vite-plugin-dts` to generate declaration files for each of the packages inside of our mono-repository. 

Basic setup is like so:

```text
mono
- packages
-- app
-- shared
```

But the problem lies when we try to compile app, it seems to get confused with the types folder. Here's the error:

```bash
src/App.tsx:3:23 - error TS6307: File '/Users/arturs/mono-bug/packages/app/src/types/App.types.ts' is not listed within the file list of project '/Users/arturs/mono-bug/packages/app/tsconfig.json'. Projects must list all f
│ 3 import { AType } from './types/App.types';
```

Not sure if it is related to it being a mono repo or not but I have linked code to reproduce.

### Reproduction

https://github.com/ArtursTimofejevs/mono-bug

### Steps to reproduce

- Clone repository
- Run `pnpm install`
- Run `pnpm run build`

**Expected**
Build runs and all is good

**Result**
Get an error to do with types folder as described above.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 71.91 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 107.0.5304.121
    Safari: 16.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Original post
https://github.com/qmhc/vite-plugin-dts/issues/149

**Comment by MarekPrzydanek** [comment]
Looks like a bug related with Typescript references. My code works with `vite-plugin-dts` up to 1.6.6, doesn't work with ^1.7.0.

**Comment by ArtursTimofejevs** [comment]
@MarekPrzydanek thanks for that! I have opted to build the types after the vite build is complete for now. But I may try to implement lower version of `vite-plugin-dts` in order to test it.

**Comment by qmhc** [comment]
The outputs are right. This diagnostics log (is a warning) will disappear after remove the composite option (or set it to false).

Before 1.7.0, diagnostics is default skipped, now it is executed be default.

**Comment by MarekPrzydanek** [comment]
@qmhc the composite option is required to use Typescript references. Does that mean the plugin does not support them?

I succeeded to generate types using `@rollup/plugin-typescript` without any warnings and the composite option turned on. I couldn't make it work in monorepo with VS Code debugger though, but that's probably unrelated cause Intellisense and tsc in the final app worked correctly.
