### ISSUE TITLE
Is it's able adapt to node 12

### ISSUE THREAD

**Issue by Hisioni** [qmhc/vite-plugin-dts#156]
### Description

in `package.json`
```json
 "engines": {
    "node": "^14.18.0 || >=16.0.0"
 },
```
--------------------
our develop computer is win7, high support node version is node v12, so cuz it, can't use this vite plugin, could it's able to adapt to use on node 12?

### Suggested solution

run on node 12

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
The `engines` field follows `vite`, you can use the patch command via your package manager to adjust the `package.json` of this project.

**Comment by Hisioni** [comment]
i thought as a tool lib, should be provided that the oldest environment for supports

thank you a lot, use the way u said able solve my problem as well.
