### ISSUE TITLE
生成vue.d.ts文件时如果组件嵌套了 多层子组件，会导致报错TS7056

### ISSUE THREAD

**Issue by luguoj** [qmhc/vite-plugin-dts#157]
如果vue组件嵌套了多层子组件，生成的d.ts文件会在DefineComponent的泛型参数的RawBindings参数中循环生成每一层的子组件类型声明，这将导致泛型过于复杂报错"TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed. "
请问有什么方法处理么

**Comment by qmhc** [comment]
请提供一个复现，以帮助定位问题。

**Comment by Gengkaibo** [comment]
我的代码里边用到了这个组件，ElCascader, 生成d.ts时候遇到同样的报错"TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed. "


const elCascaderRef = ref<InstanceType<typeof ElCascader>>()
