### ISSUE TITLE
The dts file cannot be generated if tsconfig is not in the root directory

### ISSUE THREAD

**Issue by yingpengsha** [qmhc/vite-plugin-dts#159]
### Describe the bug

The dts file cannot be generated if tsconfig is not in the root directory

### Reproduction

https://github.com/yingpengsha/vite-plugin-dts-issue-reproduction

### Steps to reproduce

- Run `pnpm install` followed by `pnpm build`
- Examine the dist folder under the packages/normal directory
- Only the js file is generated, not the dts file

### System Info

```shell
System:
  OS: macOS 12.6.2
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 20.83 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
  Yarn: 1.22.11 - ~/.nvm/versions/node/v16.10.0/bin/yarn
  npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
Browsers:
  Chrome: 108.0.5359.98
  Firefox: 96.0.2
  Firefox Developer Edition: 103.0
  Safari: 16.2
npmPackages:
  vite: ^4.0.1 => 4.0.1 
  vite-plugin-dts: ^1.7.1 => 1.7.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kaustubhkagrawal** [comment]
Same issue occurring to me in nx monorepo project. Not sure how to proceed.

**Comment by qmhc** [comment]
The `root` config in vite is changed to other and tsconfig.json is in the project root. so you need to specify the `root` and `outputDir` in plugin options.

```ts
dts({
  tsConfigFilePath: joinCurrentDir('./tsconfig.json'),
  root: __dirname,
  outputDir: joinCurrentDir('./packages/normal/dist')
})
```
