### ISSUE TITLE
默认配置输出的文件为何多了一层"src"目录

### ISSUE THREAD

**Issue by mqhe2007** [qmhc/vite-plugin-dts#16]
![image](https://user-images.githubusercontent.com/13450661/124245025-26d18a80-db52-11eb-9f5c-5d6d251640cf.png)
如图，默认配置。

**Comment by qmhc** [comment]
生成类型文件时会保持相对于 `root` 的目录结构，整体输出到 `outputDir` 下，这是为了保证各类型相互引用的正确关系。
如果你想要有一个固定出口，你可以使用 `insertTypesEntry` 选项，否则你需要在 `package.json` 下准确指定到入口文件对应的 `d.ts` 类型文件。

例如：你的入口文件是 `<root>/src/foo.ts`，输出目录是 `dist`，在未使用 `insertTypesEntry` 选项时，入口文件对应的类型文件为 `<root>/dist/src/foo.d.ts`。

如果你想要最终只生成一个单独的 `d.ts` 类型文件，我推荐你在用插件生成类型文件后，使用 [@microsoft/api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor) 来打包类型文件。

**Comment by mqhe2007** [comment]
> 生成类型文件时会保持相对于 `root` 的目录结构，整体输出到 `outputDir` 下，这是为了保证各类型相互引用的正确关系。
> 如果你想要有一个固定出口，你可以使用 `insertTypesEntry` 选项，否则你需要在 `package.json` 下准确指定到入口文件对应的 `d.ts` 类型文件。
> 
> 例如：你的入口文件是 `<root>/src/foo.ts`，输出目录是 `dist`，在未使用 `insertTypesEntry` 选项时，入口文件对应的类型文件为 `<root>/dist/src/foo.d.ts`。
> 
> 如果你想要最终只生成一个单独的 `d.ts` 类型文件，我推荐你在用插件生成类型文件后，使用 [@microsoft/api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor) 来打包类型文件。

感谢解惑，我采用了在package.json里指定types属性。

**Comment by guoyunhe** [comment]
@qmhc `tsconfig.json` 的 [`rootDir`](https://www.typescriptlang.org/tsconfig#rootDir) 是 tsc 控制这个行为的选项。默认情况下，tsc 输出是不会有 src 文件夹的。

**Comment by qmhc** [comment]
@guoyunhe 

在存在多个文件夹时，ts 打包会从 root 开始维持原有文件夹结构输出到 outDir，插件将该行为统一至了只有一个文件夹时的情况。

我们可以重新打开一个新的 issue 讨论这个问题。

**Comment by harry118** [comment]
所以最后是怎么去掉src目录呢？我写了insertTypesEntry还是不行啊 
![image](https://user-images.githubusercontent.com/98019105/184632122-ee926ee9-4687-42de-9b71-8406c0dcbaf0.png)
