### ISSUE TITLE
vite-plugin-dts does not skip css files

### ISSUE THREAD

**Issue by paul-clavier** [qmhc/vite-plugin-dts#166]
### Describe the bug

I am building a react component library and using vite to bundle my application. 
When building my library, `vite-plugin-dts` throws an error as it cannot find type definitions for the css file (which is exepcted, what I do not expect is to receive an error)

<img width="1128" alt="Capture d’écran 2023-02-01 à 15 26 04" src="https://user-images.githubusercontent.com/96700160/216069713-11391cc4-e11d-468f-aab5-01edcd67d340.png">

### Reproduction

https://stackblitz.com/edit/js-58ykfc?file=index.js

### Steps to reproduce

Run `npm install`, then `npm build`

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 949.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/opt/nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/opt/nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 103.0.1
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-react-swc: 3.0.0 => 3.0.0
    vite: 4.0.0 => 4.0.0
    vite-plugin-dts: ^1.7.2 => 1.7.2
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You need to add the `types; ["vite/client"]` option to `compilerOptions` in tsconfig.json.

**Comment by paul-clavier** [comment]
Thank you. Can you explain why adding `types: ["vite/client"]` prevents me from having this issue ?

**Comment by petyosi** [comment]
Thanks for the tip @qmhc , for the record, `vite/client` contains the following: 

```ts
// CSS modules
type CSSModuleClasses = { readonly [key: string]: string }

declare module '*.module.css' {
  const classes: CSSModuleClasses
  export default classes
}
declare module '*.module.scss' {
  const classes: CSSModuleClasses
  export default classes
}
declare module '*.module.sass' {
  const classes: CSSModuleClasses
  export default classes
}
declare module '*.module.less' {
  const classes: CSSModuleClasses
  export default classes
}
declare module '*.module.styl' {
  const classes: CSSModuleClasses
  export default classes
}
declare module '*.module.stylus' {
  const classes: CSSModuleClasses
  export default classes
}
declare module '*.module.pcss' {
  const classes: CSSModuleClasses
  export default classes
}
declare module '*.module.sss' {
  const classes: CSSModuleClasses
  export default classes
}

```
