### ISSUE TITLE
Generated components.d.ts instead of index.d.ts

### ISSUE THREAD

**Issue by lixiaofa** [qmhc/vite-plugin-dts#170]
### Describe the bug

I want to generate index.d.ts, not components.d.ts

How do I configure
![image](https://user-images.githubusercontent.com/23230215/218071752-ba4c985c-e11f-4413-93a8-084bda9dc895.png)

### Reproduction

https://github.com/lixiaofa/vant-sku

### Steps to reproduce

pnpm dev

### System Info

```shell
"vite": "^4.0.0",
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Because you activate the `copyDtsFiles` option (default: `true`).

The `components.d.ts` and `auto-imports.d.ts` are soure dts files in your project.

The generated dts files are under the `dist/src`.

**Comment by lixiaofa** [comment]
> The `components.d.ts` and `auto-imports.d.ts` are soure dts files in your project.
> 
> The generated dts files are under the `dist/src`.
@qmhc 
How do I configure？
