### ISSUE TITLE
No type file generated

### ISSUE THREAD

**Issue by lixiaofa** [qmhc/vite-plugin-dts#172]
### Describe the bug

![image](https://user-images.githubusercontent.com/23230215/218427090-088f9d5f-6dce-4e5b-a678-52293789df9d.png)
No type file generated

### Reproduction

https://github.com/lixiaofa/vant-sku

### Steps to reproduce

pnpm build

### System Info

```shell
"vite-plugin-dts": "^1.7.2",
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Check `dist/src`.

**Comment by lixiaofa** [comment]
> 

什么意思， 是说 代码错误造成不生成类型文件吗
@qmhc

**Comment by qmhc** [comment]
检查 `dist/src` 文件夹，然后关于插件的选项可以阅读 Readme 中的选项章节。
