### ISSUE TITLE
Option to simplify console output

### ISSUE THREAD

**Issue by guoyunhe** [qmhc/vite-plugin-dts#177]
### Description

The current console output is like:

```
vite v4.1.2 building for production...
✓ 6 modules transformed.
dist/index.js  0.92 kB │ gzip: 0.49 kB
dist/index.mjs  1.07 kB │ gzip: 0.51 kB

[vite:dts] Start generate declaration files...
[vite:dts] Start rollup declaration files...
[vite:dts] Declaration files built in 1960ms.
```

The plugin's output is very different from vite itself.

Would be nice to have something like:

```
vite v4.1.2 building for production...
✓ 6 modules transformed.
dist/index.js  0.92 kB │ gzip: 0.49 kB
dist/index.mjs  1.07 kB │ gzip: 0.51 kB
dist/index.d.ts  2.35 kB │ gzip: 0.87 kB
```

### Suggested solution

May be an option to disable progress output?

```js
{
  disableDetailOutput: true,
  logOutputFiles: true,
}
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
The part of rollup types requires the real file system, so is not easy to use the vite reporter plugin.

I plan to create a option to control whether should log or which level should log, just like the vite. And it will follow the `logLevel` of vite when not be specified.
