### ISSUE TITLE
setup interface Props transfrom dismiss

### ISSUE THREAD

**Issue by Miofly** [qmhc/vite-plugin-dts#182]
### Describe the bug

when i use unplugin-vue-macros/vite i can import props in external files，but build error
```vue
<script setup lang="ts">
import type { TestProps } from './props';

const {
	name, type
} = defineProps<TestProps>();
</script>

<template>
	<div>
		name:{{ name }}
		type:{{ type }}
	</div>
</template>

<style scoped lang="scss">

</style>
```

### Reproduction

[as example](https://github.com/Miofly/vite-macros-ts-generate)

### Steps to reproduce

pnpm build-ts

### System Info

```shell
null
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Miofly** [comment]
I don't know if this issue is due to vue3 itself supporting ts, but the results of the current conversion are not what I want

**Comment by qmhc** [comment]
Infer ts intersection types is not a normalize feature of vue, see https://github.com/vuejs/core/issues/4294 and https://github.com/vuejs/core/pull/7394. (the PR of this feature is ready to merge, maybe come soon)

`unplugin-vue-macros`  implements this via a inner plugin, but it will lose types definition of props when transform. (and I don't know whether the official implementation will also is it)

So, I think you'd better use the js props or literal props type currently. And we keep this issue open to track the progress.

**Comment by Miofly** [comment]
vue3.3 is publish, unplugin-vue-macros/vite whether the relevant function can be supported，exp 

```
const ns = /* hoist-static*/ useNamespace('logo');

defineOptions({
	name: ns.b()
});
```

when i use unplugin-vue-macros/vite  hoistStatic: true build error
