### ISSUE TITLE
Incorrect types for a lib that depends on other libs in a monorepo (Nx)

### ISSUE THREAD

**Issue by struggling-dev** [qmhc/vite-plugin-dts#199]
### Describe the bug

Let's assume I have two libs in my monorepo
- `lib-a`
- `lib-b`
and `lib-b` imports some components/types from `lib-a`. While the bundled js file for `lib-b` correctly includes the imported stuff from `lib-a` the `.d.ts` file for `lib-b` relies on the existence of `@my-scope/lib-a` which it won't be when I publish `lib-b`.

<img width="1195" alt="dts-import-error" src="https://user-images.githubusercontent.com/130234999/230732120-00828361-ca13-41f9-ace0-560e6ac68f84.png">

### Reproduction

https://github.com/struggling-dev/nx-publishable-lib

### Steps to reproduce

- Run `nx build lib-b`. Please notice the errors in the console
- The generate `dist/libs/lib-b/lib/lib-b.d.ts` relies on the existence of `@my-scope/lib-a`

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.76 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 112.1.50.114
    Chrome: 109.0.5414.87
    Firefox Developer Edition: 102.0
    Safari: 16.4
    Safari Technology Preview: 16.4
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.1.0 
    vite: ^4.0.1 => 4.2.1 
    vite-plugin-dts: ~1.7.1 => 1.7.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You can upgrade to `3.0.0`, remove the `entryRoot` and specify `insertTypesEntry: true`.
