### ISSUE TITLE
test:e2e  error 

### ISSUE THREAD

**Issue by klwfwdk** [qmhc/vite-plugin-dts#2]
test:e2e  error 

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)

**Comment by klwfwdk** [comment]
node v12.18.2
npm 7.13.0
ts 4.2.4

**Comment by qmhc** [comment]
This is not a bug.

Node v12 can not parse `foo?.baz` syntax, you can upgrade Node to v14 to resolve this problem temporarily.
