### ISSUE TITLE
'--jsx' is not set

### ISSUE THREAD

**Issue by yeshaojun** [qmhc/vite-plugin-dts#201]
### Describe the bug

使用tsx语法，打包会报 '--jsx' is not set.
![image](https://user-images.githubusercontent.com/16093065/231347178-bb2523cc-0b58-42b3-984f-e30e7f48eb29.png)

### Reproduction

https://stackblitz.com/edit/node-5rkwv2?file=src%2Fcomponents%2Fbutton%2Fsrc%2Fbutton.tsx

### System Info

```shell
vue 3.2.47 + vite4.1.4
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
你提供的示例缺失了 Button 组件，无法正常运行。

**Comment by yeshaojun** [comment]
不好意思，提供的示例被修改了。

**Comment by yeshaojun** [comment]
不好意思，提供的示例被修改了。
配置tsconfig修改为tsconfig.app.json成功了，之前一直用的是tsconfig.json
