### ISSUE TITLE
Different bundle after use `npm run build` if not remove the output dir

### ISSUE THREAD

**Issue by L1atte** [qmhc/vite-plugin-dts#203]
### Describe the bug

It's the first build result as follows:
![1681955759699](https://user-images.githubusercontent.com/59164539/233237965-a5972a17-2ff6-4c9d-86be-8347c48430a8.png)

And it is the second build result if not remove the dist folder:
![1681955854033](https://user-images.githubusercontent.com/59164539/233238183-3ac289cf-f723-4c62-8752-db10b11443c8.png)

I wonder if this makes sense？

Here is the minimum recurrence: [https://stackblitz.com/edit/vitejs-vite-qzld1n?file=src/index.ts](https://stackblitz.com/edit/vitejs-vite-qzld1n?file=src/index.ts)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-eixypa?file=vite.config.ts

### Steps to reproduce

first build: `npm run build`
second build `npm run build`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: ^4.3.0-beta.2 => 4.3.0-beta.8 
    vite-plugin-dts: ^2.3.0 => 2.3.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Correct in `3.0.0`.

**Comment by L1atte** [comment]
> Correct in `3.0.0`.

Thanks a lot
