### ISSUE TITLE
Add missing external dependencies to peerDependencies list

### ISSUE THREAD

**Issue by arianics** [qmhc/vite-plugin-dts#204]
### Describe the bug

Please add [external dependencies](https://github.com/qmhc/vite-plugin-dts/blob/main/build.config.ts#L5) to peerDependencies list.  Some build systems (bazel) rely on this info  to fetch appropriate dependencies in a sandboxed environment.

### Reproduction

n/a

### Steps to reproduce

`bazel build path/to/package:build`

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 43.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 104.0.1
    Safari: 16.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Fixed in `3.0.0-beta.2`.
