### ISSUE TITLE
How to generate d.ts from external directory

### ISSUE THREAD

**Issue by keyiis** [qmhc/vite-plugin-dts#206]
### Describe the bug

I used `paths` import some interface from external directory,It's not under in my app directory,below is my tsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "es2020",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "strict": true,
        "removeComments": true,
        "skipLibCheck":true,
        "sourceMap": true,
        "outDir": "./dist",
        "declaration": true,
        "pretty": true,
        // "strictNullChecks": true,
        "lib": ["esnext", "dom"],
        "baseUrl": ".",
        "paths": {
            "@serverInterface": [ "D:/projects/other/base/interface" ]
        }
    },
    "include": ["src"],
    "references": [{ "path": "./tsconfig.node.json" }]
}
```
Then i used vite-plugin-dts in vite.config.ts
```
import { defineConfig } from 'vite'
import dts from 'vite-plugin-dts'

export default defineConfig({
  resolve: {
    alias: {
      '@serverInterface': "D:/projects/other/base/interface",
    },
  },
  build: {
    lib: {
      entry: './src/index.ts',  //库的入口
      formats: ['es', 'umd'],
      name: 'calculator', //这里是你的包的名字，假设是firstadd
      fileName:"index"
    },
    rollupOptions: {
      output: {
      },
    }
  },
  plugins: [dts({
    // copyDtsFiles: true,
  })],
})
```
The actual result is that the d.ts is not packaged into the dist directory.

### Reproduction

the external directory can't Reproduction

### System Info

```shell
npx envinfo --system --npmPackages '{vite,@vitejs/*,vite-plugin-dts}' --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 3.33 GB / 15.80 GB
  Binaries:
    Node: 18.13.0 - D:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.64)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^4.3.5 => 4.3.5
    vite-plugin-dts: ^2.3.0 => 2.3.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by keyiis** [comment]
The errors
```
> build
> vite build

vite v4.3.5 building for production...
✓ 1 modules transformed.
dist/index.mjs  1.68 kB │ gzip: 0.81 kB
dist/index.umd.js  1.50 kB │ gzip: 0.87 kB

[vite:dts] Start generate declaration files...
src/index.ts:1:50 - error TS6059: File 'D:/projects/other/interface/index.ts' is not under 'rootDir' 'D:/projects/calculator'. 'rootDir' is expected to contain all source files.
```
but I already add to rootDir
```
import { defineConfig } from 'vite'
import dts from 'vite-plugin-dts'

export default defineConfig({
  resolve: {
    alias: {
      '@serverInterface': "D:/projects/other/interface",
    },
  },
  build: {
    lib: {
      entry: './src/index.ts',  //库的入口
      formats: ['es', 'umd'],
      name: 'calculator', //这里是你的包的名字，假设是firstadd
      fileName:"index"
    },
    rollupOptions: {
      output: {
      },
    }
  },
  plugins: [dts({
    rootDirs: ["./src", "D:/projects/other/interface"],
  })],
})
```

**Comment by chenweigh** [comment]
same problem.

**Comment by ShirlyKong** [comment]
same problem width 2.3.0。  External directory that  setting by tsconfig includes can be generate with version 1.7.3, although there are errors. such as  import type { default } from 'ol/Map';

**Comment by ShirlyKong** [comment]
> same problem width 2.3.0. External directory that setting by tsconfig includes can be generate with version 1.7.3, although there are errors. such as import type { default } from 'ol/Map';

soleved this by config root option, viteDts({
      root: "../",
      ....
}. version 2.3.0

**Comment by chenweigh** [comment]
### Desc
```
pnpm workspace project:

demo/src/app.vue
demo/vite.config.ts
demo/package.json

util/date.ts
util/package.json
```

```vue
//demo/src/app.vue
import {formatData} from 'util'
```
### Problem
build finished. ✅
there are no util/date.d.ts file 

### Help
So  how to generate workspace package ?

**Comment by ShirlyKong** [comment]
> ### Desc
> ```
> pnpm workspace project:
> 
> demo/src/app.vue
> demo/vite.config.ts
> demo/package.json
> 
> util/date.ts
> util/package.json
> ```
> 
> ```
> //demo/src/app.vue
> import {formatData} from 'util'
> ```
> 
> ### Problem
> build finished. ✅ there are no util/date.d.ts file
> 
> ### Help
> So how to generate *.d.ts workspace package ?
 you may just add src to be included in  tsconfig settings.
 tsconfig.json add the util folder into include like this  `inlcude:` ["src", "../util"]` or include all other folder like this  "include": ["../**/*.ts", "../**/*.d.ts", "../**/*.tsx", "../**/*.vue"]

**Comment by chenweigh** [comment]
> > ### Desc
> > ```
> > pnpm workspace project:
> > 
> > demo/src/app.vue
> > demo/vite.config.ts
> > demo/package.json
> > 
> > util/date.ts
> > util/package.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > //demo/src/app.vue
> > import {formatData} from 'util'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Problem
> > build finished. ✅ there are no util/date.d.ts file
> > ### Help
> > So how to generate _.d.ts workspace package ?
> > you may just add src to be included in  tsconfig settings.
> > tsconfig.json add the util folder into include like this  `inlcude:` ["src", "../util"]`or include all other folder like this `"include": ["../**/_.ts", "../**/*.d.ts", "../**/_.tsx", "../**/_.vue"]`

Everything is ok now.
add config:
//demo & util parent dir.
root: "../"

**Comment by qmhc** [comment]
Does it still exist in `3.0.0-beta.2`?
