### ISSUE TITLE
Problem importing JSON file

### ISSUE THREAD

**Issue by jure123** [qmhc/vite-plugin-dts#215]
### Describe the bug

In .ts file I'm importing and using JSON file:
`import json from "./file.json";`

dts plugin writes the same line to d.ts file, but it does not export the actual file.json to types/ folder. So compiler throws error while resolving this d.ts file, because "./file.json" does not exist.

Is there any option so dts plugin to convert json to .d.ts? It could resolve the type of json file in the similar way that TS compiler converts JSON to JS.

Or at least if it's possible to copy the original JSON files to types folder?

### Reproduction

/

### System Info

```shell
vite-plugin-dts@1.5.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kolirt** [comment]
same problem
