### ISSUE TITLE
Multiple build issues with issues that seem to have no reason to them all of which worked before various updates

### ISSUE THREAD

**Issue by VividLemon** [qmhc/vite-plugin-dts#218]
### Describe the bug

Things are completely out of line in how they are functioning for me. 
I get an error like
```
src/components/BBadge/BBadge.vue.ts:10:7 - error TS2742: The inferred type of '_sfc_main' cannot be named without a reference to '.pnpm/vue-router@4.2.0_vue@3.3.4/node_modules/vue-router'. This is likely not portable. A type annotation is necessary.
```
But I've had the following tsconfig for awhile
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["**/*.spec.*", "**/*.test.*"],
  "compilerOptions": {
    "types": ["vitest/globals", "vite/client"],
    "baseUrl": ".",
    "paths": {
      "vue-router": ["node_modules/vue-router"],
      "@vueuse/shared": ["node_modules/@vueuse/shared"],
      "@floating-ui/core": ["node_modules/@floating-ui/core"]
    }
  }
}

```
So, vue-router is typed annotated. 

Every single one of my instances seemingly are the result of a upstream component. So, that above component imports another component, which is the one that holds the vue-router type reference.

Now, to make things more complicated, I have components that never even _touch_ the vue-router instance, but throw errors anyways. For example, I have one components whos imports are 
```ts
import type {Booleanish, TransitionMode} from '../../types'
import {computed, type TransitionProps} from 'vue'
import {useBooleanish} from '../../composables'
```
None of which are related to vue-router. -- unless, the import cycle has issues with the namespace of `/composables` or `/types` which will, somewhere inside them have an import relating to vue-router... But this still doesn't answer the question why, if it's defined in paths, why it doesn't work... Or answer the question on why only some select components are throwing this issue and not all that are connected to it in some way.

To go off of the above a bit more, I have this file:

![image](https://github.com/qmhc/vite-plugin-dts/assets/31498096/847205e8-f59c-40ac-943f-cc7d8d13c0da)

if I do
```ts
const items: BreadcrumbItem[] = []
// or
const items = reactive([])
```
both work,
but if I combine them and do
```ts
const items = reactive<BreadcrumbItem[]>([])
```
I get an obscure `The inferred type of 'default' cannot be named without a reference to '.pnpm/vue-router@4.2.2_vue@3.3.4/node_modules/vue-router'.`. Which, viewing the file, has nothing to do with vue-router. The only thing odd about this error message is it does `@4.2.2_vue@3.3.4`. I'm not sure what this is. Is it vue-router, or vue? It certainly doesn't exist in my node_modules, of either the root or individual package node_modules. I tried adding "vue" to the tsconfig paths, but it has no affect.

And yet, there's even more random issues. 

![image](https://github.com/qmhc/vite-plugin-dts/assets/31498096/83d2d365-3839-489f-a3de-2e63c99d833f)
![image](https://github.com/qmhc/vite-plugin-dts/assets/31498096/6fc8115c-19b1-4ed4-b1a1-247fd28b7279)
So, an item that has a clear type, somehow implicitly has any type? 
This issue could be related to the dist file being 
![image](https://github.com/qmhc/vite-plugin-dts/assets/31498096/46aef5fd-ede5-4944-adf2-45c5c31dd3bb)
Which, in this case, I'm not sure how I would begin to fix. But this is a bit odd as I'm not sure how or why this plugin would infer the types from a js file. 

Ok, so all this is a bit confusing, so why not try updating the dependencies one more time... This then makes all my imports fail with `src/components/BAccordion/BAccordionItem.vue.ts:5:23 - error TS2307: Cannot find module '../BCollapse.vue' or its corresponding type declarations`... Okay. This might be a TS issue at it's heart. But regardless, it still contains some of the issues shown above, and I'm guessing, but expecting that once those import issues get fixed, the other issues will return just as quickly. 

So a multitude of problems when generating dts files. Which is bad because I cannot do anything until this issue gets sorted out. 

### Reproduction

https://github.com/bootstrap-vue-next/bootstrap-vue-next

### Steps to reproduce

I really can't explain how I reached this point. A minimum example is nearly impossible as I can't begin to figure out where the root issue is. 

The original, and current version, still with issues is https://github.com/bootstrap-vue-next/bootstrap-vue-next . You can do `pnpm i --ignore-scripts` & `pnpm build` at the workspace root. 

Otherwise, there's my branch with the latest amount of broken things

https://github.com/VividLemon/bootstrap-vue-next 

I'm sorry, obviously a full repository is a hard place to start, but I simply cannot pinpoint why or how things are breaking. It could be an issue with TypeScript, it could be an issue with Vue 3.3, it could be an issue with Vite plugin dts, it could be an issue with pnpm. The issues only really started occurring during the initial update to Vue 3.3. In which all packages were updated at the same time. 

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 7.77 GB / 15.53 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.2.0 - /run/user/1000/fnm_multishells/24376_1685818507445/bin/node
    npm: 9.6.6 - /run/user/1000/fnm_multishells/24376_1685818507445/bin/npm
  Browsers:
    Firefox: 113.0.2
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
Now, without changing anything, coming back to it a day later results in none of the `Cannot find module '../BCollapse.vue' or its corresponding type declarations`, but as expected, all of the 
`Parameter 'item' implicitly has an 'any' type.`
&
`The inferred type of 'default' cannot be named without a reference to '.pnpm/vue-router@4.2.2_vue@3.3.4/node_modules/vue-router'. This is likely not portable. A type annotation is necessary.` persist

**Comment by MrBrax** [comment]
yes i get a ton of errors as well, even `An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.`

**Comment by VividLemon** [comment]
> yes i get a ton of errors as well, even `An async function or method in ES5/ES3 requires the 'Promise' constructor. Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.`

Your issue probably has to do with your tsconfig. You'll likely want to choose your lib version. 2020 is what vite prefers, or you can use esnext

**Comment by VividLemon** [comment]
> > > yes i get a ton of errors as well, even `An async function or method in ES5/ES3 requires the 'Promise' constructor. Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.`
> > 
> > 
> > Your issue probably has to do with your tsconfig. You'll likely want to choose your lib version. 2020 is what vite prefers, or you can use esnext
> 
> i'm using vite configs which use @vue/tsconfig which use es2020, so probably okay? except it can't be found when using this plugin
> 
> ```
> [vite:dts] Start generate declaration files...
> error TS2468: Cannot find global value 'Promise'.
> error TS6053: File '@vue/tsconfig/tsconfig.dom.json' not found.
> env.d.ts:1:23 - error TS2688: Cannot find type definition file for 'vite/client'.
> ```

It should be noted, that the default tsconfig path is 'tsconfig.json'. However, when combined with the Vue defaults, you'll likely want to either set this in the plugin options as `dts({tsConfigFilePath: 'tsconfig.app.json'})` or `dts({tsConfigFilePath: 'tsconfig.dom.json'})` It may be simply that you're using the wrong tsconfig. 

In addition to this,`File '@vue/tsconfig/tsconfig.dom.json' not found.` indicates that you're expecting @vue/tsconfig v0.4, but it may not be installed as 0.4. You may want to check this out.
