### ISSUE TITLE
monorepo模式下打包后`.d.ts`输出路径问题

### ISSUE THREAD

**Issue by zguiyang** [qmhc/vite-plugin-dts#219]
### Describe the bug

在vite配置文件中设置为库打包模式，并将`packages/xx` 作为库根目录进行打包，打包后作为根目录的`.d.ts`文件位置未与`js`文件位置保持一致。
示例中，我将`packages/my-test-ui`作为打包后的根目录，此目录下生成的`.d.ts`我希望和打包的入口文件都出现在`dist/esm`、`dist/lib`根目录中，实际效果却是`packages/my-test-ui`目录下输出的`.d.ts`文件没有出现在打包后的根目录中

### Reproduction

https://stackblitz.com/edit/vitejs-vite-k1pofw?file=dist%2Fesm%2Findex.js,package.json&terminal=dev

### Steps to reproduce

1. 执行`pnpm run build` or `npm run build`
2. 查看`dist`目录

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 5.34 GB / 13.87 GB
  Binaries:
    Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1778.0), Chromium (114.0.1823.37)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
在 monorepo 场景，你可以尝试将 root 设置为总包的入口，将 entryRoot 设置为子包的入口（`my-test-ui`）。

**Comment by zguiyang** [comment]
> 

抱歉，我没太懂你的意思，可以用我示例里的代码说明一下吗？非常感谢🙏🏻

**Comment by qmhc** [comment]
你可以尝试在插件选项中加入 `entryRoot: resolve(__dirname, 'packages/my-test-ui')`，不过这种形式打包出来的目录结构不这么好看。

**Comment by zguiyang** [comment]
> 你可以尝试在插件选项中加入 `entryRoot: resolve(__dirname, 'packages/my-test-ui')`，不过这种形式打包出来的目录结构不这么好看。
好的，感谢，刚刚我也试了下你说的方案，发现生成的目录结构确实不尽人意，并且缺失了包入口的声明文件
> 补充：再检查了一下，原本是可以通过 `insertTypesEntry: true` 解决的，但是目前缺少了对多入口的支持。
哇，那就期待插件的后续更新了，感谢解答🙏🏻😄

**Comment by qmhc** [comment]
你可以再尝试一下添加 `insertTypesEntry: true` 同时将 `lib.entry` 改为对象的形式。

https://stackblitz.com/edit/vitejs-vite-wf3k6u?file=vite.config.ts

**Comment by zguiyang** [comment]
> 再看了一下发现是你配置上有点问题。你的 `lib.entry` 三个文件都是 `index.ts`，插件无法正确的推断入口名称。
> 
> 你可以再尝试一下添加 `insertTypesEntry: true` 同时将 `lib.entry` 改为对象的形式。
> 
> https://stackblitz.com/edit/vitejs-vite-wf3k6u?file=vite.config.ts
> 
> ![image](https://user-images.githubusercontent.com/40221744/249181543-0cb758dc-ffe0-4ffc-bea4-e6d60e44ec00.png)
这样配置，确实能够解决打包的问题，但是这个目录结构并不是我想要的，我希望的是

**Comment by qmhc** [comment]
那你无需指定指定其他入口，只需要将 `resolve(__dirname, 'packages/my-test-ui/index.ts')` 作为唯一入口即可。

dts 的编译并不解析 js 部分的内容，所以会维持原有的文件结构，如果你需要调整可以通过插件提供的钩子函数，或者自己添加后处理脚本。

dts 的目录结构也不会影响实际内容的导出，用户也不会关注库里打包出来的目录结构是怎么样的，如果纯粹为了看的话我建议是不要折腾，通过 package.json 的 exports 字段细粒度控制导出以及充分的文档指引更加重要。

**Comment by zguiyang** [comment]
> 那你无需指定指定其他入口，只需要将 `resolve(__dirname, 'packages/my-test-ui/index.ts')` 作为唯一入口即可。
> 
> dts 的编译并不解析 js 部分的内容，所以会维持原有的文件结构，如果你需要调整可以通过插件提供的钩子函数，或者自己添加后处理脚本。
> 
> dts 的目录结构不会影响实际内容的导出（仅提供导出的内容的类型推导），用户也不会关注库里打包出来的目录结构是怎么样的，如果纯粹为了看的话我建议是不要折腾，通过 package.json 的 exports 字段细粒度控制导出以及充分的文档指引更加重要。

好的，明白了，目前我本地的项目就是通过插件的钩子函数处理的，只是我觉得如果插件能够一步到位最好😄。

**Comment by pot-code** [comment]
@qmhc 你好，我和楼主有一样的问，我想请问下 dts 插件如果没有用后处理选项，是不是做不到和 vite 打包指定根目录并设置 preserveModulesRoot 一样的效果？即保留目录结构，但是可以把 root 指定的包的输出打平到输出目录。我看到 dts 插件的输出还是按照 packages 目录的结构进行输出。

例如的打包入口是 packages/lib，最后 dts 还是原样输出了 lib 目录，和其他子包的目录平级。但是 js 文件是只有 lib 包的内容被打平输出，其他包保持原始结构和包名。

> 在 monorepo 场景，你可以尝试将 root 设置为总包的入口，将 entryRoot 设置为子包的入口（`my-test-ui`）。

我按照这个方式设置了之后结果没有任何 dts 文件被输出，控制台也没有 outside emitted 这样的信息
