### ISSUE TITLE
Fails to generate types for `defineExpose` with Vue 3.3 & TS 5.0

### ISSUE THREAD

**Issue by segevfiner** [qmhc/vite-plugin-dts#220]
### Describe the bug

We have components with `defineExpose`, the types of `defineExpose` stuff was properly generated in Vue 3.2, but they are no longer generated with Vue 3.3 + TS 5

There are likely other issues with Vue 3.3, such as imported types in `defineProps` not working with an import error, generic components not working, and so on.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-t4ucyt?file=src%2FApp.vue

### Steps to reproduce

`npm exec type-check`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.2.1 => 4.2.1 
    vite: ^4.3.9 => 4.3.9 
    vite-plugin-dts: ^2.3.0 => 2.3.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by segevfiner** [comment]
@qmhc

**Comment by Tanimodori** [comment]
Does v2.3.0 supports TS 5 currently? Maybe related: #190 #194
