### ISSUE TITLE
aliases not working on declaration files in dist/

### ISSUE THREAD

**Issue by chirastefan** [qmhc/vite-plugin-dts#221]
### Describe the bug

1. I'm using `vite-tsconfig-paths` for resolving aliases from the `tsconfig.json` file and `vite-plugin-dts` for generating `.d.ts` files and they work fine inside my project, but after I run `build` (in lib mode) and check the dist folder the imports aliases are not resolved. They point to the src folder, not the dist folder. Adding a relative path works though. Shouldn't the aliases be resolved on build?
2. Shouldn't .types.ts .d.ts files be prefixed with declare so they can be accessed outside the project?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-b6n9u5?file=package.json

### Steps to reproduce

run `npm install` then `npm run build`

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) x64 Apple M1 Pro
    Memory: 37.96 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
  Browsers:
    Brave Browser: 107.1.45.116
    Chrome: 114.0.5735.106
    Firefox: 112.0.2
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-react: 3.1.0 => 3.1.0 
    vite: 4.3.7 => 4.3.7 
    vite-plugin-dts: ^2.3.0 => 2.3.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by everdimension** [comment]
Why is this one "completed"? 
I am facing the same problem, so I think this is an unresolved issue

@qmhc Could you please take a look?

**Comment by qmhc** [comment]
@everdimension Currently you can use `pathsToAliases` option of the plugin.

If you think the issue still exists, you can create a new issue and provode a reproduction with the latest plugin version.

**Comment by everdimension** [comment]
@qmhc 
> Currently you can use pathsToAliases option of the plugin

The docs say it's `true` by default. I tried setting it to both and the result is the same. Currently I had to rewrite all types imports to relative paths

**Comment by qmhc** [comment]
@everdimension You can make a reproduction and create a new issue for it.
