### ISSUE TITLE
Proper watch mode support

### ISSUE THREAD

**Issue by segevfiner** [qmhc/vite-plugin-dts#227]
### Description

Currently vite build watch mode crashes often #193 (When making a change to a file while types compilation is still running on a large enough project so it takes long enough), and doesn't support incremental building, so it has to rebuild all types on each change, which is slow on any decently sized project. Running `vue-tsc -w` directly is capable of building types incrementally which is much faster when iterating on the code.

### Suggested solution

Support rollup watch mode with incremental compilation of TypeScript types properly and fully. No crashing 😛.

### Alternative

Switch to `vue-tsc -w`

### Additional context

https://github.com/vuejs/language-tools/issues/3306

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
Would you try `3.0.0-beta.2` and give me some feedback?

**Comment by segevfiner** [comment]
> Would you try `3.0.0-beta.2` and give me some feedback?

I will ☺️

**Comment by segevfiner** [comment]
Seems much better. Was able to just plug it into the project, update `tsConfigFileName` to `tsconfigFile`, and watch mode seems much faster and from some testing it didn't seem to crash. Hopefully you managed to fix the cause of the crash and it didn't just become rarer by the improved performance.
