### ISSUE TITLE
3.0.0.Beta3 版本编译时，路径层次错误，出现编译失败错误

### ISSUE THREAD

**Issue by herodotus-cloud** [qmhc/vite-plugin-dts#230]
### Describe the bug

个人的工程为基于 pnpm 的 monorepo，各个模块使用 vite 进行编译。在使用 2.3.0 版本时，没有任何问题，基本上没有做额外的配置，只是设置了 `insertTypesEntry`

```javascript
export default defineConfig({
  plugins: [
    dts({
      include: ['src/**/*.ts'],
      insertTypesEntry: true
    })
  ],
```

因为怕出现大量升级依赖导致的不可预期问题，基本上会定期升级依赖然后从新编译库。最近使用 `pnpm up --latest` 命令更新，vite-plugin-dts 会升级到 3.0.0-Beta版。

使用这个版本再次编译已有代码，就会出现编译问题。具体错误如下：

![image](https://github.com/qmhc/vite-plugin-dts/assets/11025512/e1f2d7f1-15a2-4c59-bf15-4ac42663b45f)

最初以为是因为 3.0.0 变化导致，所以尝试去掉 `insertTypesEntry` ，全部采取默认设置。但是这样就会爆出大量类型错误，所以恢复回来，再行定位问题。

经过观察发现，抛错内容指向的路径有误。

> 注：同样的代码，vite-plugin-dts 2.3.0 不会出错，3.0.0 就会出错。

编译生成的 .d.ts 文件，还是会输出到 dist 目录，2.X 和 3. X 都是如此。但是 3.X 抛出的错误中，因为路径中多了 一层 `/src` 所以导致找不到文件，如下图：

![image](https://github.com/qmhc/vite-plugin-dts/assets/11025512/3ce1f2d4-0d87-4101-90e1-1a6d1d39deca)

### Reproduction

https://gitee.com/herodotus/dante-cloud-ui

### Steps to reproduce

```shell

// 1. 执行下面命令，vite-plugin-dts 会升级至最新版

pnpm up --latest 

// 2. 编译库

pnpm shared:build

```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 33.56 GB / 63.75 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.5 - D:\local-cached\npm\nodejs\node_global\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1928.0), Chromium (112.0.1722.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3
    vite: ^4.3.9 => 4.3.9
    vite-plugin-dts: 3.0.0-beta.3 => 3.0.0-beta.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
可以暂时先用 beta.2，beta.3 对 entryRoot 做了一些修改导致了一些问题的发生。
