### ISSUE TITLE
dose rollupTypes options must be true when build in vue

### ISSUE THREAD

**Issue by 52javascript** [qmhc/vite-plugin-dts#234]
### Describe the bug

if rollupTypes = false

the build directory will not keep directory structure

### Reproduction

1

### Steps to reproduce

1

### System Info

```shell
1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Please provide a reproduction, and create the issue follow sections in issue template.
