### ISSUE TITLE
导出 declare module "xxx" 和 declare global 定义的模块扩展支持

### ISSUE THREAD

**Issue by biggerstar** [qmhc/vite-plugin-dts#240]
### Description

当前测试不支持导出 declare module "xxx" 和 declare global ， 而这两个也是拓展其他库常用定义，速度支持-_-      

### 测试导出代码  
``` 
// 为vue库定义一个名为Test新类型 
export declare module "vue"{
    export type Test = { newField : string }
}

```
### 遇到的情况   
通过vite build 编译后无法在构建产物 xxx.d.ts中找到上面定义，此时也是无法通过 import { Test } from 'vue'  引入拓展的新类型

### Suggested solution

.

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
这是一个 api-extractor 已知的问题：https://github.com/microsoft/rushstack/issues/2090 https://github.com/microsoft/rushstack/issues/1709

目前你可以参考 [VueRouter 的做法](https://github.com/vuejs/router/commit/50ad404ae45086f051b01ac552e4a3ab98535633) 或暂时不使用 `rollupTypes` 功能。

**Comment by biggerstar** [comment]
我现在使用了vue-router的做法，但是该做法不够优雅，因为必须准确控制文本切割合并的行数。
后面发现了有这么个仓库，看下可以给您参考下，将其外部配置字符串指向的文件 解析成ast语法树，之后再输出(feature: 给出一个配置合并到同一个文件或者全局定义的d.ts单独输出一个文件  )
您可以考虑后面加上该功能，我觉得手动解析的话可能是当前的最佳实践，也能使vite-plugin-dts更加完美     [rollup-plugin-add-global-ts](https://github.com/gintamamadao/rollup-plugin-add-global-ts)

**Comment by biggerstar** [comment]
我花了点时间写了解决这个问题的通用插件 [vite-plugin-copy-dts](https://github.com/biggerstar/vite-plugin-copy-dts)
