### ISSUE TITLE
Entry file references missing d.ts files

### ISSUE THREAD

**Issue by norahmaria** [qmhc/vite-plugin-dts#244]
### Describe the bug

I'm using `vite-plugin-dts` to provide types for my component library, but it's only generating an `index.d.ts` file (without `rollupTypes` set to true) that imports from non-existing files.

The generated `index.d.ts` file. The files `./components`, `./theme` and `./TypeachConfig.vue` are all in my `src` folder, but not in the dist folder as the package is bundled into one JS file. These TypeScript files do not exists in this folder.
```ts
export * from "./components";
export * from "./theme";
export { default as TypeachConfig } from "./TypeachConfig.vue";
```
I saw on FAQ a question about missing files, but the options `skipDiagnostics` and `logDiagnostics` seem to no longer exists.

I expect for the plugin to either summarize all the types into one `index.d.ts` file, or to create the all the needed `.d.ts` files and reference those in the index file rather then referencing non existing files.

This is my Vite config file.
```ts
import { resolve } from "node:path";
import { fileURLToPath, URL } from "node:url";

import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [vue(), dts({ insertTypesEntry: true, copyDtsFiles: true })],

  resolve: {
    alias: {
      "~": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },

  css: {
    preprocessorOptions: {
      scss: {
        /* eslint-disable-next-line quotes */
        additionalData: '@use "~/scss/index.scss" as *;',
      },
    },
  },

  build: {
    cssCodeSplit: true,

    lib: {
      entry: resolve(__dirname, "src/index.ts"),
      name: "typeach",
      formats: ["es", "cjs", "umd"],
      fileName: format => `typeach.${format}.js`,
    },

    rollupOptions: {
      external: ["vue"],

      output: {
        exports: "named",

        globals: {
          vue: "Vue",
        },

        assetFileNames: assetInfo => {
          if (assetInfo.name === "index.css") {
            return "typeach.css";
          }

          return assetInfo.name ?? "";
        },
      },
    },
  },
});
```
I have three `tsconfig.json` files, but the last one just references the two different environments, App and Node.

App:
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],

  "compilerOptions": {
    "strict": true,
    "noUncheckedIndexedAccess": true,

    "resolveJsonModule": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    }
  }
}
```
Node:
```json
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "include": ["vite.config.*", "vitest.config.*"],

  "compilerOptions": {
    "strict": true,
    "noUncheckedIndexedAccess": true,

    "resolveJsonModule": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    "module": "ES2022",
    "composite": true,
    "types": ["node"]
  }
}
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4id9ug?file=src%2Fvite-env.d.ts

### Steps to reproduce

I provided a link to a MVP, if you run `yarn build` you should see the issue.

### System Info

```shell
System:
  OS: macOS 13.2.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 31.94 GB / 64.00 GB
  Shell: 5.8.1 - /bin/zsh

Binaries:
  Node: 18.16.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.5.1 - /usr/local/bin/npm
  pnpm: 8.6.1 - ~/Library/pnpm/pnpm

Browsers:
  Safari: 16.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Hi, Maria. I think it's because you defined an empty array in `files` of `tsconfig.json`. You can remove it and try again.

**Comment by norahmaria** [comment]
@qmhc ooh, damn, yeah - sorry for wasting your time! Adding ` "include": ["./src/**/*.ts"]` to the root `tsconfig` fixed it ☺️
