### ISSUE TITLE
Regression in sources paths in declaration maps

### ISSUE THREAD

**Issue by ekwoka** [qmhc/vite-plugin-dts#245]
### Describe the bug

v 3.3.0 has broken the source paths in the dts files

```ts
dts({
      entryRoot: resolve(__dirname, 'src'),
      tsconfigPath: resolve(__dirname, 'tsconfig.json'),
    }),
    ```
    
    This would, with 3.2.0 provide declaration maps that looked like
    
    ```
    {"version":3,"file":"index.d.ts","sourceRoot":"","sources":["src/index.ts"],"names":[],"mappings":"AAEA,eAAO,MAAM,KAAK,YAEjB,CAAC"}
    
    ```
    
    But with 3.3.0 they look like
    
    ```
    {"version":3,"file":"index.d.ts","sourceRoot":"","sources":["../src/src/index.ts"],"names":[],"mappings":"AAEA,eAAO,MAAM,KAAK,YAEjB,CAAC"}
    ```
    
    Which doesn't work at all. There is no `src/src` directory.
    
    I guess technically both are wrong? tsc alone would have the path be `../src/index.ts`

### Reproduction

https://github.com/ekwoka/create-kwoka-pkg

### Steps to reproduce

In above repo, the focus is the nested project under `kwoka-pkg` directory. It's basically just a scaffold.

Just add `src/index.ts` in the source with whatever.

Run build.

Then update `vite-plugin-dts` and run build again.

The source paths are different.

But if you do `pnpm exec tsc` the source paths are also different...

So something is wrong here, but 3.3.0 of this plugin is definitely most wrong.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 104.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - ~/Library/pnpm/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.6.7 - ~/Library/pnpm/npm
    pnpm: 8.6.7 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.82
    Safari: 16.5.2
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Could you provide a reproduction?

**Comment by ekwoka** [comment]
Beautiful! Thank you!!
