### ISSUE TITLE
3.3.1打包后部分文件未出现

### ISSUE THREAD

**Issue by jiubanqingchen** [qmhc/vite-plugin-dts#248]
### Describe the bug

打包文件后 部分文件打包不出来，下面做了一个精简后的版本 麻烦帮忙看一下，万分感谢🙏

index.ts

```typescript
import type { App } from "vue";
import * as Components from "./components";

const install = (app: App) => {
  for (const [key, component] of Object.entries(Components)) {
    app.component(component.name, component);
  }
};

export * from "./components";
export * from "./types";

export default {
  install,
};
```

index.d.ts
```typescript
export * from "./components";
export * from "./types";
declare const _default: {
    install: (app: App) => void;
};
export default _default;
```

### Reproduction

https://stackblitz.com/github/jiubanqingchen/vite-plugin-dts-demo?file=README.md

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 23.53 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.2
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3 
    vite: ^4.3.9 => 4.4.4 
    vite-plugin-dts: 3.3.1 => 3.3.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
因为你的 tsconfig.json 中指定了 `"files": []`，不包含任何的文件，移除该选项即可（同时可以添加 `include` 指定更准确的包含范围）。

**Comment by jiubanqingchen** [comment]
按照提供的方法，能否打包成功了，万分感谢🙏

**Comment by lizy0329-biubiubiu** [comment]
在 [vite vue-ts](https://github.com/vitejs/vite/blob/main/packages/create-vite/template-vue-ts/tsconfig.json)  模板中 ，tsconfig.json fies 字段为 [], 所以我在 src 中写
` import { ISomeTypes } from ./types` ，那么编译后的 dist 中一定找不到这个 types.d.ts 文件，从而导致获取类型失败

这个怎么看？
