### ISSUE TITLE
Generated types stay primitives

### ISSUE THREAD

**Issue by KyllianV** [qmhc/vite-plugin-dts#25]
Hello,

First of all thank you for your lib.
I'm encountering an issue with the generated types. I have a Button.vue component like this : 

```
<script setup lang="ts">
type Props = {
  color: "blue" | "red";
};

defineProps<Props>();
</script>

<template>
  <button>Test</button>
</template>
```

The prop `color` is a String that only accepts 2 defined words `blue` and `red`.
But this is the result of the generated `Button.vue.d.ts` file :

![image](https://user-images.githubusercontent.com/15817431/132700574-6d2dda71-c5fe-4120-a855-b76fce06e0df.png)

As you can see, the `color` prop is now a `StringConstructor` and accepts every string. I'm losing the initial typing which is more strict.

This is my `vite.config.ts` file :

```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { resolve } from "path";
import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [vue(), dts()],
  build: {
    lib: {
      entry: resolve(__dirname, "src/main.ts"),
      name: "uikit",
    },
    rollupOptions: {
      external: ["vue"],
      output: {
        globals: {
          vue: "Vue",
        },
      },
    },
  },
});
```

Am I doing something wrong or the lib can't just be more precise with the types ?

**Comment by qmhc** [comment]
Thanks for your using.

This is a limit of ts-props in compiler currently.

A temporary workaround:

```vue
<script setup lang="ts">
import type { PropType } from 'vue'

defineProps({
  color: {
    type: String as PropType<'red' | 'blue'>
  }
})
</script>
```

**Comment by KyllianV** [comment]
When I access the returned value, the generated type looks like this :

![image](https://user-images.githubusercontent.com/15817431/132841665-b7504e45-de03-4a2a-935e-505345017b62.png)

But I still get no completion :

![image](https://user-images.githubusercontent.com/15817431/132841951-30b64aad-da4c-4af2-9dc0-f3158789781d.png)

**Comment by qmhc** [comment]
A temporary workaround is rollback to js-props:

```vue
<script setup lang="ts">
import type { PropType } from 'vue'

type Props = {
  color: 'blue' | 'red' | 'purple'
}
defineProps({
  color: String as PropType<Props['color']>
})
</script>
```

**Comment by KyllianV** [comment]
It works with this syntax, thanks
