### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by AJJackGIS** [qmhc/vite-plugin-dts#250]
### Describe the bug

我们有个组件库工程，凡是使用了defineModel的组件，打包后使用时，都会在组件的script标签末尾报一个错，源码调用的时候没有这个问题。

![image](https://github.com/qmhc/vite-plugin-dts/assets/12505951/29226c10-9953-466d-b787-1427ec7969b2)

请问这个是需要哪里做配置，还是并不支持这个？

"vue": "^3.3.4",
"vite": "^4.4.4",
"vite-plugin-dts": "^3.3.1",
"vue-tsc": "^1.8.5"
"@vitejs/plugin-vue": "^4.2.3",
"@vitejs/plugin-vue-jsx": "^3.0.1",

### Reproduction

......

### System Info

```shell
@vitejs/plugin-vue: ^4.2.3 => 4.2.3
@vitejs/plugin-vue-jsx: ^3.0.1 => 3.0.1
vite: ^4.4.4 => 4.4.4
vite-plugin-dts: ^3.3.1 => 3.3.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
你的描述有点模糊，我没理解各个组件的关系。使用了 defineModel 的组件（A）打包后，使用 A 的 B 组件的 script 内容末尾会报错？

**Comment by AJJackGIS** [comment]
> 你的描述有点模糊，我没理解各个组件的关系。使用了 defineModel 的组件（A）打包后，使用 A 的 B 组件的 script 内容末尾会报错？

我们有个组件库工程，里面封装了一些通用的业务组件，打包完成后，上传到了公司内部的Verdaccio，然后使用vite创建了一个项目工程，安装这个组件库依赖，然后在App.vue中直接测试使用，经过测试，凡是组件库中的业务组件使用了defineModel的组件就会报错，就是A组件使用了defineModel，A的script 内容末尾会报错。我不知道这次我描述清楚了没。

**Comment by qmhc** [comment]
不理解为什么使用 A 组件会出现到 A 的 script？A 的 script 应该属于被打包了的内容，打包后的内容应该为 .js 和 .d.ts 文件。或许你可以借助一些片段代码辅助说明，或者准确指代各个组件的关系。我现在理解上是你直接从使用组件库的项目中，直接通过 node_modules 里打开查看组件库源码。

我建议你还是要提供一个尽可能小的复现，能帮助更快速的帮助其他人理解问题并找到原因，以更快地修复。

**Comment by AJJackGIS** [comment]
> 看上去并不属于dts的问题，dts不会影响运行时代码，你可以去掉dts插件打包一次试试。

试过了，确实还是同样的问题。
