### ISSUE TITLE
Generate types for JS files too

### ISSUE THREAD

**Issue by AlexAegis** [qmhc/vite-plugin-dts#251]
### Description

When using `tsc` on js files with JSDoc comments I get `.d.ts` files as output. But not when I use `vite-plugin-dts`

### Suggested solution

If `allowJs` is enabled in the tsconfig, generate type output for `.js` files too to preserve type information from JSDoc comments.

### Alternative

I have to use `tsc` instead of `vite` for JSDoc based libraries

### Additional context

I tried publishing a library with JSDocs only, but typescript doesn't seem to read those..

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
Here is a [jsdoc example](https://github.com/qmhc/vite-plugin-dts/blob/4738ab29fbd2083e65a51d9fbc0764236098aeb5/examples/ts/src/js-test.js#L14), you can run locally `pnpm run test:ts`, then check `examples/ts/types/index.d.ts#L40`

**Comment by AlexAegis** [comment]
Thank you, that helped!
