### ISSUE TITLE
Types imported or declared in Vue script-setup are not included in output declaration

### ISSUE THREAD

**Issue by smastrom** [qmhc/vite-plugin-dts#261]
### Describe the bug

Hello, firstly, thank you for vite-plugin-dts. I use it in any of my packages, and it has been a pleasant experience since ever.

When bundling my library, I expect that types imported (or defined directly) inside script-setup and passed to `defineProps` macro are always included in the output declaration just like functional components.

This is mostly because I have to retain IntelliSense descriptions.

Not quite sure if this is something unrelated to this package. In that case, sorry in advance.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-u6wy8g?file=vite.config.ts&terminal=dev

### Steps to reproduce

npm run build

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 1.04 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 114.0.1823.55
    Safari: 16.6
    Safari Technology Preview: 17.0
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3
    vite: ^4.4.9 => 4.4.9
    vite-plugin-dts: ^3.5.1 => 3.5.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Hello, I think you are missing 'index.ts' of the root in the `include` section of `tsconfig.json`.

You can change to `"include": ["src", "index.ts"]` and try it again.

PS: If you specified `rollupTypes: true`, you don't need to specify `staticImport` and `insertTypesEntry`, they will be force `true`.

**Comment by smastrom** [comment]
Sorry, I forgot to save the reproduction with the current tsconfig I'm using.

If you check now, the type `BundleProps` is not included in the output.

**Comment by qmhc** [comment]
If you want to export any type, you should export it in the entry. In your case, you should add following in `index.ts`:

```ts
export * from './src/types.ts'
```

When developing component, we typically define the type (and props) in a separate `.ts` file, and then export the component along with its types in a unified export file (`index.ts`). This allows us to export them with just one statement for use elsewhere:

```ts
// src/bundle/types.ts
export interface BundleProps {
  // ...
}
```

```ts
// src/bundle/index.ts
export { default as  Bundle } from './bundle.vue'
export * from './types'
```

```ts
// src/index.ts
export * from './bundle'

// or
// index.ts
export * from './src/bundle'
```

**Comment by smastrom** [comment]
Thank you for your answer, and I know what you're saying, and that's what I do when I want to include types.

Maybe I haven't been clear when I opened the issue, so I'll try to be more precise.

When Vue files with script-setup are defined in the entry point, I would expect that the declaration output includes the type I passed to defineProps **in the DefineComponent declaration**. This way, Intellisense will be available when the consumer hovers a component prop, for example. Which is the same behavior I get in development mode or when the consumer uses a package that has defined ts/tsx components in the entry point.

I hope I've been clear this time, thank you.

**Comment by qmhc** [comment]
I get your meaning totally.

Sorry, I think this feature is highly customized and goes beyond the usual scope of type bundling. You can achieve this requirement by customizing a Resolver (which involves the compilation of `.vue` files and manipulation of AST trees).

**Comment by smastrom** [comment]
Yeah, that's what I suspected when opened the issue:

> Not quite sure if this is something unrelated to this package. In that case, sorry in advance.

Thank you very much for clarifying this, wish you the best!
