### ISSUE TITLE
启用rollupType时出错TypeScript version不兼容的问题

### ISSUE THREAD

**Issue by zhangfisher** [qmhc/vite-plugin-dts#266]
### Describe the bug

TypeScript Version: 5.2.2
当启用rollupType:true时，生成d.ts时出错：

```
[vite:dts] Start rollup declaration files...
Analysis will use the bundled TypeScript version 5.0.4
*** The target project appears to use TypeScript 5.2.2 which is newer than the bundled compiler engine; consider upgrading API Extractor.
```

### Reproduction

https://github.com/

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.69 GB / 15.84 GB
  Binaries:
    Node: 20.4.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\node_stores\npm\packages\yarn.CMD
    npm: 9.7.2 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - D:\node_stores\npm\packages\pnpm.CMD
  Browsers:
    Chrome: 112.0.5615.138
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
这并不是错误，仅是 API Extractor 输出的一个提示语句，无报错时可忽略。
