### ISSUE TITLE
Cross-workspace file references in monorepo causes type-loosing in build results.

### ISSUE THREAD

**Issue by emosheeep** [qmhc/vite-plugin-dts#268]
### Describe the bug

I create a monorepo and I need to publish `target` project to npm. But for some reason(maybe complex directory structure?), the types of build results lost a part.

Here is my project structure, in which `target` reference `a`, `a` reference `b`

```shell
libs
  - a
  - b
target
```
in `target/src/index.ts`
```ts
export { varFromA, varFromB } from '../../libs/a/src';
```
in `libs/a/src/index.ts`
```ts
import { varFromB } from '@libs/b';
export const varFromA = {}
export { varFromB }
```
in `libs/b/src/index.ts`
```ts
export const varFromB: any = 1
```

And the problem is that the types of @libs/b(project b) lost.

<img width="330" alt="image" src="https://github.com/qmhc/vite-plugin-dts/assets/31957758/09e476d0-a2aa-4766-8510-ba08729f05c5">

But If I change in `libs/a/src/index.ts` to:
```ts
import { varFromB } from '../../b/src/index'; // reference from source code
export const varFromA = {}
export { varFromB }
```
Everything runs well, I don't know what happened, please help🙏.

### Reproduction

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-xg9wwn?file=target%2Fvite.config.ts

### Steps to reproduce

```shell
pnpm install
cd target
pnpm build
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
How do you map `@libs/b` to `libs/b/src`? I see that you commented out the alias config in Vite config:

![image](https://github.com/qmhc/vite-plugin-dts/assets/40221744/0820b926-9ddb-453e-8776-c63448dd0540)

**Comment by qmhc** [comment]
I think you can use `resolve.alias` of Vite config section to specify aliases and manually specify `include` of `target/tsconfig.json` like the below:

```json
{
  "extends": "../configs/tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react",
    "noUnusedLocals": true,
    "target": "ESNext",
    "baseUrl": "src",
    "outDir": "dist"
    // "rootDir": "src"
  },
  "exclude": ["node_modules"],
  "references": [
    {
      "path": "../libs/a"
    },
    {
      "path": "../libs/b"
    }
  ],
  "include": [
    "src",
    "../libs"
  ]
}
```

And you should remove `entryRoot` (unnecessary in your demo) and `compilerOptions` of plugin options:

```ts
export default defineConfig({
  build: {
    lib: {
      entry: "src/index.ts",
      fileName: "index",
      formats: ["es"],
    },
  },
  plugins: [
    dtsPlugin({
      staticImport: true,
      insertTypesEntry: true,
    }),
  ],
  resolve: {
    alias: [
      {
        find: /^@libs\/(\w+)/,
        replacement: `${monoRoot}/libs/$1/src`,
      },
    ],
  },
});
```

Last, I think you don't need to specify `rootDir` in all of your `tsconfig.json` files.

**Comment by emosheeep** [comment]
Emmm, this is my company project I worked in, I'm doing some refactor lately. In my option, I have a few questions
1. Does `rootDir` or `entryRoot` option cause this problem? 
2. These problem came from tsconfig not vite-plugin-dts?
