### ISSUE TITLE
Declaration file is not exporting types.

### ISSUE THREAD

**Issue by norvalbv** [qmhc/vite-plugin-dts#269]
### Describe the bug

When building my package using Vite and vite-plugin-dts the outputted types are not exported from the `d.ts` file.

My outputted file looks like this:

```Typescript
import { ReactElement } from 'react';
import { ReactNode } from 'react';

declare const Blog: ({ allBlogs, paramKey, headers }: BlogProps) => ReactElement;
export default Blog;

// omitted for brevity.

declare type ReadTimeType = number | string;

export { }
```

As you can see, nothing bar the default export which is the root index.tsx file is exported. None of the config options seem to change this feature.

I am using Vite library and my config looks like this:

```Typescript
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';
import viteTsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [
    react({ include: /\.(ts|tsx)$/ }),
    viteTsconfigPaths(),
    dts({
      rollupTypes: true,
    }),
  ],
  assetsInclude: ['**/*.md'],
  build: {
    lib: { entry: './src/index.tsx', name: 'react-blogs', fileName: 'index' },
    rollupOptions: {
      external: ['react'],
      output: {
        globals: {
          react: 'react',
        },
      },
    },
  },
});
```

### Reproduction

https://github.com/norvalbv/react-blogs

### Steps to reproduce

- yarn install
- yarn build

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 3.6.1 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Firefox: 117.0.1
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4 
    vite: ^4.4.9 => 4.4.9 
    vite-plugin-dts: ^3.5.3 => 3.5.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Because you are using `rollupTypes: true`, it will make all types into one declaration file. You can remove it and try again.

**Comment by norvalbv** [comment]
Yes, that's because I want all types in one declaration file. If they're not all in one file I have an excessive amount of files for types, which is not needed. However, like I said the types are not being exported from the one file, which is strange.

**Comment by qmhc** [comment]
The types which you want to export you need to export them in your entry file (`index.tsx`):

```ts
// ...
export default Blog;

export * from './types';
// export type * from './types';
```

**Comment by norvalbv** [comment]
Apologies for the late reply, thank you for this. It makes sense. :)
