### ISSUE TITLE
没有正确导出类型

### ISSUE THREAD

**Issue by kanocence** [qmhc/vite-plugin-dts#272]
### Describe the bug

项目目录

```
├─packages
│  └─layout          <------ pnpm build
│    ├─dist
│    ├─src
│    ├─package.json
│    └─vite.config.ts
├─play
├─package.json
├─tsconfig.json
└─vite.config.ts
```

这是`/packages/layout/vite.config`的配置
``` typescript
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import dts from 'vite-plugin-dts';

export default defineConfig({
  build: {
    outDir: './dist',
    emptyOutDir: true,
    cssCodeSplit: true,
    sourcemap: true,
    lib: {
      formats: ['es'],
      entry: [resolve(__dirname, './src/index.ts')],
    }
  },
  define: { 'process.env.NODE_ENV': '"production"' },
  plugins: [vue(), dts()],
});
```

似乎是入口文件读取错了，没有生成 `index.d.ts` 生成了 `vite.config.d.ts`

![image](https://github.com/qmhc/vite-plugin-dts/assets/61108370/c57b8cb4-9c4b-45dc-9837-726dc38615d2)

![image](https://github.com/qmhc/vite-plugin-dts/assets/61108370/81fa7823-f7e8-462e-bdd2-e032fc753c9a)

### Reproduction

暂无

### Steps to reproduce

pnpm up

cd ./packages/layout

pnpm build

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.93 GB / 15.69 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.32.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 117.0.5938.89
    Edge: Spartan (44.22621.2283.0), Chromium (116.0.1938.81)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
请提供一下复现项目。

**Comment by kanocence** [comment]
> 请提供一下复现项目。

https://github.com/kanocence/dts-demo

**Comment by qmhc** [comment]
新版收集文件的逻辑有一些变化，表现上基本是按照 TypeScript 原本的方式去收集（旧版并不是），所以建议你打包的时候最好在打包的 `root` 目录有 `tsconfig.json` 并指定好 `include`，或者直接使用插件选项的 `include`。
