### ISSUE TITLE
The "mainEntryPointFilePath" path does not exist: ./dist/index.d.ts

### ISSUE THREAD

**Issue by nikitamax** [qmhc/vite-plugin-dts#275]
### Describe the bug

I am trying to deploy project to gitlab ci-cd, but getting an error (local build without errors)

`Error: Error parsing ./api-extractor.json:
The "mainEntryPointFilePath" path does not exist: ./dist/index.d.ts
    at Function.prepare (./node_modules/@microsoft/api-extractor/src/api/ExtractorConfig.ts:1033:13)
    at rollupDeclarationFiles (./node_modules/vite-plugin-dts/dist/index.cjs:205:56)
    at Object.writeBundle (./node_modules/vite-plugin-dts/dist/index.cjs:891:13)
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file://./node_modules/rollup/dist/es/shared/node-entry.js:25472:9)
    at async file://./node_modules/rollup/dist/es/shared/node-entry.js:26792:13
    at async catchUnfinishedHookActions (file://./node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at async Module.build (file://./node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:48074:22)
    at async build (./node_modules/@storybook/builder-vite/dist/index.js:159:11024)
    at async Promise.all (index 0)`

vite.config.ts

`import { fileURLToPath, URL } from 'node:url'
import { resolve } from 'path'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify'
import dts from 'vite-plugin-dts'
import { viteStaticCopy } from 'vite-plugin-static-copy'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: { transformAssetUrls },
    }),
    dts({
      rollupTypes: true,
    }),
    vuetify({ autoImport: true, styles: { configFile: 'src/styles/settings.scss' } }),
    viteStaticCopy({
      targets: [
        {
          src: 'build/scss/_variables.scss',
          dest: 'scss'
        }
      ]
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  optimizeDeps: {
    include: ['vuetify'],
  },
  // The important bit...
  build: {
    cssCodeSplit: false,
    lib: {
      // src/main.ts is where we have exported our component(s)
      entry: resolve(__dirname, 'src/main.ts'),
      formats: ['es', 'cjs'],
      name: 'NostroyUILibrary',
      fileName: format => (format === 'es' ? 'index.js' : 'index.common.js'),
    },
    rollupOptions: {
      external: ['vue'],
      output: {
        globals: {
          vue: 'Vue',
        },
      },
    },
  },
})
`

### Reproduction

can't reproduce it using StackBitz

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 712.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.05.15.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.0
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.4.0 
    vite: ^4.4.5 => 4.4.11 
    vite-plugin-dts: ^3.6.0 => 3.6.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by GoodbyeVictoria** [comment]
I have this error too, how do you solve it? Do I need to create a index.d.ts file, but with what content? Could you help me with this?@qmhc

**Comment by qmhc** [comment]
@GoodbyeVictoria Could you provide a reproduction, I can't reproduce this issue.

**Comment by tirthaguha** [comment]
I have this issue, in the exact same manner. 
I'm using react, storybook on vite. When I run build-storybook, it fails. 

Funny, the build does not fail on local, but build always fails on CI system, running on node v18, with error

```bash
19:36:36  => Failed to build the preview
19:36:36  Error: [vite:dts] Error parsing ./api-extractor.json:
19:36:36  The "mainEntryPointFilePath" path does not exist: ./dist/index.d.ts
```

**Comment by tirthaguha** [comment]
@qmhc would it be ok to reopen it, I can now predictably replicate it, accross win/*nix platforms.

**Comment by qmhc** [comment]
@tirthaguha How can I reproduce this issue in Windows system?

**Comment by jurijsk** [comment]
@qmhc I run into the same issue.

Got this error while trying to merge .d.ts-es into one. After fiddling with configs found a solution, you can see the setup that works here: https://github.com/jurijsk/lib-template

Problem is likely to occur if one sets `vite.root` to `./src` and output to `../dist` to have the the generated files land to `./dist` instead of `./dist/src`. Maybe there is a better what to do that but I don't know about it.

And then that fact that package.json/types have a says in the all this does not help [...](https://github.com/qmhc/vite-plugin-dts/blob/8c245baeb14ba628ffc80d69087efe001d8e3aa6/src/plugin.ts#L597C35-L597C41)

if you remove or change `outDir` or `root` from `dts.options` in my project everything will fall apart pretty quickly.

**Comment by terwer** [comment]
```
insertTypesEntry: true 
```
is worked for me, thanks.

**Comment by hanfengv** [comment]
package.json
"types": "./dist/index.d.ts",

**Comment by Kegulf** [comment]
Hot tip for those who experienced this with a repo containing React and Storybook:
Add this nifty thing to your storybook-config in `.storybook/main.ts`.
This will remove `vite-plugin-dts` from your storybook build, as it strictly isn't needed there 😁 

```TS
import { withoutVitePlugins } from '@storybook/builder-vite';

const config = {
  ...
  async viteFinal(config) {
    config.plugins = await withoutVitePlugins(config.plugins, [
      'vite:dts',
    ]);
  
    return config;
  },
};

export default config;
```

**Comment by atpradical** [comment]
@Kegulf 
it works for me, many thanks!

**Comment by Ho3einWave** [comment]
> Hot tip for those who experienced this with a repo containing React and Storybook: Add this nifty thing to your storybook-config in `.storybook/main.ts`. This will remove `vite-plugin-dts` from your storybook build, as it strictly isn't needed there 😁
> 
> ```ts
> import { withoutVitePlugins } from '@storybook/builder-vite';
> 
> const config = {
>   ...
>   async viteFinal(config) {
>     config.plugins = await withoutVitePlugins(config.plugins, [
>       'vite:dts',
>     ]);
>   
>     return config;
>   },
> };
> 
> export default config;
> ```

this worked for me too 👍🏻

**Comment by airtonix** [comment]
back to tsup we go

**Comment by cdauth** [comment]
Had this problem in a new project. I had forgotten to update the export paths in `package.json`, so `exports["."].types` (might be simply `types` in older projects) was set to `"./build/release.d.ts"`. I believe it was set this way by `yarn init`. However, using vite, the build was actually created in `./dist/`. I suspect that the error was caused by trying to write into the `build` directory, which did not actually exist.
