### ISSUE TITLE
maybe regression introduced by v3.6.1

### ISSUE THREAD

**Issue by Shana-AE** [qmhc/vite-plugin-dts#279]
### Describe the bug

After updated to v3.6.1, I found some d.ts files or js files were missing but is ok with v3.6.0 even when v3.6.0 `moduleResolution` has been set.
升级到3.6.1后发现有些d.ts文件或js文件未生成, 但3.6.0正常, 手动设置`moduleResolution`时也能输出d.ts

v3.6.1版本
https://stackblitz.com/edit/vitejs-vite-x9dszy?file=packages%2Ftypes%2Fdist%2Findex.d.ts

v3.6.0版本
https://stackblitz.com/edit/vitejs-vite-skadh5?file=internal%2Fbuild%2Fpackage.json

### Reproduction

https://stackblitz.com/edit/vitejs-vite-x9dszy?file=packages%2Ftypes%2Fdist%2Findex.d.ts

### Steps to reproduce

in each project
- run `pnpm install` 
- cd to `internal/build`
- run `pnpm build`
- see `packages/types/dist/`

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 64.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.3.0 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-vue2: ^2.2.0 => 2.2.0 
    @vitejs/plugin-vue2-jsx: ^1.1.0 => 1.1.0 
    vite: ^4.4.9 => 4.4.11 
    vite-plugin-dts: ^3.6.1 => 3.6.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
谢谢反馈。

不过希望以后能提供一个更小的复现（当前包含很多与 issue 无关的其他依赖），可以有效提高定位和修复的效率，同时减轻大家的负担 😂。
