### ISSUE TITLE
Usage with TSX

### ISSUE THREAD

**Issue by zakiAzfar** [qmhc/vite-plugin-dts#28]
I am trying to use it with react typescript i.e TSX but it is not generating types

**Comment by qmhc** [comment]
Could you provide a reproduce repository?

**Comment by zakiAzfar** [comment]
> Could you provide a reproduce repository?

https://github.com/zakiAzfar/framer-kit

**Comment by qmhc** [comment]
This repository takes a resolve error during build.

Please note that you cannot set `noEmit` option to `ture` in `tsconfig.json`, this will prevent any file be generated.
