### ISSUE TITLE
Support vite 5.0

### ISSUE THREAD

**Issue by pgsandstrom** [qmhc/vite-plugin-dts#284]
### Description

The plugin should work with Vite 5. Currently it does not, since it returns the plugin type from v4, which is not compatible with the plugin type from v5.

### Suggested solution

Upgrade the Vite dependency to v5.

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by padcom** [comment]
I'm not sure about this bug report. I am using the dts plugin with vite 5.0.2 and it works without any issues so far. Do you have a minimal repo where I could see the problem?

**Comment by DesDevCharan** [comment]
I also got issues, when i upgraded to vite 5 . it precisely throws error like

```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
Your configFile is invalid: {{path}}

It threw an error when required, check the stack trace below:

TypeError: (0 , vite_plugin_dts_1.default) is not a function
```

I am using it as `import dts from 'vite-plugin-dts';`

**Comment by padcom** [comment]
@DesDevCharan https://github.com/padcom/mrdr-example/blob/master/packages/c/package.json

It's a test for my mrdr tool, but it contains a project built with vite 5, using the dts plugin to rollup the types. And it works, no problem. The thing that I did, however, was to set the type of the package to "module". Maybe that'll help you out...

**Comment by alvarosabu** [comment]
Dunno if related but, now the dist includes the `src` for the d.ts so the types of the project are not resolving correctly anymore.

Does anyone else have this issue?

![Screenshot_2024-02-06_at_16 51 19](https://github.com/qmhc/vite-plugin-dts/assets/4699008/d25bea01-62ff-448a-a307-c352b6ad62e5)

**Comment by Xenossolitarius** [comment]
@alvarosabu Yea at some moment my dts plugin stopped producing index.d.ts in library mode and now i'm relaying on that src folder.

**Comment by mbret** [comment]
HAving the same issue, I changed my types property in package.json by

"types": "./dist/src/index.d.ts",

however other packages using this one now have this kind of error

 There are types at 'shared/dist/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'shared' library may need to update its package.json or typings.

**Comment by qmhc** [comment]
@alvarosabu @Xenossolitarius @mbret Seems you having a issue differences form this, please create a new issue with reproduction.

**Comment by mbret** [comment]
My issue is the same, the typescript files are generated under `dist/src` rather than `dist/` previously. To fix the issue I just changed entryRoot to "src" and the types are now correctly generated under `dist/` as before.

**Comment by qmhc** [comment]
@mbret Well, but this issue is about the plugin's type definition.

**Comment by mbret** [comment]
You are right, my fault. the initial issue is indeed not what I was talking about. The further discussion on the issue itself led to this problem being talked as well.
