### ISSUE TITLE
export * statements in d.ts can not be use to prompt types of default export.

### ISSUE THREAD

**Issue by emosheeep** [qmhc/vite-plugin-dts#285]
### Describe the bug

I'm facing a problem that I have these lines in my `src/index.ts`
```ts
export { sdk as default } from './sdk';
```
and I use `insertTypesEntry` functionality to generate `dist/index.d.ts` as follows:
```ts
export * from './src/index.d.ts';
```
But when I publish these code to npm and use it, type prompts were gone.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-xwwwbi?file=test.ts

### Steps to reproduce

just run `yarn build` and see `test.ts`.

```ts
import sdk from '.';

sdk.execute(); // types' broken
```

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 86.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.9.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Edge: 119.0.2151.72
    Safari: 17.1
  npmPackages:
    vite: ^4.4.11 => 4.5.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Maybe a workaround:

```ts
import { sdk } from './sdk'
export default sdk
```

**Comment by emosheeep** [comment]
Although...maybe the plugin could do something? such as
```
import _default from './src/index.d.ts';
export * from './src/index.d.ts';
export default _default;
```

**Comment by qmhc** [comment]
This is a flaw of match logic, please wait for it to be fixed.

**Comment by emosheeep** [comment]
That would be great! Thanks a lot.
