### ISSUE TITLE
如何使用Resolvers?有没有示例？

### ISSUE THREAD

**Issue by parlay96** [qmhc/vite-plugin-dts#293]
### Description

![image](https://github.com/qmhc/vite-plugin-dts/assets/32978177/22de94d6-4656-4931-8c4f-1f26835243c2)
我想该这个路径，我需要怎么写解析器呢？

### Suggested solution

![image](https://github.com/qmhc/vite-plugin-dts/assets/32978177/22de94d6-4656-4931-8c4f-1f26835243c2)
我想该这个路径，我需要怎么写解析器呢？

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by livelyPeng** [comment]
![image](https://github.com/qmhc/vite-plugin-dts/assets/32978177/2068ae33-a438-4bbc-9de9-71efa935bcc2)
我不想再beforeWriteFile方法里面去修改我得内容信息

**Comment by livelyPeng** [comment]
![image](https://github.com/qmhc/vite-plugin-dts/assets/32978177/e90f844b-cafc-4739-94ce-ea598d7d660e)
这个gouzi钩子能不能给我一个 内容转换之前的参数， 你给我转换之后的 我确实不好判断啊！

**Comment by livelyPeng** [comment]
还有就是 
![image](https://github.com/qmhc/vite-plugin-dts/assets/32978177/aaaf8df2-f932-4cdd-b520-a6936f21078a)
vite-plugin-dts在打包项目的plugins里面根本没啥作用，为啥要把它跟工程关联起来？它给我感觉完全可以自己独立运行啊。传入一个目录 去找文件即可。vite-plugin-dts并没有对我的打包的文件改变什么。

**Comment by livelyPeng** [comment]
![image](https://github.com/qmhc/vite-plugin-dts/assets/32978177/f78e6af0-ac23-4b4a-b1b3-e764dd9b007a)
如何替换别名呢？

**Comment by livelyPeng** [comment]
你能不能写个文档 示例呢  你文档只有一些方法描述。 谢谢

**Comment by qmhc** [comment]
你可以使用 `aliasesExclude` 忽略所有的别名，然后在 `beforeWriteFile` 中自行处理别名转换。

你可以查看已有的 Resolver 代码查看它们是如何工作的，编写 Resolver 需要你对 TypeScript 编译有一定的基础了解，它接受一些文件的原始信息和 TypeScript 编译相关的对象，需返回转换后的 dts 文件路径和内容。

**Comment by livelyPeng** [comment]
@qmhc 谢谢

**Comment by qmhc** [comment]
> 它给我感觉完全可以自己独立运行啊

当一样东西能够处理各种东西，人们更倾向于都用它来解决，就像如果你在使用 Vue，你会更倾向使用 Vue 编写的库，而不是原生 js 编写的。

当然你提的这个获取可以作为后面的开发计划，为其提供一个可单独使用的途径。

**Comment by livelyPeng** [comment]
![image](https://github.com/qmhc/vite-plugin-dts/assets/32978177/aad204c6-57fd-441c-8abe-c59d426c7b60)
@qmhc 为啥我这里老是 排除不掉呢

**Comment by HaibaraAiSherry** [comment]
老哥，你的这个问题解决没，在monorepo下面，如果设置了paths，声明文件确实是会被转换成相对路径，但是如果用aliasesExclude忽略掉路径别名的话，最终生成的文件里面，又会把其他monorepo仓库下的声明也合并到当前仓库，我们应该遇到的是同样的问题。

**Comment by Roman-Lo** [comment]
> 老哥，你的这个问题解决没，在monorepo下面，如果设置了paths，声明文件确实是会被转换成相对路径，但是如果用aliasesExclude忽略掉路径别名的话，最终生成的文件里面，又会把其他monorepo仓库下的声明也合并到当前仓库，我们应该遇到的是同样的问题。

我这两天也是遇到了类似的问题。最终也是通过`aliasesExclude`解决了，我的做法是这个字段设置的值跟主配置的`rollupOptions.external`的值一致，那么他的输出行为其实也会跟rollup打包行为一致。

不过因为我的组件有很多secondary entries，所以用了正则匹配去处理别名排除
