### ISSUE TITLE
SvelteComponentTyped is used with svelte 4 and it's deprecated

### ISSUE THREAD

**Issue by stemaDev** [qmhc/vite-plugin-dts#299]
### Describe the bug

When I'm compiling, the .d.ts file includes SvelteComponentTyped which was deprecated in svelte4. I don't know if there are any differences in the object that it references behind this type, but it should be replaced with SvelteComponent instead. This way whenever I'm importing the components I get this deprecated warning.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-srb31p

### Steps to reproduce

Create a svelte project and export a component, use the type in another project.

In the stackblitz pls delete "dist" folder and run "npm run build" and check out the .d.ts file, at the top you see the importing of a deprecated file even though the project uses svelte4

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 12.84 GB / 31.77 GB
  Binaries:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.2 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: 120.0.6099.224
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    vite: 5.0.11 => 5.0.11
    vite-plugin-dts: 3.7.1 => 3.7.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Will that break projects written with svelte 3?

**Comment by GjorgjievskiMarko** [comment]
Any updates on this issue?
