### ISSUE TITLE
vite-plugin-dts does not support <script lang="tsx">

### ISSUE THREAD

**Issue by Hollelihanqi** [qmhc/vite-plugin-dts#300]
### Describe the bug

Use tsx in the script tag to write the vue3 component, and when packaging and generating the declaration file, an error is reported。

### Reproduction

lihanqi.com

### System Info

```shell
vue ui
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Would you provide a minimum reproduction?

**Comment by wuyuedefeng** [comment]
same problem

**Comment by qmhc** [comment]
@wuyuedefeng May you provide a reproduction?

**Comment by wuyuedefeng** [comment]
> @wuyuedefeng May you provide a reproduction?

Ok, this is the project: https://github.com/dyn-components/json-view-vue
build commond: `npm run build:lib`

**Comment by wuyuedefeng** [comment]
from: https://github.com/qmhc/vite-plugin-dts/issues/347#issue-2400223986
Now I used the version: 3.7.3, it work ok.

**Comment by qmhc** [comment]
@wuyuedefeng You can refer to this [FAQ](https://github.com/qmhc/vite-plugin-dts?tab=readme-ov-file#get-module-not-found-errors-during-build).

**Comment by wuyuedefeng** [comment]
Thanks, It's solved.
