### ISSUE TITLE
生成类型错误 import关键词

### ISSUE THREAD

**Issue by Leovenn** [qmhc/vite-plugin-dts#301]
### Describe the bug

import 变量关键词 生成的类型错误  具体看示例

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ttfjga?file=vite.config.ts

### Steps to reproduce

仓库中npm run build后
在dist中查看生成的类型

### System Info

```shell
示例仓库中可最小化复现
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Now a workaround is to set `clearPureImport` to `false`.

**Comment by Leovenn** [comment]
> Now a workaround is to set `clearPureImport` to `false`.现在的解决方法是将 `clearPureImport` `false` 设置为 。

Received. Thank you.
