### ISSUE TITLE
Can I customize the generated d.ts files, or merge a specific d.ts file into the compiled output?

### ISSUE THREAD

**Issue by s3xysteak** [qmhc/vite-plugin-dts#303]
### Description

I am using `{ rollupTypes: true }` with `vite-plugin-dts`.
I use `transform` to custom some code in output index.ts:
```js
defineConfig({
  plugins: [
     {
      apply: 'build',
      transform(code,id){
        // ...
        return ` export const example =  ...` + code
      }
    },
    dts({ rollupTypes: true, })
  ]
})
```
Obviously, doing so would result in the lack of type declarations for 'example'.
Is there any ways to add the type declarations to d.ts?

### Suggested solution

Maybe like: 
```js
const custom = 'types/customTypes.d.ts'
dts({ rollupTypes: true, custom })
```
before
```ts
// ...
import type { someLibsA } from 'libsA'

export { something }

export {}
```
after
```ts
import type { someLibsA } from 'libsA'
import type { fromCustomTypes } from 'codeFromCustomTypes '

export { something }
// code in customTypes.d.ts
export {}
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
Maybe you can try to use `afterBuild` options.

**Comment by s3xysteak** [comment]
> Maybe you can try to use `afterBuild` options and process the result file by anyway you like.

It is confusing that `afterBuild` callback do not need to return anything. How could I change the result by afterBuild?
```js
afterBuild: ( dtsMap ) => {
  const path = fileURLToPath(
    new URL('../../dist/index.d.ts', import.meta.url)
  ).replace(/\\/g, '/')

  const content = dtsMap.get(path)

  dtsMap.set(path, content + `export declare const testAfterBuild: string;\r\n`)
}
```

**Comment by s3xysteak** [comment]
I see. It is not only use to edit generated file but also do anything I want. I just rewrite the file and achieve what I want. 
```js
{
afterBuild: dtsMap => {
  const path = fileURLToPath(
    new URL('../../dist/index.d.ts', import.meta.url)
  ).replace(/\\/g, '/')

  writeFileSync(
    path,
    dtsMap.get(path) +
      '\r\n' +
      `export declare const autoImport: string[];` +
      '\r\n'
  )
}
}
```

**Comment by s3xysteak** [comment]
@qmhc 看起来首页英文文档最下面，关于`afterBuild`的说明有错误，和中文文档不一致
```ts
/**
 * Hook called after all declaration files are written
 *
 * It will be received a map (path -> content) that records those emitted files
 *
 * @default () => {}
 */
afterBuild?: () => MaybePromise<void>
```
```ts
/**
 * 在所有类型文件被写入后调用的钩子
 *
 * 它会接收一个记录了那些最终被写入的文件的映射（path -> content）
 *
 * @default () => {}
 */
afterBuild?: (emittedFiles: Map<string, string>) => MaybePromise<void>
```
