### ISSUE TITLE
Before .ts analysed hook

### ISSUE THREAD

**Issue by s3xysteak** [qmhc/vite-plugin-dts#308]
### Description

I want to change the entry file before build:
```js
{
  enforce: 'pre',
  transform(code,id){
    // ...
    return code + '\n' + value
  }
}
```
But dts throw a error when I do that. Could it export a options to change file before it is anlaysed by dts?

### Suggested solution

Maybe like
```js
dts({
  transform(code, id){
    // ...
  }
})
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
What error threw and what you changed?

**Comment by s3xysteak** [comment]
Sorry for my haste, I couldn't reproduce the problem, but still found a problem after building successfully.
```ts
// src/index.ts

export * from './core/one'
```
```ts
// vite.config.ts

function reExport(): Plugin {
  return {
    name: 're-export',
    enforce: 'pre',
    transform(code, id) {
      if (id.endsWith('src/index.ts'))
        // Here !
        return `${code}\n` + `export * from './core/two'` 
    },
  }
}
export default defineConfig({
  plugins: [
    reExport(),
    dts({ rollupTypes: true }),
  ]
})
```
So after building, the result is:
```js
// dist/index.js

const t = () => 1, e = () => 2;
export {
  t as getOne,
  e as getTwo
};
```
But in dts is:
```ts
// dist/index.d.ts

export declare const getOne: () => number;

export { }
```
It missed the `getTwo`.

**Comment by qmhc** [comment]
You can try to use `load` hook to customize.

**Comment by s3xysteak** [comment]
So is there no way to achieve that by `Vite` hooks or any other in a "less aggressive" manner?
I think maybe it could only be solved by scripts.
```ts
// scripts/reExport.ts
writeFileSync(...)
// package
{ build: "esno reExport.ts && tsc && vite build" }
```
