### ISSUE TITLE
Wrong declaration file for union types with null or undefined

### ISSUE THREAD

**Issue by cpicou-patool** [qmhc/vite-plugin-dts#311]
### Describe the bug

Hello,
I'm using vite-plugin-dts to generate declaration files for a library that shares Vue 3 reusable code (components, composables, Pinia stores...).
The problem is that `vite-plugin-dts` generate an incorrect declaration file for "internal states" (Pinia, composable) definitions when using union types with null or undefined
I've noticed the problem with a Pinia store but when trying to build a minimal reproduction case, it seems to be unrelated to Pinia.

Example : 
```
import { type MyType } from '@/types';
import { ref, type Ref } from 'vue';

export const externalState: Ref<MyType | null> = ref(null);
export const useMyComposable = () => {
  const nullableInternalState: Ref<MyType | null> = ref(null);
  const stringableInternalState: Ref<MyType | string> = ref();
  const undefinableInternalState: Ref<MyType | undefined> = ref(undefined);
  const noRefInternalState: MyType | null = null;

  return {
    nullableInternalState,
    stringableInternalState,
    undefinableInternalState,
    noRefInternalState
  };
};
```

The corresponding declaration file : 
```
import { type MyType } from '@/types';
import { type Ref } from 'vue';
export declare const externalState: Ref<MyType | null>;
export declare const useMyComposable: () => {
    nullableInternalState: Ref<MyType>;
    stringableInternalState: Ref<string | MyType>;
    undefinableInternalState: Ref<MyType>;
    noRefInternalState: MyType;
};

```
You can notice that declarations of type `MyType|null` or `MyType|undefined` have been replaced by `MyType` only when declared as an internal const.

So when I'm using this library, I've got a transpilation error when I'm doing things like `nullableInternalState.value = null`

Here's my vite.config.ts file : 
```
import { fileURLToPath, URL } from 'node:url';

import { defineConfig } from 'vite';
import { configDefaults } from 'vitest/config';
import vue from '@vitejs/plugin-vue';
import dts from 'vite-plugin-dts';

export default defineConfig({
  plugins: [
    vue(),
    dts({
      insertTypesEntry: true
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
    extensions: ['.js', '.json', '.jsx', '.mjs', '.ts', '.tsx', '.vue']
  },
  test: {
    environment: 'jsdom',
    exclude: [...configDefaults.exclude, 'e2e/*'],
    root: fileURLToPath(new URL('./', import.meta.url)),
    setupFiles: ['./vitest/setup.ts']
  },
  build: {
    emptyOutDir: true,
    outDir: 'dist',
    sourcemap: true,
    lib: {
      entry: {
        composables: './src/composables/index.ts',
        types: './src/types/index.ts'
      },
      formats: ['es', 'cjs']
    },
    rollupOptions: {
      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: ['vue'],
      output: {
        // Provide global variables to use in the UMD build
        // for externalized deps
        globals: {
          vue: 'Vue'
        }
      }
    }
  }
});

```

Thank you

### Reproduction

https://github.com/cpicou-patool/test-plugin-dts

### Steps to reproduce

- Run `yarn install`
- Run `yarn build`
- Check the content of `/dist/composable/useMyComposable.d.ts`

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 3.41 GB / 15.88 GB
  Binaries:
    Node: 18.17.0 - ~\AppData\Local\nvm\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Local\nvm\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.19041.3636
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You should add `"strict": true` to your `tsconfig.json` file.

**Comment by cpicou-patool** [comment]
> You should add `"strict": true` to your `tsconfig.json` file.

Shame on me, thank you very much !
