### ISSUE TITLE
现在源文件以.d.ts结尾的文件没法打包到dist目录中

### ISSUE THREAD

**Issue by junjun666** [qmhc/vite-plugin-dts#312]
### Describe the bug

![image](https://github.com/qmhc/vite-plugin-dts/assets/35680677/2b8c43b6-1c80-4a73-b150-0294a7c8c8f9)
这种以xxx.d.ts的文件现在在打包的时候，并没有打包到对应目录中，有什么配置项可以直接原封不动迁移到dist目录中么？

### Reproduction

111

### System Info

```shell
node v18.18.2
vite  v5.1.4
vite-plugin-dts v3.7.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by junjun666** [comment]
<img width="340" alt="image" src="https://github.com/qmhc/vite-plugin-dts/assets/35680677/b763c7b0-aa19-431e-bc01-13e7e73be9ad">
辛苦大佬帮看看这个问题该怎么解决呢？

**Comment by qmhc** [comment]
请阅读文档的插件选项，内有控制是否复制 dts 源文件的选项。
