### ISSUE TITLE
 The inferred type of 'default' cannot be named without a reference to '.pnpm/vue@2.7.16/node_modules/vue'. This is likely not portable. A type annotation is necessary

### ISSUE THREAD

**Issue by shaobeichen** [qmhc/vite-plugin-dts#315]
### Describe the bug

![image](https://github.com/qmhc/vite-plugin-dts/assets/18715564/ca1c85e2-e29d-4cc0-bfad-b77edd5582f7)

In vue-demi, it is possible to switch the version of Vue. There is no problem when switching to Vue3, but when switching to Vue2, this error is reported. Can this error be attributed to the following figure? How should I handle it temporarily?
Now tsconfig is like this,
```
   /* alias */
    "baseUrl": "src",
    "paths": {
      "@/*": ["./*"],
      "@": ["./"]
    }
```

![image](https://github.com/qmhc/vite-plugin-dts/assets/18715564/99eea880-a3bc-4b0e-9563-d2d0f5e879bd)

### Reproduction

https://stackblitz.com/?starters=vite

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.61 GB / 15.75 GB
  Binaries:
    Node: 18.19.1 - ~\.nvm\versions\node\v18.19.1\bin\node.EXE
    npm: 10.2.4 - ~\.nvm\versions\node\v18.19.1\bin\npm.CMD
    pnpm: 7.9.5 - ~\.nvm\versions\node\v18.19.1\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
```

### Validations

- [x] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Please provide a reproduction.
