### ISSUE TITLE
Version 3.8.1 doesn't work with path aliases

### ISSUE THREAD

**Issue by ohkimur** [qmhc/vite-plugin-dts#317]
### Describe the bug

Since version 3.8.1, the plugin doesn't update the paths as 3.7.3.

### Reproduction

-

### Steps to reproduce

I identified 2 cases where the plugin doesn't work as expected:
  1. When using the plugin with `vite-tsconfig-paths`
  2. When using the plugin with aliases like the following:
  ```ts
  resolve: {
    alias: {
      "@": resolve(fileURLToPath(new URL(".", import.meta.url)), "./src"),
    },
  },
  ```

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 67.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v21.5.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 17.3.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Please provide a reproduction.

**Comment by qmhc** [comment]
@CodingDive I reproduced your case and now I'm looking for the reason.

But I'm not sure if your problem is the same as @ohkimur.

**Comment by ohkimur** [comment]
@qmhc This solved my issue too.
