### ISSUE TITLE
Errors being swallowed when `rollupTypes: true`

### ISSUE THREAD

**Issue by GeordiD** [qmhc/vite-plugin-dts#322]
### Describe the bug

I've noticed that `vite-plugin-dts` will report type errors in the build logs but not halt the build. This causes a lot of messy errors in our build logs that should be fixed, but because nothing is stopping CI they keep sneaking into master.

The easiest way I can reproduce this is with `api-extractor` errors by not tagging exports with `@public`. I made a reproduction repo showing that which is linked. 

I have also seen this happen with non `api-extractor` errors (i.e. didn't have `jest-extended` types wired into the tsconfig right and it was throwing errors during `vite build` but not `tsc`).

Is this expected behavior for this library? I'd really like my build script to not produce errors, and I'd think that any generated errors should blow up the build and force us to fix them. If I've gone to all the trouble of marking that these api-extractor messages should be "errors" then it'd be nice if they could kill the build too.

Maybe I'm missing a option somewhere? 

### Reproduction

https://github.com/GeordiD/repro-dts-not-throwing-errors

### Steps to reproduce

1. Install node_modules: pnpm i
1. Run build: pnpm run build

```shell
> repro-dts-not-throwing-errors@0.0.0 build /Users/geordi/dev/repros/repro-dts-not-throwing-errors
> tsc && vite build

vite v5.2.0 building for production...
✓ 1 modules transformed.

[vite:dts] Start generate declaration files...
dist/my-lib.js  0.18 kB │ gzip: 0.16 kB
[vite:dts] Start rollup declaration files...
Analysis will use the bundled TypeScript version 5.4.2
Error: dist/main.d.ts:1:1 - (ae-missing-release-tag) "setupCounter" is part of the package's API, but it is missing a release tag (@alpha, @beta, @public, or @internal)
[vite:dts] Declaration files built in 456ms.

✓ built in 492ms
```

### System Info

```
System:
    OS: 14.2.1 (23C71)
    CPU: Apple M1 Pro
    Memory: 32 GB
    Shell: zsh
Binaries:
  Node: v18.16.0
  pnpm: 8.6.9
npmPackages:
  typescript: ^5.2.2
  vite: ^5.2.0,
  vite-plugin-dts: ^3.8.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by GeordiD** [comment]
Digging into the source code, it looks like the result is being returned here as `false` when there is an error [here](https://github.com/qmhc/vite-plugin-dts/blob/main/src/rollup.ts#L96)...

...but that return value is never used anywhere ([here](https://github.com/qmhc/vite-plugin-dts/blob/main/src/plugin.ts#L686-L696)). 

I can't figure out how I would stop the build process from inside this function. Very new to rollup/vite plugins 🤔

I'm also not sure the intention is to halt the build process here. Technically the plugin did it's job.

But if I have it configured to log as an error, shouldn't I be able to configure the plugin to stop the build in cases like this? 

(🤷 I'm just someone new to open source trying to help out / asking questions)

**Comment by qmhc** [comment]
I added a option 'afterRollup', it will be called after each `rollupDeclarationFiles` applied. Hope this can solve your issue.

**Comment by kahagerman** [comment]
To resolve this, I was able to use:
```
dts({
	rollupTypes: true,
	afterDiagnostic: (diagnostics) => {
		if (diagnostics.length) {
			throw new Error("lint failure");
		}
	},
}),
```

But this really should be the default behaviour.
