### ISSUE TITLE
【Regression】Library which use IterableIterator.entries() cause TS Error.

### ISSUE THREAD

**Issue by pronitsateli731** [qmhc/vite-plugin-dts#323]
### Describe the bug

I develop a library which use Vue having multiple entry points, which has utility functions not only components.
In them, some functions use IterableIterator.entries().
Those can build in vite-plugin-dts 3.7.2, but when I upgrade vite-plugin-dts >= 3.8.0, TS error happened.
For example for reproduction, this simple function
![スクリーンショット 2024-04-22 095657](https://github.com/qmhc/vite-plugin-dts/assets/133564027/810d1fae-5f94-41c8-a75f-f25dc90cbbbb)
 cause error as below.
![スクリーンショット 2024-04-22 095311](https://github.com/qmhc/vite-plugin-dts/assets/133564027/6010ce50-8c94-40f5-bbe9-0dc36d6ad185)

### Reproduction

https://github.com/pronitsateli731/vite-plugin-dts-report-r60421

### Steps to reproduce

Run `npm install` and `npm run build`.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 39.72 GB / 47.81 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^5.0.4 => 5.0.4 
    vite: ^5.2.8 => 5.2.9 
    vite-plugin-dts: ^3.8.3 => 3.8.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You can add `tsconfigPath: resolve(dirname(fileURLToPath(import.meta.url)), './tsconfig.app.json')` to the plugin options as workaround currently.

**Comment by pronitsateli731** [comment]
This options works.
Thank you.
