### ISSUE TITLE
升级 language-tools 到 2.0

### ISSUE THREAD

**Issue by jellyfishgh** [qmhc/vite-plugin-dts#324]
### Description

vscode volar 插件升级为 vue-official 插件，搭配 vue-tsc 为 2.0 版本

### Suggested solution

升级 vue-tsc @vue/language-core 两个依赖到最新的 2.0 版本

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
这个是在计划内的，但 volar2 破坏性更新非常多，并且目前缺乏文档指导，需要研读源码，经过评估工作量比较大，会是一个比较漫长的过程。
