### ISSUE TITLE
Wrong definition generations since 3.8.2 for 

### ISSUE THREAD

**Issue by skill83** [qmhc/vite-plugin-dts#325]
### Describe the bug

It seems that after 3.8.2 update in same cases the generation of the type definitions if cleanVueFileName is set to true, is wrong when there is a "PropType<import("
![Screenshot 2024-05-03 alle 11 55 44](https://github.com/qmhc/vite-plugin-dts/assets/656011/26c3a8d0-bbe1-49d2-a6b3-a4b3d4877b72)
![Screenshot 2024-05-03 alle 11 57 31](https://github.com/qmhc/vite-plugin-dts/assets/656011/16ce5887-ee25-4785-9659-b4591c36c40c)

The issue is still present in 3.9.0.

Thanks
![Screenshot 2024-05-03 alle 12 12 20](https://github.com/qmhc/vite-plugin-dts/assets/656011/77ae6a1e-4528-49e0-92c2-bec85410d02b)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bpsvcd?file=vite.config.ts,tsconfig.json,package.json,index.html,src%2Fvite-env.d.ts,src%2Fmain.ts,src%2FApp.vue,src%2Fcomponents%2FBreadcrumbCmp.vue,src%2Fcomponents%2Findex.ts,src%2Fcomponents%2Flib.ts,yarn.lock,dist%2Flib.d.ts&terminal=dev

### Steps to reproduce

yarn
yarn build

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 55.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
  Browsers:
    Chrome: 124.0.6367.119
    Edge: 124.0.2478.67
    Firefox: 124.0.2
    Safari: 17.4.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 0x1f57** [comment]
Oops, this problem reappeared in 4.0.3
