### ISSUE TITLE
打包一个库的时候，defineProps问题

### ISSUE THREAD

**Issue by 21236774** [qmhc/vite-plugin-dts#327]
### Describe the bug

const props = defineProps(defineProp) 不会生成.d.ts类型文件
defineProps(defineProp)  这样就会生成.d.ts类型文件

### Reproduction

https://github.com/qmhc/vite-plugin-dts

### System Info

```shell
"vite-plugin-dts": "1.4.1"
"4.3.9": "4.3.9"
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
请更新版本
