### ISSUE TITLE
Invalid imports in generated d.ts for project with tsconfig path alias defined for any module

### ISSUE THREAD

**Issue by k-i-m** [qmhc/vite-plugin-dts#330]
### Describe the bug

I have a project, where I have path aliases defined in `tsconfig.json` to simplify usage of any module within src folder:
```
    "paths": {
      "*": ["src/*"],
    },
```
This setting allows to simplify the imports, so that instead of:
`import { Sample } from 'src/components/Sample';` (or even `import { Sample } from '@/components/Sample';`)
we can use:
`import { Sample } from 'components/Sample';`

When I build the app, the app itself works fine (thanks to the `vite-tsconfig-paths`), but all the `d.ts` files for `.ts` files that are inside a subfolder of src, are generated with invalid `import` paths.

The original ts file:
![image](https://github.com/qmhc/vite-plugin-dts/assets/22868198/362bbab3-1221-4029-b968-b474eae99870)
The output d.ts file:
![image](https://github.com/qmhc/vite-plugin-dts/assets/22868198/6d686b3a-5899-47a4-9ad9-b036e0c97991)

It was working fine in `vite-plugin-dts@3.6.4`. Any version since then (so starting from v3.7.0) has the issue.
Possibly there is an issue in this commit that was introduced in 3.7.0:
https://github.com/qmhc/vite-plugin-dts/commit/e8827cb6c8be1406e4e3a9a24639b7b54ca20d53

### Reproduction

https://stackblitz.com/edit/vitejs-vite-sg53ed?file=dist%2Ftypes%2Fcomponents%2FSample%2Findex.d.ts

### Steps to reproduce

- create sample app (react based for example), with vite + vite-plugin-dts + vite-tsconfig-paths
- create any subfolder (like "components") inside `src`, and there create any other folder containing some sample component:
```
src
- components
-- Sample
--- Sample.tsx
--- index.ts
```
where `index.ts` is only reexporting the component
```
export * from './Sample';
```
- import the component in App.tsx: `import { Sample } from 'components/Sample';`

- set the project's configuration:

**package.json**
vite related libraries:
```
    "vite": "^5.2.0",
    "vite-plugin-dts": "^3.9.1",
    "vite-tsconfig-paths": "^4.3.2"
```

 **tsconfig.json**
add the following `"paths"`:
```
    "paths": {
      "*": ["src/*"],
    }
```

**vite.config.ts**
```
import * as path from 'path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import tsconfigPaths from 'vite-tsconfig-paths';

import * as packageJSON from './package.json';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    dts({
      entryRoot: path.resolve(__dirname, 'src'),
      outDir: path.resolve(__dirname, 'dist', 'types'),
    }),
    tsconfigPaths(),
  ],
  build: {
    rollupOptions: {
      external: Object.keys(packageJSON.dependencies),
    },
  },
});
``` 

- run `vite build` command
- in `dist/types` folder you will find d.ts files with invalid import paths

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
    Memory: 13.18 GB / 31.66 GB
  Binaries:
    Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1
    vite: ^5.2.0 => 5.2.11
    vite-plugin-dts: ^3.9.1 => 3.9.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by giuvincenzi** [comment]
The problem is still here. Are there any updates/workarounds?

**Comment by kristof-mattei** [comment]
Temp fix:

`tsconfig.json`:

```
    // ...

    "paths": {
      "@/*": [
        "./src/*",
      ]
    },                                                   /* Specify a set of entries that re-map imports to additional lookup locations. */
    
    // ...

```

`vite.config.mts`: 
```
// ...

export default defineConfig(() => {
    const config: UserConfig = {
        build: {
            // ...
        },

        resolve: { alias: { "@/": path.resolve("src/") } },

        plugins: [
            viteTsConfigPaths(),
            dts({
                insertTypesEntry: true,
                entryRoot: "./src",
                exclude: ["test.setup.ts", "vite.config.ts", "src/tests/**"],
            }),
        ],
        // ...
```

Note the `resolve: { alias: { "@/": path.resolve("src/") } },`. Since it takes a `string: string` we can't import it from `tsconfig.json`, but at the moment, that is ok, I only have 1 line for my paths.

And the generated `.d.ts` don't contain the `@/`, but the `./`, as expected.

**Comment by lachieh** [comment]
See note on #376 

> Hey 👋 v4.1.0 is released which should fix this. I tried to add some test cases to cover the cases mentioned here.
> 
> If any of you could update and test if you're still having the issue? If not, can you post your full tsconfig.json and vite.config.json? Even better would be a codesandbox reproduction.

@k-i-m, @giuvincenzi, @kristof-mattei Could you all try this update?

**Comment by kristof-mattei** [comment]
@lachieh 

To start, thanks for releasing a bugfix. Then, sorry for the late reply.

I've tested with the old 4.0.3 and my `resolve: { alias: { "@/": path.resolve("src/") } },` fix vs the current 4.1.1 without said fix.

Unfortunately it doesn't work for me.

```diff
❯ diff dist-4.0.3/core.d.ts dist-4.1.1/core.d.ts
1,6c1,6
< export * as checks from './checks';
< export * from './commands/base-program';
< export * from './commands/cargo';
< export * from './commands/cross';
< export * from './commands/rustup';
< export * as input from './input';
---
> export * as checks from '@/checks';
> export * from '@/commands/base-program';
> export * from '@/commands/cargo';
> export * from '@/commands/cross';
> export * from '@/commands/rustup';
> export * as input from '@/input';
```

Maybe I'm doing something wrong?

**Comment by lachieh** [comment]
Thanks @kristof-mattei. No worries, I find most gh issues happen quite async.

Could you post your tsconfig?

**Comment by kristof-mattei** [comment]
> Thanks @kristof-mattei. No worries, I find most gh issues happen quite async.
> 
> Could you post your tsconfig?

https://github.com/actions-rs-plus/core/blob/main/tsconfig.json

In that project you can do `npm run build` and then look in `dist/core.d.ts`

and then in vite `vite.config.ts` you can comment out the resolve part and then build again. But then `dist/core.d.ts` isn't correct anymore.

**Comment by lachieh** [comment]
Ahh ok, looks like it goes away with the `baseUrl` being set. I thought that was a requirement, but looks like it was removed in TS4.1. I'll see if I can add some more tests to get coverage and fix the underlying issue.

**Comment by kristof-mattei** [comment]
> Ahh ok, looks like it goes away with the `baseUrl` being set. I thought that was a requirement, but looks like it was removed in TS4.1. I'll see if I can add some more tests to get coverage and fix the underlying issue.

Let me know if you want me to retest stuff / help out.

**Comment by k-i-m** [comment]
The problem still exists in v 4.2.3

I have exact same output as was described in the issue

**Comment by lachieh** [comment]
@k-i-m do you have a `baseUrl` set in your tsconfig? It _should_ work without since TS4.1 doesn't need it anymore but I don't think this lib has accounted for that setting being missing.

**Comment by lachieh** [comment]
I added a PR to hopefully fix the issue

**Comment by lachieh** [comment]
[v4.2.4](https://github.com/qmhc/vite-plugin-dts/releases/tag/v4.2.4) is out! Thanks, @qmhc!

@k-i-m can you retest your issue with this version?

@kristof-mattei the tsconfig file should no longer require the baseUrl now, either!

**Comment by k-i-m** [comment]
The main issue is solved but I still get some weird imports for my 3rd party depencendies, like for React:
`import { Component, ErrorInfo, ReactNode } from '../../react;`

**Comment by lachieh** [comment]
Ah yes, that's a great point. It seems that there isn't really a way to support top level `*` alias without some actual dependency checking.

@qmhc what do you think?

**Comment by qmhc** [comment]
OH, an intractable disease. Let me think...

**Comment by efriandika** [comment]
Just confirmed this problem still exists with version 4.3.0

**Comment by lachieh** [comment]
@qmhc would you accept a solution that adds a check for this specific condition (top-level `*` alias)? I'm thinking we would need to use `resolve` to check if the import exists after it has been modified and then assume it is a dependency if it doesn't exist within the project?

Example:
1. check if alias is '`*`', if no > process like normal
2. if it is, process the import (`'react' becomes `'../../react'`) and attempt to resolve using `import {resolve} from 'node:path'`. If it resolves, leave the import as is and continue
3. if it does not resolve, assume it is (or will be) installed as a dependency

Does that sound like it would work?

**Comment by qmhc** [comment]
@lachieh Yes, my thoughts are very similar to yours.

**Comment by lachieh** [comment]
Added a PR (#396) which probably needs some closer attention. I wanted to try to use the TS program to resolve the paths and see if they had a better way, but in this solution I just used the `existsSync`.

**Comment by lachieh** [comment]
@k-i-m @efriandika This fix has been released in 4.4.0 if you'd like to give it a go and report back if there are issues.

**Comment by k-i-m** [comment]
All good now :) Thank you

**Comment by efriandika** [comment]
I just tried the latest version with baseUrl: '.',
It's still not working.

**Comment by lachieh** [comment]
What's the output you get in the `*.d.ts` files?

**Comment by efriandika** [comment]
The issue is still the same as @k-i-m mentioned. Probably worth to re-open this issue?

How to reproduce:
* Create fresh nx project with ts and vite (it will automatically install latest vite-plugin-dts)
* Create 2 example packages (example-1, example-2)
* In example-1, Import something from example-2 then build.


Example tsconfig
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "paths": {
      "@scope/example-1": ["./packages/example-1/src/index.ts"],
      "@scope/example-2": ["./packages/example-2/src/index.ts"],
    }
  },
  "exclude": ["node_modules", "tmp"]
}

```

Expected import (If I revert the version back to 3.6.4. it's working well.)
```
import Something from '@scope/example-2';
```

The import with latest version:
```
import Something from '../../../../somewhere';
```

**Comment by qmhc** [comment]
@efriandika It seems to be because the alias has been converted, maybe you can try `aliasesExclude` option.

**Comment by lachieh** [comment]
If I configure a normal vite project as you describe without involving `nx`, it works fine: [working example](https://stackblitz.com/edit/vite-plugin-dts-repro-working?file=dist%2Ftypes%2Fsrc%2Findex.d.ts)

**Comment by efriandika** [comment]
I have just [modified your example ](https://stackblitz.com/edit/vite-plugin-dts-repro-working-dem7lmyw?file=dist%2Ftypes%2Fpackages%2Fexample-2%2Fsrc%2Ftype.d.ts)a little bit and it's importing '.../.../.../somewhere' instead of '@scope/example-1'

**Comment by efriandika** [comment]
> [@efriandika](https://github.com/efriandika) It seems to be because the alias has been converted, maybe you can try `aliasesExclude` option.

I can confirm that it's working after adding the config you suggested.
`... aliasesExclude : ["@scope/example-1", "etc"] ...`

However, in version 3.6.4, we don't need to set anything to make it work. The way that old version did seems to be better, in my opinion.

**Comment by qmhc** [comment]
@efriandika If you want to back to the previous behavior, you can set `pathsToAliases: false`.

**Comment by efriandika** [comment]
> [@efriandika](https://github.com/efriandika) If you want to back to the previous behavior, you can set `pathsToAliases: false`.

Perfect, many thanks @qmhc

**Comment by lachieh** [comment]
Nice! Yeah, I was just about to suggest that, @efriandika. Might be worth opening an issue on the appropriate nx repo.
