### ISSUE TITLE
【功能请求】希望可以增加一个像rollup一样可以自定义输出目录层级的功能

### ISSUE THREAD

**Issue by libondev** [qmhc/vite-plugin-dts#331]
我正在实现一个样式组件库, 我的vite版本是 5.2.11, vite-plugin-dts 的版本是 3.9.1, 我所有的源代码都在 src下面按照文件夹分类了, 打包的时候在dist下面也是保持的这个结构, 
![image](https://github.com/qmhc/vite-plugin-dts/assets/47918504/bd72ad43-4e5e-493c-a3a4-16365ab1863f)
然而我在使用插件以后, 生成到 dist 的目录层级是: 
![image](https://github.com/qmhc/vite-plugin-dts/assets/47918504/10072bf4-e5bb-4b7e-a9fe-704412db899d)
外面多了一层 src, 导致组件文件和样式文件最终没有生成在一起, 所以有了这个issue, 我希望可以像 rollup 一样自定义生成的文件格式的层级, 是我的使用方式
![image](https://github.com/qmhc/vite-plugin-dts/assets/47918504/6cd5a499-bb25-46fe-bd19-76a59b4d2423)，我的项目地址是： https://github.com/libondev/pxd，可以在这个项目里运行 build 看到结果

**Comment by qmhc** [comment]
尝试指定 entryRoot 到 src 目录

**Comment by libondev** [comment]
可以了，非常感谢
