### ISSUE TITLE
Keep comments of the variable in d.ts

### ISSUE THREAD

**Issue by s3xysteak** [qmhc/vite-plugin-dts#334]
### Description

Could we keep comments of the variable in d.ts, like `unjs/unbuild` ?
However I haven't looked at the `unjs/untyped` implementation, so I don't know if this is possible.

### Suggested solution

No idea.

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
Comments will be keeped in declaration files. You need to provide a reproduction to show how the comments disappeared.

**Comment by Shinigami92** [comment]
I assume it is related to #132, but that is not a valuable workaround.

We export types e.g. like this:

```vue
<script lang="ts">
export interface MyCompProps {
  /** JSDoc comment */
  myprop1: string
}
</script>

<script setup lang="ts">
defineProps<MyCompProps>()
</script>
```

That way other devs can also import these TS types and reuse them for their needs

**Comment by qiaozhu** [comment]
当我像这样声明props
未经编译时，导入MyCompoment.vue，在vue文件template里，鼠标移动到props上，能够显示注释信息。
经过编译后，开发者在vue文件template里，鼠标移动到props上只能显示其类型，而不显示注释信息。

props.ts
```
export const myProps = {
   /**
     * @description 我的props
     */
    myprop: {
      required: false,
      type: String
    }
}
```

MyCompoment.vue
```
<script lang="ts" setup>
import { myProps } from './myProps';

defineOptions({
  name: 'MyCompoment'
});

const props = defineProps(myProps);
</script>
```

**Comment by qmhc** [comment]
Duplicate to #373 (more details), so I close this issue.
