### ISSUE TITLE
All typescript errors are being swallowed 

### ISSUE THREAD

**Issue by Exelord** [qmhc/vite-plugin-dts#342]
### Describe the bug

Hi, I have noticed tsc errors don't stop the build process. I would expect any tsc error would stop further declarations build and exit early vite process, instead it is swallowing the errors and finishing build successfully. Is this intended?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-7a57iw?file=vite.config.ts

### Steps to reproduce

`pnpm i && pnpm build`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vite: ^5.2.13 => 5.3.1 
    vite-plugin-dts: 3.9.1 => 3.9.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You can try to use the `afterDiagnostic` option of plugin.
