### ISSUE TITLE
DTS not compatible with latest React Vite tsconfig structure

### ISSUE THREAD

**Issue by mochizin** [qmhc/vite-plugin-dts#344]
### Describe the bug

I'm trying to use DTS with Vite for React 5.3.1
In this version Vite introduced tsconfig.app.json and reference it in tsconfig.json:
```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```
For some reason, the tsconfig.app.json is not being recognized by DTS. I get the following error:

![image](https://github.com/qmhc/vite-plugin-dts/assets/91489357/2bb7eff5-4eee-48e7-b838-d46fae26eeac)
or
`Module './App.tsx' was resolved to 'libray-ui/src/App.tsx', but '--jsx' is not set.`
![image](https://github.com/qmhc/vite-plugin-dts/assets/91489357/11b50beb-3bd0-453c-9c66-7351e92486e4)

~~The solution that I'm using is add `tsconfigPath: "./tsconfig.app.json",`  Is this a good solution?~~ Edit: This solution doesn't work properly 
```
plugins: [
    react(),
    dts({
      tsconfigPath: "./tsconfig.app.json"
    }),
  ],
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-yxnnz2?file=vite.config.ts

### Steps to reproduce

- Run:
`npm create vite@latest`
`npm install @types/node`
`npm install --save-dev vite-plugin-dts`

- vite.config.ts
```
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { resolve } from "path";
import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [
    react(),
    dts(),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, "src/main.ts"),
      name: "trigger-ui",
      formats: ["es"],
      fileName: "trigger-ui",
    },
    rollupOptions: {
      external: ["react", "react/jsx-runtime"],
    },
  },
});
```
- main.tsx file
```
export const Card = ({ children, ...props }: CardTypes) => {
  return <button {...props}>{children}</button>;
};

type CardTypes = {
  children: string;
} & React.ComponentPropsWithoutRef<"button">;
```

- Run 
`npm run build`

### System Info

```shell
System:
    OS: Windows 11
  Binaries:
    Node: 20.11.1
    npm: 10.2.4
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.1
    vite: ^5.3.1 => 5.3.1
    vite-plugin-dts: ^3.9.1 => 3.9.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sacru2red** [comment]
wrong
```
plugins: [
    react(),
    dts({
      tsconfigPath: "./tsconfig.app.json"
    }),
  ],
```

works
```
plugins: [
    react(),
    dts({
      tsconfigPath: "./tsconfig.json"
    }),
  ],
```

**Comment by yestay90** [comment]
@mochizin , hello. Is there any updates on this subject? Should we recreate react and vite app with older version?

**Comment by yestay90** [comment]
@mochizin , I removed tsconfig.app.json and moved all its content to tsconfig.json. And it started to work properly. I could import UI component to my other project.

**Comment by mochizin** [comment]
> @mochizin , I removed tsconfig.app.json and moved all its content to tsconfig.json. And it started to work properly. I could import UI component to my other project.

Yeah, this was my solution as well, but it is how Vite do in previous versions. I was looking for some solution/fix that works with latest Vite

**Comment by willian** [comment]
@yestay90, @mochizin, I think this fix must come from this plugin in a future update. Until it happens, this is what I did to fix it on my side:
```ts
    dts({
      tsconfigPath: resolve(__dirname, "tsconfig.app.json"),
      rollupTypes: true,
    }),

```
So, I didn't need to change the "Vite way" of organizing the tsconfig files.

**Comment by mochizin** [comment]
@willian, I tried to do that previously as well but when I run `npm run build` that contains `tsc -b`, it generates a vite.config.js file in my root folder.
So this solution doesn't work for me 😕

**Comment by phuongthuan** [comment]
@mochizin I got exactly the same your issue
Here is the [fix](https://github.com/phuongthuan/bee-ui/blob/main/vite.config.ts#L29)

**Comment by fahrikurniawan99** [comment]
@phuongthuan wow amazing how this works, why does it happen?

**Comment by mochizin** [comment]
@phuongthuan can't see the file, can you post the code here?

**Comment by lizy0329-biubiubiu** [comment]
> @mochizin I got exactly the same your issue <img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/91489357?s=80&amp;u=c4e7abf7b87d146c9864b9af25f80f6e92e6fe01&amp;v=4"> @mochizin我得到了与你完全相同的问题 Here is the [fix](https://github.com/phuongthuan/bee-ui/blob/main/vite.config.ts?rgh-link-date=2024-07-16T16%3A30%3A26Z#L29)这是[修复方法](https://github.com/phuongthuan/bee-ui/blob/main/vite.config.ts?rgh-link-date=2024-07-16T16%3A30%3A26Z#L29)
> 
> ```
>   plugins: [
>     react(),
>     dts({
>       rollupTypes: true,
>       tsconfigPath: "./tsconfig.app.json",
>     }),
>   ],
> ```

It work! @qmhc

**Comment by albertdugba** [comment]
This also ended up working for me

**Comment by elkofy** [comment]
Me too after 4 days of searching

**Comment by qmhc** [comment]
It has been updated in FAQs.

**Comment by LuciKritZ** [comment]
> @yestay90, @mochizin, I think this fix must come from this plugin in a future update. Until it happens, this is what I did to fix it on my side:
> 
> ```ts
>     dts({
>       tsconfigPath: resolve(__dirname, "tsconfig.app.json"),
>       rollupTypes: true,
>     }),
> ```
> 
> So, I didn't need to change the "Vite way" of organizing the tsconfig files.

Thanks for the fix, appreciate it! @willian @phuongthuan

**Comment by luizfm** [comment]
Any updated on this? Some of these suggested config didn't work for me... 

```
error during build:
[vite:dts] Internal Error: getResolvedModule() could not resolve module name "./stories/button/button.component"
/Users/luizfernandodemorais/Desktop/projetos/personal-projects/prolog-component-js/dist/index.d.ts:1:1
```

I'm using the same build command as mentioned by @mochizin `"build": "tsc -b && vite build"`
