### ISSUE TITLE
`"type": "module"` with `rollupTypes: true` results in error

### ISSUE THREAD

**Issue by christopherjbaker** [qmhc/vite-plugin-dts#345]
### Describe the bug

If my package.json has `"type": "module"` and my dts plugin config has `rollupTypes: true`, I get the error `Internal Error: getResolvedModule() could not resolve module name "./src/main"`.

I believe this is because module packages must use file extensions. If I comment out [the line that removes `.d.ts`](https://github.com/qmhc/vite-plugin-dts/blob/main/src/plugin.ts#L632) from the generated imports, it builds as expected.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-hq4tq1

### Steps to reproduce

`npm run build`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vite: ^5.3.1 => 5.3.1 
    vite-plugin-dts: ^3.9.1 => 3.9.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by elVengador** [comment]
Any idea to solve it?
