### ISSUE TITLE
大神，我生成的类型文件是源文件的结构，这种模式下导入组件的时候 package.json 中 types 该如何指定

### ISSUE THREAD

**Issue by itwmike** [qmhc/vite-plugin-dts#348]
### Description

![image](https://github.com/qmhc/vite-plugin-dts/assets/6613191/1f727059-6f70-46e9-ab4f-ec273ef4c81c)
生成了源文件结构，打包发布的时候 package.json 这样写：
![image](https://github.com/qmhc/vite-plugin-dts/assets/6613191/4344301f-caae-4a90-9cef-219d567167bf)
别的项目导入这个包的时候，并没有ts提示

### Suggested solution

无

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
指定入口文件（通常是 index）即可
