### ISSUE TITLE
Issue while installing the plugin

### ISSUE THREAD

**Issue by bademiya5306** [qmhc/vite-plugin-dts#350]
### Describe the bug

Gettting the below error while installing the plugin in vite react-ts project 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: prettier-plugin-organize-imports@4.0.0
npm ERR! Found: vue-tsc@2.0.19
npm ERR! node_modules/vue-tsc
npm ERR!   vue-tsc@"2.0.19" from vite-plugin-dts@4.0.0-beta.0
npm ERR!   node_modules/vite-plugin-dts
npm ERR!     dev vite-plugin-dts@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional vue-tsc@"^2.0.24" from prettier-plugin-organize-imports@4.0.0
npm ERR! node_modules/prettier-plugin-organize-imports
npm ERR!   peerOptional prettier-plugin-organize-imports@"*" from prettier-plugin-tailwindcss@0.6.5
npm ERR!   node_modules/prettier-plugin-tailwindcss
npm ERR!     dev prettier-plugin-tailwindcss@"^0.6.5" from the root project
npm ERR!   dev prettier-plugin-organize-imports@"^4.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue-tsc@2.0.26
npm ERR! node_modules/vue-tsc
npm ERR!   peerOptional vue-tsc@"^2.0.24" from prettier-plugin-organize-imports@4.0.0
npm ERR!   node_modules/prettier-plugin-organize-imports
npm ERR!     peerOptional prettier-plugin-organize-imports@"*" from prettier-plugin-tailwindcss@0.6.5
npm ERR!     node_modules/prettier-plugin-tailwindcss
npm ERR!       dev prettier-plugin-tailwindcss@"^0.6.5" from the root project
npm ERR!     dev prettier-plugin-organize-imports@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:

### Reproduction

https://stackblitz.com/edit/vitejs-vite-fdpkbb?file=package.json&terminal=dev

### Steps to reproduce

Try to run 
npm i vite-plugin-dts@3.9.1 -D 

### System Info

```shell
Mac os
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Maybe you can try to re-create the `package-lock.json` file.

**Comment by bademiya5306** [comment]
@qmhc No I have shared a reproducible link as well and steps to reproduce the issue

**Comment by qmhc** [comment]
I deleted the `package-lock.json` and re-install, it works.

**Comment by bademiya5306** [comment]
i tried to do the same in my codebase as well as the stackblitz link i have shared.. it did not work for me. Not sure why.

**Comment by qmhc** [comment]
It seems to be a problem when combine with `prettier-plugin-organize-imports`, I found the following content in its package.json:

<img width="275" alt="image" src="https://github.com/user-attachments/assets/d206c7af-7a8c-4113-9cce-3ac94851aca8">

**Comment by qmhc** [comment]
You can create a `.npmrc` with content `legacy-peer-deps=true` to ignore auto install peer dependencies.

**Comment by bademiya5306** [comment]
Thanks i will check this one.
