### ISSUE TITLE
namespace declaration exports two times

### ISSUE THREAD

**Issue by momokunsu** [qmhc/vite-plugin-dts#352]
### Describe the bug

source code:
```ts
export namespace Space {
    export let test = "test";
}
```

exports .d.ts file:
```ts
export declare namespace Space {
    let test: string;
}

export { }

export declare namespace Space {
    let test: string;
}
```

namespace Space has 2 declaration.

this bug also replicate in Reproduction url

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-7ejfqm?file=index.ts

### System Info

```shell
nodejs
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
It seems a bug form `api-extractor`, see https://github.com/microsoft/rushstack/issues/4807.

**Comment by momokunsu** [comment]
> It seems a bug form `api-extractor`, see https://github.com/microsoft/rushstack/issues/4807.

It seems that 2 problems, his project makes two packages, and everyone exports one time from the same package names 'package-a'.But my repo just has a single file. Moreover, his result is correct even if that isn't expected. My result has syntax errors of typescript because of redefine namespace members.

**Comment by momokunsu** [comment]
I changed this plugin version to 3.7.3, and it works. I hope to help you find the real bug.
