### ISSUE TITLE
Can the index file under the file be searched by default And How to handle getResolvedModule errors

### ISSUE THREAD

**Issue by nqsjd178559344** [qmhc/vite-plugin-dts#353]
### Description

![image](https://github.com/user-attachments/assets/b4ee49de-30b5-4996-9a57-ac8adb9b3cb6)
As shown in the figure, there are three files under APIs: index file, mining file, and query file. The index file exports the remaining two files by default. When I build, DTS cannot find the index file by default, so it will report an error 'getResolvedModule() could not resolve module name "./apis"'
![image](https://github.com/user-attachments/assets/7611bb7c-d298-4815-8b5b-51b3351b4f97)
If I change the import method, build will be successful

### Suggested solution

Default search for index files under the current file

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.

**Comment by qmhc** [comment]
Please provide a reproduction and the context in this case.
