### ISSUE TITLE
Volar generated type been added

### ISSUE THREAD

**Issue by RayGuo-ergou** [qmhc/vite-plugin-dts#354]
### Describe the bug

Volar generated types like `__VLS_Element ` will be declared in built files.

This happens on version `^4.0.0` I am guessing it's caused by upgrading `vue-tsc`?

This will cause type conflict when import the library.

### Reproduction

https://github.com/RayGuo-ergou/dts-reproduction

### Steps to reproduce

1. Clone the repo
2. Open this [file](https://github.com/RayGuo-ergou/dts-reproduction/blob/main/dist/components/button/Button.vue.d.ts#L4) or run build

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 42.63 GB / 46.66 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.15.0 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.6.0 - /usr/local/bin/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  npmPackages:
    @vitejs/plugin-vue: ^5.0.5 => 5.0.5
    vite: ^5.3.4 => 5.3.4
    vite-plugin-dts: 4.0.0-beta.1 => 4.0.0-beta.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Could you provide what type conflict will be caused?

**Comment by RayGuo-ergou** [comment]
When importing a library that includes types same as those generated by Volar (e.g., __VLS_Element), the following error occurs:

> Definitions of the following identifiers conflict with those in another file:
__VLS_IntrinsicElements, __VLS_Element, __VLS_GlobalComponents, __VLS_IsAny, 
__VLS_PickNotAny, __VLS_intrinsicElements, __VLS_SelfComponent, __VLS_WithComponent, 
__VLS_FunctionalComponentProps, __VLS_UnionToIntersection, __VLS_OverloadUnionInner, 
__VLS_OverloadUnion, __VLS_ConstructorOverloads, __VLS_NormalizeEmits, __VLS_PrettifyGlobal [6200]

This conflict because these types are auto-generated by the Volar language server. When a library declares same types, it results in naming conflicts.

**Comment by DerYeger** [comment]
This issue is still present with 4.0.0-beta.2 and the above reproduction.

While certainly not minimal, I also have an end-to-end reproduction of the issue. See https://github.com/DerYeger/yeger/actions/runs/10174119328/job/28139332486#step:4:1227.
