### ISSUE TITLE
Error: File not found:  commonjsHelpers.js

### ISSUE THREAD

**Issue by skimmilk6877** [qmhc/vite-plugin-dts#36]
at DirectoryCoordinator.addSourceFileAtPath (./node_modules/ts-morph/dist/ts-morph.js:18117:19)
    at Project.addSourceFileAtPath (./node_modules/ts-morph/dist/ts-morph.js:19567:51)
    at Object.transform (./node_modules/vite-plugin-dts/dist/index.js:138846:17)
    at ./node_modules/rollup/dist/shared/rollup.js:22620:25

**Comment by luozhihua** [comment]
`commonjsHelpers.js` 是 Vite 中生成的一个虚拟文件名，本身就不存在，看有没有办法直接判断一下这个文件名，将它忽略掉

**Comment by skimmilk6877** [comment]
@luozhihua 没有继续深挖这个问题，目前用 tsup 和 tsc 进行 type 的打包。由于 type 实际只存在于运行态，目前我计划后续研究下 esbuild 在这方面的问题。依赖 rollup 进行对 ts 的类型打包有一些问题，尤其因为我还用了 pnpm，尤其麻烦。只好先作罢了。

**Comment by CaiWenlie** [comment]
> `commonjsHelpers.js` 是 Vite 中生成的一个虚拟文件名，本身就不存在，看有没有办法直接判断一下这个文件名，将它忽略掉

额，打包之后还是有这个文件是咋回事
![image](https://user-images.githubusercontent.com/8305535/154392449-58830ca3-48b1-4cca-9a49-f587e75b12ff.png)

**Comment by LLwyct** [comment]
请问问题解决了吗，我打包也有一个 _commonjsHelpers-DaMA6jEr.js 不知道是干嘛的
