### ISSUE TITLE
Bogus typescript errors related to default imports during since 4.x

### ISSUE THREAD

**Issue by silverwind** [qmhc/vite-plugin-dts#363]
### Describe the bug

Since 4.x, I observe that this plugin prints typescript errors during `npx vite build`, related to default imports. `npx tsc` does not show these errors, so I think they are bogus and a bug in this plugin.

### Reproduction

https://github.com/silverwind/dts-4-react-issue

### Steps to reproduce

Clone and run `npm i && npx vite build`, observe these bogus errors:

```
index.tsx:2:33 - error TS2604: JSX element type 'Select' does not have any construct or call signatures.

2 export const Component = () => <Select/>;
                                  ~~~~~~
index.tsx:2:33 - error TS2786: 'Select' cannot be used as a JSX component.
  Its type 'typeof import("node_modules/react-select/dist/react-select.cjs")' is not a valid JSX element type.

2 export const Component = () => <Select/>;
```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (16) arm64 Apple M3 Max
    Memory: 2.10 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.6.0 - ~/.npm-global/bin/pnpm
    bun: 1.1.21 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 127.0.6533.89
    Firefox Nightly: 129.0a1
    Safari: 17.5
  npmPackages:
    vite: 5.4.0 => 5.4.0
    vite-plugin-dts: 4.0.1 => 4.0.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by silverwind** [comment]
Another way to reproduce is to perform this import in a `vite.config.ts`:

```
import type {UserConfig} from "vite";
```

It shows error `TS2305: Module '"vite"' has no exported member 'UserConfig'` which is bogus and works just fine in `tsc`.

**Comment by dumptyd** [comment]
I was getting similar errors. In my case, explicitly specifying `tsConfigPath` did the trick.

<img width="542" alt="image" src="https://github.com/user-attachments/assets/14708b96-9263-495b-901b-fe8f7a40f233">

**Comment by silverwind** [comment]
No change for me when I try this in the reproduction repo:

```ts
tsconfigPath: fileURLToPath(new URL("tsconfig.json", import.meta.url)),
```

**Comment by qmhc** [comment]
You should also add `@types/react` as a dev dependency.

**Comment by silverwind** [comment]
Yeah indeed. I forgot :)
