### ISSUE TITLE
Type error: File 'index.d.ts' is not a module since 4.0

### ISSUE THREAD

**Issue by Germandrummer92** [qmhc/vite-plugin-dts#365]
### Describe the bug

Since version 4 a file without exports does NOT get a "valid" d.ts file anymore. Worked on version 3.9.1.

We have a rather unusual use case where we WANT side-effects to happen on import, so the library in question can be injected into an iframe context. Since vite-d-ts the d.t.s file produced for the library is not a valid module anymore and typescript on import throws a

```Type error: File 'index.d.cts' is not a module.```. 

Workaround for us currently is in vite.config.ts

```ts
dts({
        insertTypesEntry: true,
        beforeWriteFile: (filePath, content) => {
          let safeContent = content;
          if (filePath.endsWith("dist/index.d.ts")) {
            if (!safeContent) {
              safeContent = "export {};";
            }

            const ctsFile = filePath.replace("d.ts", "d.cts");
            fs.writeFileSync(ctsFile, safeContent);
          }

          return {
            filePath,
            content: safeContent,
          };
        },
      }),
```

Root cause seems to be this change: https://github.com/qmhc/vite-plugin-dts/commit/e080ce5410468ff6659b5a06a390a6f818216a38 .

Maybe the use case is a bit weird, but wanted to report it anyways.

### Reproduction

https://github.com/Germandrummer92/reproduce-vite-dts

### Steps to reproduce

`corepack up`
`pnpm i`
`pnpm build`

expected behavior:

a valid `index.d.ts` is created.

actual behavior: resulting index.d.ts is empty.

You can see it works if you downgrade vite-d-ts to 3.9.1.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 61.84 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.5
  npmPackages:
    vite: ^5.4.0 => 5.4.0 
    vite-plugin-dts: ^4.0.1 => 4.0.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by suraj1294** [comment]
same issue.
