### ISSUE TITLE
The new version (4.0.2) is unable to follow symbol for "Record"

### ISSUE THREAD

**Issue by luckasnix** [qmhc/vite-plugin-dts#367]
### Describe the bug

When I updated the version from "3.9.1" to "4.0.2" I got the following error:

![vite-plugin-dts-error](https://github.com/user-attachments/assets/3a7a3eb5-ee08-4340-bdad-45dd8948dde4)

The project I left as an example may not be the smallest possible, but it is quite small.

### Reproduction

https://github.com/luckasnix/structured-objects/tree/main

### Steps to reproduce

- Run `npm i`
- Run `npm i vite-plugin-dts@4.0.2 --save-exact --save-dev`
- Run `npm run build`

### System Info

```shell
- OS: Microsoft Windows 10 Home
- Node: 22.5.1
- npm: 10.8.2
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SegaraRai** [comment]
I think this will be fixed by #366.
A workaround until this is merged and released is to use `4.0.0-beta.2`, the version that does not contain #360.
