### ISSUE TITLE
The type definition file generated in version 4.0.3 has errors in its content

### ISSUE THREAD

**Issue by 0x1f57** [qmhc/vite-plugin-dts#372]
### Describe the bug

![image](https://github.com/user-attachments/assets/563c8fb3-0919-4d7b-81eb-d8253d69e99a)

This is the same issue as #325 , but appears in version 4.0.3
Generated type definition file has errors when cleanVueFileName is set to true

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tpr4pc?file=packages%2Fdist%2Fpackage.json

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 2.62 GB / 15.94 GB
  Binaries:
    Node: 18.20.3 - ~\AppData\Local\fnm_multishells\16716_1724156337968\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\fnm_multishells\16716_1724156337968\yarn.CMD
    npm: 10.7.0 - ~\AppData\Local\fnm_multishells\16716_1724156337968\npm.CMD
    pnpm: 9.7.1 - ~\AppData\Local\fnm_multishells\16716_1724156337968\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Please provide a reproduction.

**Comment by 0x1f57** [comment]
> Please provide a reproduction.

The link has been updated. Please install the dependencies and run `npm run build`. After the build is successful, check packages/dist/es/src/checkButton/index.d.ts

**Comment by qmhc** [comment]
Don't use `cleanVueFileName` in your case then it works. After you used `cleanVueFileName` there are some duplicate files make errors (`index.vue.d.ts` -> `index.d.ts`).

**Comment by 0x1f57** [comment]
> Don't use `cleanVueFileName` in your case then it works. After you used `cleanVueFileName` there are some duplicate files make errors (`index.vue.d.ts` -> `index.d.ts`).

Yes, I realize that this problem will occur when index.vue and index.ts will generate index.d.ts after cleanVueFileName is set to true. But in actual projects, it is possible to have ts files and vue files with the same name in the same folder, so can we consider that in this case, even if cleanVueFileName is set to true, the correct type definition file can be generated?
