### ISSUE TITLE
Wrong type resolve order

### ISSUE THREAD

**Issue by cangSDARM** [qmhc/vite-plugin-dts#374]
### Describe the bug

If multiple entrypoints are set, the generated `.d.ts` will try to start resolve with the "js file" in the same folder (which is wrong). The correct way should be the corresponding folder name

ps This is the default rule for ts, but make no sense for the "to .d.ts" scenes

![image](https://github.com/user-attachments/assets/41936d85-2a40-4025-8bbc-acf1f20450a5)

consider add a "check folder or file" logic

### Reproduction

https://stackblitz.com/edit/vitejs-vite-keh9pu?file=src%2Findex.tsx,vite.config.ts

### Steps to reproduce

npm run build

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    vite: ^4.1.4 => 4.1.4 
    vite-plugin-dts: ^4.0.3 => 4.0.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Can't reproduce in the latest version.
