### ISSUE TITLE
Missing "service" property in Resolver interface

### ISSUE THREAD

**Issue by matteoscaramuzza** [qmhc/vite-plugin-dts#375]
### Describe the bug

This is the interface I get locally, when I download package from npm

```
interface Resolver {
    /**
     * The name of the resolver
     *
     * The later resolver with the same name will overwrite the earlier
     */
    name: string;
    /**
     * Determine whether the resolver supports the file
     */
    supports: (id: string) => void | boolean;
    /**
     * Transform source to declaration files
     *
     * Note that the path of the returns should base on `outDir`, or relative path to `root`
     */
    transform: (payload: {
        id: string;
        code: string;
        root: string;
        outDir: string;
        host: ts.CompilerHost;
        program: ts.Program;
    }) => MaybePromise<{
        path: string;
        content: string;
    }[]>;
}
```

and this is what I expect.

```
export interface Resolver {
  /**
   * The name of the resolver
   *
   * The later resolver with the same name will overwrite the earlier
   */
  name: string,
  /**
   * Determine whether the resolver supports the file
   */
  supports: (id: string) => void | boolean,
  /**
   * Transform source to declaration files
   *
   * Note that the path of the returns should base on `outDir`, or relative path to `root`
   */
  transform: (payload: {
    id: string,
    code: string,
    root: string,
    outDir: string,
    host: ts.CompilerHost,
    program: ts.Program,
    service: ts.LanguageService
  }) => MaybePromise<{ path: string, content: string }[]>
}
```

and it causes me this error:

`Cannot read properties of undefined (reading 'getEmitOutput')`

when i launch the build because I'm using a transformer

### Steps to reproduce

Launch `npm i`

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 107.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 7.13.5 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.122
    Safari: 17.6
  npmPackages:
    @vitejs/plugin-vue: ^5.1.2 => 5.1.2 
    vite: ^5.4.2 => 5.4.2 
    vite-plugin-dts: ^4.0.3 => 4.0.3
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by matteoscaramuzza** [comment]
The version v3.9.1 is the last one that still works

**Comment by qmhc** [comment]
This is a breaking change from v3 to v4. You need to create language service by yourself in v4.

**Comment by qmhc** [comment]
If you want to get emitted content, you can refer to the bottom part of `transform` method in `src/plugin.ts`.

**Comment by matteoscaramuzza** [comment]
Ok, thank you! I haven't seen anywhere in the repo about this breaking change, so I thought it was a bug. Sorry.

**Comment by matteoscaramuzza** [comment]
> ```ts
> let content = ''
> program.emit(sourceFile, (name, text) => {
>   content = text
> })
> ```

Perfect! I've implemented your solution and it works. 
I only suggest you to update the README because there still is the "service" property reference.

I close the issue. Thanks
