### ISSUE TITLE
when set rollupTypes: true, the import is redundant

### ISSUE THREAD

**Issue by dgf957492430** [qmhc/vite-plugin-dts#378]
### Describe the bug

![image](https://github.com/user-attachments/assets/a3f6d41c-644d-4562-a9e7-cb6dddfa5f09)
these import maybe come from different files, so how to merge them

### Reproduction

-

### System Info

```shell
"version": "4.0.3",
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
This is a behavior of `@microsoft/api-extractor`, also it's unnecessary to merge these imports and it will work normally.
