### ISSUE TITLE
Wrong package types: Can't be resolved by eslint-plugin-import

### ISSUE THREAD

**Issue by alixsep** [qmhc/vite-plugin-dts#379]
### Describe the bug

I'm encountering an issue when importing `dts` in my `vite.config.ts` file. Eslint throws the following error:

`error  No default export found in imported module "vite-plugin-dts"  import/default`

However, `vite-plugin-dts` DOES have a default export in `index.d.ts`:

`export { type PluginOptions, dtsPlugin as default, editSourceMapDir };`

As a temporary workaround, I've added the following to my Eslint config:

```
  ...
  settings: {
    "import/ignore": ["vite-plugin-dts"],
    ...
```

I also managed to reproduce the issue in stackblitz:
![image](https://github.com/user-attachments/assets/a8d6a8e0-1ddc-4c88-8597-812aceb9e872)

I'm looking forward to a fix for this issue. Thank you!

### Reproduction

https://stackblitz.com/edit/vitejs-vite-43sgdt?file=vite.config.ts&terminal=dev

### Steps to reproduce

After stackblitz loads, press CTRL + C in terminal and run `pnpm lint`.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 4.42 GB / 15.64 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-react-swc: ^3.7.0 => 3.7.0 
    vite: ^5.4.3 => 5.4.3 
    vite-plugin-dts: ^4.1.0 => 4.1.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
It also an error occurred from '@vitejs/plugin-react', so I think this is a issue about eslint import plugin.

Maybe you should not extend `plugin:import/recommended`, and use `plugin: ['import']` instead.

**Comment by alixsep** [comment]
Thanks! That fixed the issue even though I also had to add `plugin:import/typescript`. May I ask what was the underlying issue with using `plugin:import/recommended` and not `plugin: ['import']` ?
