### ISSUE TITLE
由于没有找到讨论的地方，想问下支持vue3的tsx文件吗？

### ISSUE THREAD

**Issue by JobinJIa** [qmhc/vite-plugin-dts#38]
因为我需要做二次封装，可能有些组件要用到tsx

**Comment by qmhc** [comment]
支持的，在 [example](https://github.com/qmhc/vite-plugin-dts/blob/main/example/components/TsxTest.tsx) 下有各种类组件的示例

**Comment by qmhc** [comment]
由于这是一个简单的询问，暂时先关闭该 issue。

**Comment by JobinJIa** [comment]
ok thx
