### ISSUE TITLE
(4.1.0) Not handle build from other directory

### ISSUE THREAD

**Issue by sarrooo** [qmhc/vite-plugin-dts#380]
### Description

I am using this plugin in a monorepo package :

```md
.
└── my-monorepo/
    ├── apps
    └── libs/
        └── ui-library/
            ├── src/
            ├── ...
            ├── project.json
            ├── vite.config.ts
            ├── vitest.config.ts
            └── tsconfig.ts
```

I am trying to run the Vite build command from the root of the monorepo using the command `pnpm run build:ui-library`, which is equivalent to `pnpm vite build -c libs/ui-library/vite.config.ts`.

### Bug

When using the `dts` plugin, I encounter errors stating that Vue modules cannot be found. For example:

```
libs/ui-library/src/components/index.ts:10:46 - error TS2307: Cannot find module '@/components/status/StatusMultiSelect/StatusMultiSelect.vue' or its corresponding type declarations.

10 export { default as StatusMultiSelect } from '@/components/status/StatusMultiSelect/StatusMultiSelect.vue'
```

### Investigation

After spending several hours analyzing the source code of the plugin, I identified that this issue was introduced in version [4.1.0](https://github.com/qmhc/vite-plugin-dts/releases/tag/v4.1.0) with this [commit](https://github.com/qmhc/vite-plugin-dts/commit/a04a191566e996defc071344f59cc76414fce61d). Specifically, the problem originates from [this line](https://github.com/qmhc/vite-plugin-dts/blob/a04a191566e996defc071344f59cc76414fce61d/src/program.ts#L19), where the plugin checks for the Vue dependency in the current working directory, rather than in the target package directory.

### Proposal

To properly support build execution from different directories, I suggest passing a `paths` argument to the `getPackageInfoSync` method. Here's an example:

```typescript
try {
  hasVue = !!(
    getPackageInfoSync('vue', { paths: [" -> ... <-"] }) ??
    getPackageInfoSync('svelte', { paths: [resolveModule('svelte') || process.cwd()] })
  );
} catch (e) {}
```

This adjustment should ensure that the plugin correctly resolves dependencies from the appropriate directory.

### Reproduction

https://stackblitz.com/~/github.com/sarrooo/vite-plugin-dts-bug

### Steps to reproduce

Run: `pnpm run build:ui-library` with `vite-plugin-dts` version `4.1.0` check `libs/ui-library/dist/index.es.d.ts`. Re-try with version `4.0.3`.

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.6.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 17.6
  npmPackages:
    @vitejs/plugin-vue: ^5.0.4 => 5.1.3 
    vite: ^5.0.13 => 5.2.9
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
A mistake when doing this feature.

**Comment by sarrooo** [comment]
@qmhc the bug is still present

**Comment by qmhc** [comment]
@qmhc Well, you should run `pnpm i -Dw vue`, because cwd is root dir, but no Vue dependency in there. Also you can change cwd to the under package root dir.
