### ISSUE TITLE
Pn'P + Library mode generates .vue.d.ts file with __VLS_ global types

### ISSUE THREAD

**Issue by auirarrazaval** [qmhc/vite-plugin-dts#385]
### Describe the bug

Hello there!
 I'm just guessing that this is [again](https://github.com/qmhc/vite-plugin-dts/issues/384) related to PnP, as I saw that there was [another ](https://github.com/qmhc/vite-plugin-dts/issues/354)issue that already solved this but the error persists for me. 
 
 Upon build, an extra `....vue.d.ts` file is created which declares global `__VLS_`-prefixed types. This generates a conflict when using the generated library in another project:
 
![image](https://github.com/user-attachments/assets/6494ef27-920c-4062-85fb-52cb0155fa65)

 I have provided a link that reproduces the error, which is the same as my last issue but with the versions updated. The generated file is different than the one in the screenshot above because i just reused my previous reproduction for simplicity

### Reproduction

https://github.com/auirarrazaval/vite-plugin-dts-build-error-repr

### Steps to reproduce

git clone ...
# In case not enabled, to use yarn4
corepack enable
yarn
yarn install
yarn sdks
yarn build

Here you can just look at the generated `dist/components/atoms/typography/TText/TText.vue.d.ts` and you'll see the generated types. If you were to import this as a library in another project, the error I put above rises

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
    Memory: 832.09 MB / 7.76 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.16.0 - /tmp/xfs-aff5ab46/node
    Yarn: 4.4.1 - /tmp/xfs-aff5ab46/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Well, it's a issue of Volar ...

**Comment by auirarrazaval** [comment]
Thought it would be something on those lines. Should I open an issue directly on volar? Or do you think you have more pull with the mainteners there to get something going

**Comment by qmhc** [comment]
I just add a patch for this, and waiting it's fixed in Volar.
