### ISSUE TITLE
DTS not working with typescript@5.6

### ISSUE THREAD

**Issue by lejunyang** [qmhc/vite-plugin-dts#389]
### Describe the bug

I am not able to use dts to rollup type files if upgrading typescript to 5.6

### Reproduction

https://github.com/lejunyang/lun

### Steps to reproduce

clone my project, change typescript's version to 5.6.3 in `pnpm-workspace.yaml`, then run
```
pnpm install
cd ./packages/utils
pnpm build
```
we'll see 
```
error during build:
[vite:dts] Internal Error: getResolvedModule() could not resolve module name "./src/browser"
```

Actually api-extractor has a known [issue](https://github.com/microsoft/rushstack/issues/4919#issuecomment-2412328792) with typescript@5.6, which has been fixed recently.
If I add "@microsoft/api-extractor": "7.47.10" in package.json resolutions and repeat above steps again, the error will be gone.
So please consider to upgrade it.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900HX
    Memory: 42.41 GB / 63.74 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74), ChromiumDev (127.0.2610.3)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-vue: catalog: => 5.1.4
    @vitejs/plugin-vue-jsx: catalog: => 4.0.1
    vite: catalog: => 5.4.6
    vite-plugin-dts: catalog: => 4.2.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lejunyang** [comment]
@qmhc could you please take a look

**Comment by francislavoie** [comment]
We're using `vite-plugin-dts@v4.3.0`, the build works but we get this warning:

```
Analysis will use the bundled TypeScript version 5.4.2
*** The target project appears to use TypeScript 5.6.3 which is newer than the bundled compiler engine; consider upgrading API Extractor.
```

Is there anything we can do about this, or are we stuck seeing this?

**Comment by lejunyang** [comment]
> Analysis will use the bundled TypeScript version 5.4.2
maybe you need to consider bump typescript's version

**Comment by francislavoie** [comment]
I think you misunderstand @lejunyang. My project uses TypeScript 5.6. The problem is `@microsoft/api-extractor` bundles an older TypeScript version, therefore complains if the one I use myself does not match. Which it very rarely would because I use a `^` version constraint in my `package.json`.

**Comment by lejunyang** [comment]
@francislavoie then you need to check if there are any other dependencies requiring `typescript` or `@microsoft/api-extractor`, maybe they required lower version and caused this discrepancy. Is you project a public repo? you can share it if it is

**Comment by francislavoie** [comment]
There are not.

```
$ yarn why @microsoft/api-extractor
yarn why v1.22.22
[1/4] Why do we have the module "@microsoft/api-extractor"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@microsoft/api-extractor@7.47.11"
info Reasons this module exists
   - "_project_#service#vite-plugin-dts" depends on it
   - Hoisted from "_project_#<snip>#vite-plugin-dts#@microsoft#api-extractor"
info Disk size without dependencies: "34MB"
info Disk size with unique dependencies: "76.77MB"
info Disk size with transitive dependencies: "34MB"
info Number of shared dependencies: 35
Done in 0.47s.
```

```
$ yarn why typescript
yarn why v1.22.22
[1/4] Why do we have the module "typescript"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "typescript@5.6.3"
info Has been hoisted to "typescript"
info Reasons this module exists
   - "workspace-aggregator-4d2ac0de-2a33-4356-8af5-6e05988eb20f" depends on it
   - Hoisted from "_project_#<snip>#typescript"
   - Hoisted from "_project_#<snip>#typescript"
   - Hoisted from "_project_#<snip>#typescript"
   - Hoisted from "_project_#<snip>#typescript"
   - Hoisted from "_project_#<snip>#typescript"
info Disk size without dependencies: "21.74MB"
info Disk size with unique dependencies: "21.74MB"
info Disk size with transitive dependencies: "21.74MB"
info Number of shared dependencies: 0
=> Found "@microsoft/api-extractor#typescript@5.4.2"
info This module exists because "_project_#<snip>#vite-plugin-dts#@microsoft#api-extractor" depends on it.
info Disk size without dependencies: "31.2MB"
info Disk size with unique dependencies: "31.2MB"
info Disk size with transitive dependencies: "31.2MB"
info Number of shared dependencies: 0
Done in 0.44s.
```

**Comment by lejunyang** [comment]
@francislavoie I got you now, `api-extrator` specifies `typescript@5.4.2` in its `package.json`. In my project, I add `typescript@5.6.3` in `resolutions` so I don't see that problem, you can try that as well

**Comment by francislavoie** [comment]
Overriding with `resolutions` might work in the short term, but in the long term it may break things depending on how `@microsoft/api-extractor` (or `vite-plugin-dts` through it) uses the dependency.
