### ISSUE TITLE
用脚本去手动打包，脚本文件存放项目中不同路径下生成的文件结果不一样

### ISSUE THREAD

**Issue by JobinJIa** [qmhc/vite-plugin-dts#40]
我在使用dts()生成.d.ts文件时发现。
如果我写的脚本文件放于根目录下，也就是project/下。则打包能生成如下的文件(注意红框中的生成文件)
![image](https://user-images.githubusercontent.com/9244703/140275508-2b12e4e3-debd-43f0-aab4-9a5eb9dbdd5c.png)

但是，如果把该脚本放于project/script下，则只会生成index.d.ts. 如下（与上图对比，少了两）
![image](https://user-images.githubusercontent.com/9244703/140275653-8efacb9f-6c4f-4ef0-a679-b48070c73bb5.png)

因为console也没有提示相关错误，所以不好排查。下面是这个demo的地址
[demo](https://github.com/JobinJIa/vue3-library)

我希望的是，两者生成的结果，应该都是第一次的结果。：(

**Comment by qmhc** [comment]
我调整了 `replaceFilePath` 方法内的正则表达式：

![image](https://user-images.githubusercontent.com/40221744/140284278-afcc4429-fb68-45e7-bb88-37b77804dfc3.png)

```js
const replaceFilePath = path => {
  return path.replace(/packages[\\/][a-zA-z]+([\\/])/, '$1')
}
```

分别在根目录下执行 `node build.js` 和 `node scripts/build.js`，在 `dist` 下得到了一样的结果：

![image](https://user-images.githubusercontent.com/40221744/140284607-562a3149-c69f-4f2b-9117-516430df2088.png)

**Comment by JobinJIa** [comment]
emm, 实在抱歉，因为我没有配置打包前删除原有的dist目录 。
所以需要手动删除dist之后，重新偿试打包，我这边还是没有达到预期的效果。
也许跟系统环境有关？(我的环境：macOS Big Sur 11.6.1 )

![image](https://user-images.githubusercontent.com/9244703/140289973-fd619cfc-adf5-49bb-ae93-20c7c0f1bda3.png)

**Comment by qmhc** [comment]
两次运行之间我均手动删除了 `dist` 文件夹的。

我借了一台 mac 笔记本进行了测试，两次打包结果是一样且正常的，无法复现你描述的情况：

<img width="779" alt="{4202DD66-1173-76C3-7359-D34FAE3B5A65}" src="https://user-images.githubusercontent.com/40221744/140297703-5903aaa8-b2f2-42ce-88ba-6b5fee0661d5.png">

**Comment by JobinJIa** [comment]
> 两次运行之间我均手动删除了 `dist` 文件夹的。
> 
> 我借了一台 mac 笔记本进行了测试，两次打包结果是一样且正常的，无法复现你描述的情况：
> 
> <img alt="{4202DD66-1173-76C3-7359-D34FAE3B5A65}" width="779" src="https://user-images.githubusercontent.com/40221744/140297703-5903aaa8-b2f2-42ce-88ba-6b5fee0661d5.png">
在vscode下可以，
因为我是用的webstorm ，就生成有问题...
...em 
这是vscode
![image](https://user-images.githubusercontent.com/9244703/140299407-755c0a6a-7b23-4080-ade1-5bd76dab9093.png)
这是webstorm
![image](https://user-images.githubusercontent.com/9244703/140299542-d6f7bcf6-5bdb-42de-92a4-708d535f9e59.png)

**Comment by JobinJIa** [comment]
补充，在windows下的webstorm中。执行build.js一样会只生成index.d.ts。其它的还是不见。
但是如果使用node script/build.js 是能正常的生成完全的.d.ts. 
所以， 暂时不确定到底是ws的node换环境的问题还是插件的兼容问题。
因为在ws中运行 script/build.js是执行的"C:\Program Files\nodejs\node.exe" E:\myself\vue3-library\build.js （windows下）

**Comment by JobinJIa** [comment]
最新，经调试发现，在webstorm中运行时，有路径对不上，所以没有生成
执行根目录下的build.js
![image](https://user-images.githubusercontent.com/9244703/140461795-d662bcf0-3d69-4e9c-ac45-2adf1e39092c.png)
执行非根目录下的build
![image](https://user-images.githubusercontent.com/9244703/140461825-02ebe687-90fd-435e-8758-027919858a6a.png)
向上寻找对应的地方创建project对象时
![image](https://user-images.githubusercontent.com/9244703/140461942-26be8f42-65e6-42cb-a87b-9ffc20adccfe.png)

对应vite-plugin-dts源码位置
![image](https://user-images.githubusercontent.com/9244703/140462027-656bea70-7639-4bc9-87a9-8fb320a74290.png)
![image](https://user-images.githubusercontent.com/9244703/140462101-aa4a64c3-16d0-486e-aa54-669c7b23cd3f.png)

**Comment by qmhc** [comment]
可能在 webstorm 执行 `scripts/build.js` 时 `cwd` 被设置为 `scripts` 目录了，你可以尝试一下使用 `root` 选项将根目录显式地设置为项目根目录。

**Comment by JobinJIa** [comment]
> 可能在 webstorm 执行 `scripts/build.js` 时 `cwd` 被设置为 `scripts` 目录了，你可以尝试一下使用 `root` 选项将根目录显式地设置为项目根目录。
> 
> PS：如果是 `cwd` 被设置为 `scripts` 目录，我也不确定会不会影响到 `typescript` 的输出路径（`ts-morpth` 内部依然是使用 `typescript` 的方法的）

我也是这样想的，上面调试的时候已经显示的设置了`root`的路径。因为之前没有显示设置的时候，获取组件路径就是错的。修证过后，才验证才出现上面的我说的情况。

这个问题，我先关闭了。不去深究了。因为打包时，究终会在`package.json`里设置命令，使用 node script/build.js 去执行。
这样的结果反而是对的。 : (
