### ISSUE TITLE
编译后别名的路径有误，如图

### ISSUE THREAD

**Issue by czb3279338858** [qmhc/vite-plugin-dts#41]
![image](https://user-images.githubusercontent.com/80880408/140730403-c761ddc0-0430-4911-aa41-7e5d58d08954.png)

**Comment by czb3279338858** [comment]
多了2层../

**Comment by qmhc** [comment]
需要你提供一个复现的仓库，光靠图片难以核实与定位问题。

**Comment by czb3279338858** [comment]
> 需要你提供一个复现的仓库，光靠图片难以核实与定位问题。

https://github.com/czb3279338858/vite-plugin-dts-issues.git

**Comment by czb3279338858** [comment]
> 需要你提供一个复现的仓库，光靠图片难以核实与定位问题。

补充个问题，再packages/map生成的类型中，缺少了一部分，src/request/original/amap/v3下的类型都丢失了。上个回复中提供的仓库可以复现这个bug

**Comment by qmhc** [comment]
![image](https://user-images.githubusercontent.com/40221744/141033151-f5c65a78-d58f-46c6-b253-2d5f679b6550.png)

map 打包时会出现一些类型错误导致打包中断；如果这是我操作不正确的原因，希望你可以提供一个从克隆了仓库之后的复现步骤。

插件在生成类型文件时，存在类型错误的文件将无法生成。

同时，对于 `monorepo` 的项目 `root` 的获取有时候可能会不符合预期导致计算相对路径时出现意料之外的情况。

我推荐的 `monorepo` 的实践是将顶部根目录作为 `root` 进行打包：

- 对于每个子包需要独立在自己目录下打包的，可将 `outDir` 设置为 `packages/{name}/dist`，打包出来会得到 `packages/{name}/dist/packages/...` 结构的系列文件，这个时候可以借助如 `@microsoft/api-extractor` 的工具单独对生成的类型文件打包；

- 对于顶层对全部子包一起打包成一个输出的，可以使用默认 `outDir` 或者设置到你想要的位置，对于每个子包打包路径的调整可以通过 `beforeWriteFile` 钩子函数实现（对于打包的文件结构与 `packages` 结构不一样时会有这个需求）。

**Comment by czb3279338858** [comment]
> ![image](https://user-images.githubusercontent.com/40221744/141033151-f5c65a78-d58f-46c6-b253-2d5f679b6550.png)
> 
> map 打包时会出现一些类型错误导致打包中断；如果这是我操作不正确的原因，希望你可以提供一个从克隆了仓库之后的复现步骤。
> 
> 插件在生成类型文件时，存在类型错误的文件将无法生成。
> 
> 同时，对于 `monorepo` 的项目 `root` 的获取有时候可能会不符合预期导致计算相对路径时出现意料之外的情况。
> 
> 我推荐的 `monorepo` 的实践是将顶部根目录作为 `root` 进行打包：
> 
> * 对于每个子包需要独立在自己目录下打包的，可将 `outDir` 设置为 `packages/{name}/dist`，打包出来会得到 `packages/{name}/dist/packages/...` 结构的系列文件，这个时候可以借助如 `@microsoft/api-extractor` 的工具单独对生成的类型文件打包；
> * 对于顶层对全部子包一起打包成一个输出的，可以使用默认 `outDir` 或者设置到你想要的位置，对于每个子包打包路径的调整可以通过 `beforeWriteFile` 钩子函数实现（对于打包的文件结构与 `packages` 结构不一样时会有这个需求）。

问题已经解决了，只要使用绝对路径替换相对路径就可以判断出正确的rootDir
![image](https://user-images.githubusercontent.com/80880408/141071907-d21364f5-3309-4bb7-b0a8-3f07b838e90e.png)

虽然不是用你的方法解决的，但依然非常感谢你提供了这个插件
