### ISSUE TITLE
生成.d.ts时部分文件丢失

### ISSUE THREAD

**Issue by JobinJia** [qmhc/vite-plugin-dts#42]
emm. 我又来了，如图
![image](https://user-images.githubusercontent.com/9244703/140904213-fdda0e62-cb9b-4e0a-9462-15253a16aaeb.png)
当前有这两个文件，且在对外暴露的index.ts文件中有引入
![image](https://user-images.githubusercontent.com/9244703/140904326-8375f118-46d7-496f-bd03-2a11ea82712f.png)
但构建之后 丢失
```
composables/useForm.ts
types/form.ts
```
这两个文件。结果如下
![image](https://user-images.githubusercontent.com/9244703/140904593-d0168b9b-0745-4274-a0b2-1529209b8ffb.png)

[demo](https://github.com/JobinJia/ant-design-vue-components)

**Comment by czb3279338858** [comment]
看到中文真亲切，我也遇到了相同的问题。

**Comment by qmhc** [comment]
`@jiabinbin/vue3-library` 不能被正常安装，这看起来并不是一个公开的 npm 包。

**Comment by JobinJia** [comment]
> `@jiabinbin/vue3-library` 不能被正常安装，这看起来并不是一个公开的 npm 包。

已删除这个依赖，本身上面的demo对这个并不影响。因为没有使用到

**Comment by qmhc** [comment]
这应该是出现了类型错误导致文件无法生成（除了少数错误不会导致文件 `emit` 中断）。

你可以通过添加 `skipDiagnostics: false` 来开启类型诊断，未添加上述选项时 `logDiagnostics: true` 将不会生效。

PS1：默认跳过类型诊断的初衷是因为有效率更高的 `vue-tsc` 来执行该步骤。

PS2：我使用 vscode 打开一些文件已经直接报出了许多类型错误（`vue-tsc` 和 `volar` 使用 vscode 同源的类型检查服务）

**Comment by JobinJia** [comment]
我去试试 我用webstorm 打开是没有任何类型错误的 我先用vue3 tsc查一遍看看

**Comment by JobinJia** [comment]
> 这应该是出现了类型错误导致文件无法生成（除了少数错误不会导致文件 `emit` 中断）。
> 
> 你可以通过添加 `skipDiagnostics: false` 来开启类型诊断，未添加上述选项时 `logDiagnostics: true` 将不会生效。
> 
> PS1：默认跳过类型诊断的初衷是因为有效率更高的 `vue-tsc` 来执行该步骤。
> 
> PS2：我使用 vscode 打开一些文件已经直接报出了许多类型错误（`vue-tsc` 和 `volar` 使用 vscode 同源的类型检查服务）

因为我认为vue-tsc --noEmit默认是加载的是tsconfig.json文件。所以我做了以下的操作
1. 将script/build.js中vite-plugin-dts插件切加载的配置文件由 tsconfig.build.json 换到tsconfig.json
2. 设置dts option中 `skipDiagnostics: false` 和 `logDiagnostics: true` (见script/build.js中133，134行)
2. 控制台执行vue-tsc --noEmit。结果如下
![image](https://user-images.githubusercontent.com/9244703/141048786-bc974735-b919-44a2-ab4a-3be19e361cb3.png)
3. 发现没有报类型错误，那么检测通过。再执行 `package.json -> script`中 `build:component`命令。打包报错
如下：(emm。 有很多)
![image](https://user-images.githubusercontent.com/9244703/141049352-6962a6a7-5df2-433d-97c6-acee1c1d8411.png)

**Comment by JobinJia** [comment]
更新：
之前vue-tsc 验证成功之后，执行build.js生成.d.ts文件时报的错有两种类型。

1. 报类型错误，这个是因为，vite-plugin-dts 不支持tsconfig.json中配置的typeRoots字段
```
"typeRoots": ["./node_modules/@types/", "packages/types"],
```
> 因为如果我不设置这个 改用 import type { Type1, Type2 } from 'pacakges/types/xx' 这么引入，是能正常编译出之前丢失的文件(vite:dts也不会报类型的错误)
结果如下
![image](https://user-images.githubusercontent.com/9244703/141067709-adb19a51-6dea-4da5-bbb0-5b4dd69ce517.png)
这里可以看到，已经生成之前丢失的 `form.d.ts` 及 `useForm.d.ts`

所以
全局定义在packages/types目录下的类型，在dts插件中不生效。所以vue-tsc 能检查通过。而生成.d.ts文件时报错。


2. 第二个是vue3编译setup script出现的问题，我不确定这个问题是dts插件的还是vue3运行时的或是其它的某个插件的。具体的情况如下图（有点怀疑是dts插件中对vue3的编译sfc的版本支持问题？）
![image](https://user-images.githubusercontent.com/9244703/141066955-c63e88f4-cc85-425d-b244-5a3599b71132.png)
我单独把这个.vue文件放到[Vue SFC Playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIj5cbiAgaW1wb3J0IHsgZGVmaW5lQ29tcG9uZW50IH0gZnJvbSAndnVlJ1xuXG4gIGV4cG9ydCBkZWZhdWx0IGRlZmluZUNvbXBvbmVudCh7XG4gICAgbmFtZTogJ1ZDQmFzaWNBcnJvdydcbiAgfSlcbjwvc2NyaXB0PlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuICBpbXBvcnQgeyBWQ0ljb24gYXMgSWNvbiB9IGZyb20gJ0AvY29tcG9uZW50cy9JY29uJ1xuICBpbXBvcnQgeyB1c2VEZXNpZ24gfSBmcm9tICdAL2NvbXBvc2FibGVzL3dlYi91c2VEZXNpZ24nXG4gIGltcG9ydCB7IGNvbXB1dGVkIH0gZnJvbSAndnVlJ1xuXG4gIGNvbnN0IHByb3BzID0gZGVmaW5lUHJvcHM8e1xuICAgIGV4cGFuZD86IGJvb2xlYW5cbiAgICB1cD86IGJvb2xlYW5cbiAgICBkb3duPzogYm9vbGVhblxuICAgIGluc2V0PzogYm9vbGVhblxuICB9PigpXG5cbiAgY29uc3QgeyBwcmVmaXhDbHMgfSA9IHVzZURlc2lnbignYmFzaWMtYXJyb3cnKVxuXG4gIC8vIGdldCBjb21wb25lbnQgY2xhc3NcbiAgY29uc3QgZ2V0Q2xhc3MgPSBjb21wdXRlZCgoKSA9PiB7XG4gICAgY29uc3QgeyBleHBhbmQsIHVwLCBkb3duLCBpbnNldCB9ID0gcHJvcHNcbiAgICByZXR1cm4gW1xuICAgICAgcHJlZml4Q2xzLFxuICAgICAge1xuICAgICAgICBbYHZjLS1hY3RpdmVgXTogZXhwYW5kLFxuICAgICAgICB1cCxcbiAgICAgICAgaW5zZXQsXG4gICAgICAgIGRvd25cbiAgICAgIH1cbiAgICBdXG4gIH0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8c3BhbiA6Y2xhc3M9XCJnZXRDbGFzc1wiPlxuICAgIDxJY29uIGljb249XCJpb246Y2hldnJvbi1mb3J3YXJkXCIgOnN0eWxlPVwiJGF0dHJzLmljb25TdHlsZVwiIC8+XG4gIDwvc3Bhbj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=) 编译出来的结果是跟我本地的一样的(见该地址js 69行)

**Comment by qmhc** [comment]
目前我定位到一个问题，项目中的 `.d.ts` 文件没有被添加到源文件中导致一些全局类型丢失，该问题已修复，将在随后提交。

至于 `...__default__` 这个类型错误，是很早就有的一个问题了，我认为这是 `vue/compiler-sfc` 的一个缺陷，在同时使用 `<script>` 和 `<script setup>` 时，如果你在 `<script>` 中使用了 `defineComponent` 返回，编译结果如你所见，会将 `defineComponent` 的返回值重新合并到其参数中，然而这两者的类型是不兼容的，导致类型诊断出错（因为插件是使用 `vue/compiler-sfc` 编译后的结果进行类型生成的）。

![image](https://user-images.githubusercontent.com/40221744/141070842-a2844133-f50d-4f15-8a85-8a157a462518.png)

![image](https://user-images.githubusercontent.com/40221744/141070868-e8e21ecb-f323-470d-b110-93c66dccf45d.png)

以前的一个版本，我在 `...__default...` 后添加 `as any` 解决这个问题，但是这会丢失 `<script>` 中的类型推导，在之后的版本移除了，现在我正在考虑一个新的解决办法。

当前可以规避这个问题的做法是，在 '<script>' 中不要使用  `defineComponent`，如这个[示例](https://github.com/qmhc/vite-plugin-dts/blob/main/example/components/BothScripts.vue)所示。

**Comment by JobinJia** [comment]
好的 非常感谢你的帮助 emm 有木有联系方式 加个好友 以后有机会多多向你请教
