### ISSUE TITLE
升级0.9.4之后，可以打包全局的 .d.ts文件，但是路径要怎么修改呢？

### ISSUE THREAD

**Issue by JobinJia** [qmhc/vite-plugin-dts#43]
![image](https://user-images.githubusercontent.com/9244703/141095141-0f73a25a-41cd-454b-a9bb-c0f298d36a69.png)

我想去掉一层= =

**Comment by qmhc** [comment]
你的意思是去掉整个 `packages` 文件夹的内容，还是想要将 `packages/**/*` 变成 `**/*`（`types` 往上走一层）？

**Comment by JobinJia** [comment]
> 你的意思是去掉整个 `packages` 文件夹的内容，还是想要将 `packages/**/*` 变成 `**/*`（`types` 往上走一层）？

不好意思，太忙了昨儿，忘了回复
是你说的第二种
想要将 `packages/**/*` 变成 `**/*`（types 往上走一层）？
因为我在beforWritFile钩子里面看了，全局类型的文件不在这个钩子中出来=。=（还有生产的类型入口文件也是）
比如，我替换了packages的路径。那么生成的类型入口文件 里的  `内容` 还会是export * from './packages/xxx/xxx' (然而实际上packages这一层在beforWirtFile中已被替换掉了= =)
