### ISSUE TITLE
setup script支持问题

### ISSUE THREAD

**Issue by JobinJia** [qmhc/vite-plugin-dts#44]
![image](https://user-images.githubusercontent.com/9244703/141444920-94834ae3-3396-42f2-86f9-598b55f60700.png)
如上图
因为 setup script 支持了 export interface Props {}
所以我准备在setup script中声明类型，再导出去，这样类型只用定义一次。但是发现使用dts生成.d.ts时报错

**Comment by qmhc** [comment]
我认为这是 `vue-compiler` 支持不全面，你可以尝试显式添加 `export`。

**Comment by JobinJia** [comment]
我在vuejs/next-vue的issues下查到相关的问题，说是可以显示的export出去，但是会提示ts相关的问题，但是能使。所以这个不属于该插件的问题
