### ISSUE TITLE
在`beforeWriteFile`改变生成路径后内部引用不正确

### ISSUE THREAD

**Issue by JobinJia** [qmhc/vite-plugin-dts#45]
当项目结构如下
![image](https://user-images.githubusercontent.com/9244703/141449074-1f910a18-d823-47bd-828b-4dd16eca7e2f.png)
生成的项目中 去掉packages 和src一层。生成的结果如下
![image](https://user-images.githubusercontent.com/9244703/141449154-66034f59-449b-4268-b998-de55c74a0c37.png)
而内部内容 实际没有发生变化
![image](https://user-images.githubusercontent.com/9244703/141449232-d003d90d-8ef2-4231-bdb4-7b6237c2a4fa.png)

Q： 这个是否也需要在`beforeWriteFile`中自己修改对应文件的content中的内容？

**Comment by qmhc** [comment]
是的，这是一个完全开放的钩子，插件不会感知用户做的改动。
