### ISSUE TITLE
打包提示[vite:dts] The argument 'path' must be a string or Uint8Array without null bytes. commonjsHelpers.js

### ISSUE THREAD

**Issue by hjklink** [qmhc/vite-plugin-dts#46]
![image](https://user-images.githubusercontent.com/47598373/144006535-2298e149-69b9-4e9e-98e5-ef9248f484ea.png)

**Comment by qmhc** [comment]
能否提供一个复现问题的仓库，或者提供发生该问题的项目的 `vite.config.ts` 以及 `tsconfig.json` 等配置文件。

**Comment by hjklink** [comment]
> 能否提供一个复现问题的仓库，或者提供发生该问题的项目的 `vite.config.ts` 以及 `tsconfig.json` 等配置文件。

https://gist.github.com/hjklink/91cf8bd2743ad42f53e92daeb57e09af

这个地址

**Comment by ihatake** [comment]
> tsconfig.json 配置 "allowJs": true, 错误。

设置为false后，没有生成声明文件了

**Comment by MaybeQHL** [comment]
> > tsconfig.json 配置 "allowJs": true, 错误。
> 
> 设置为false后，没有生成声明文件了

我也是
