### ISSUE TITLE
Plugin not honouring `sourcemap: false`

### ISSUE THREAD

**Issue by beefchimi** [qmhc/vite-plugin-dts#49]
It appears that the generated types files are still trying to create a source map link:

![Screen Shot 2022-01-04 at 1 46 32 PM](https://user-images.githubusercontent.com/643944/148108568-20cfd222-266c-4c36-b21a-d62bcd75c04c.png)

No `.map` files actually exist though, as I have chosen not to include source maps.

**Comment by qmhc** [comment]
Have you set `"sourceMap": false` in "compilerOptions" of `tsconfig.json` ?

**Comment by beefchimi** [comment]
Ah my bad - I was extending a config and did not realize it had `sourceMap: true` :cry:

Thanks - got it sorted out now. Your plugin is working excellently! I'm using it on a few projects - most recently here:
https://github.com/beefchimi/socialite
