### ISSUE TITLE
feat: work during --watch

### ISSUE THREAD

**Issue by tmm** [qmhc/vite-plugin-dts#5]
Not sure if this is possible with how `vite`'s `--watch` is set up, but would be great if this plugin worked during [`watch`](https://vitejs.dev/config/#build-watch) mode.

This would be helpful for building a library and testing it out (i.e. with `yarn link`) in a separate app at the same time. Right now, in watch mode the types are removed from the output after reloading.

**Comment by qmhc** [comment]
Thanks for your suggestion.

My original intention is for generating declaration in build mode, but not adequately considering the watch mode.

This idea broadens development of the plugin, I will take a try later.

**Comment by dipsaus9** [comment]
Could you use any help on this? Would really help my development!
