### ISSUE TITLE
生成类型文件排除第三方库的问题

### ISSUE THREAD

**Issue by JobinJia** [qmhc/vite-plugin-dts#51]
在设置exclude之后，好像并没有生效

![image](https://user-images.githubusercontent.com/9244703/148684632-a27594af-52f3-4c4d-8c04-0e877e8b6039.png)

[demo](https://github.com/JobinJIa/vc-view)

运行 `pnpm run build:vc-naive` 在控制台中可以看到错误日志

**Comment by qmhc** [comment]
这是 TypeScript 的一个[已知的问题](https://github.com/microsoft/TypeScript/issues/42873)，似乎是由于发生了 `node_modules` 多层嵌套的类型引用导致的，有一个临时解决方案是显式的在 `compilerOptions.path` 下添加相关包的路径。

对于你的 demo 的情况，可以在 `vc-native/tsconfig.json` 中添加 `naive-ui` 的 `paths` 选项：

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"],
      "naive-ui": ["node_modules/naive-ui/"]
    }
  },
  "include": [
    "components/**/*.ts",
    "components/**/*.d.ts",
    "components/**/*.tsx",
    "components/**/*.vue",
    "../interface/**/*.ts",
    "../interface/**/*.d.ts"
  ]
}
```

**Comment by JobinJia** [comment]
这样子，非常感谢！
