### ISSUE TITLE
`preserveModulesRoot` is invalid in windows

### ISSUE THREAD

**Issue by ckvv** [qmhc/vite-plugin-dts#54]
https://github.com/ckpack/v-ui

<img width="377" alt="截屏2022-01-11 下午7 31 07" src="https://user-images.githubusercontent.com/30174970/148935305-d9c4c961-1778-4dbc-b40e-d4aa3cbc8d25.png">

**Comment by qmhc** [comment]
默认的输出路径和 vite 打包输出路径一样，你可以通过插件选项 `outputDir` 修改输入路径。

**Comment by ckvv** [comment]
@qmhc 似乎是应为插件不支持应为这个参数导致的`preserveModulesRoot`,参考https://rollupjs.org/guide/en/#outputpreservemodulesroot

**Comment by qmhc** [comment]
使用的是插件的初始化选项，你可以查阅文档的[选项部分](https://github.com/qmhc/vite-plugin-dts/blob/main/README.zh-CN.md#%E9%80%89%E9%A1%B9)，或者查阅 example 文件夹下的[示例](https://github.com/qmhc/vite-plugin-dts/blob/main/example/vite.config.ts)

**Comment by ckvv** [comment]
看代码中并没有对`preserveModulesRoot `做特殊处理
https://github.com/qmhc/vite-plugin-dts/blob/173dfe7fcc2fd18fbd30d26433a89b7dca8801ec/src/plugin.ts#L319-L340
我用下面这种方式修改了路径
```js
  plugins: [dtsPlugin({
    cleanVueFileName: true,
    beforeWriteFile(filePath, content){
      return {
        filePath: filePath.replace(`${rootPath}/es/src`, `${rootPath}/es`),
        content,
      };
    }
  }), vue()]
```

**Comment by qmhc** [comment]
呃，我主要是没有理解你的需求是什么。

你是希望打包出的目录接口如你开始发的这张图一样，
（这里有好多同名的 index.d.ts 被相互覆盖了）

![image](https://user-images.githubusercontent.com/40221744/149141498-d4b03db5-4d67-4481-8063-7a22a54b58fc.png)

还是希望是下面这种结构？
（这是注释掉 `beforeWriteFile` 后打包出来的结构）

![31(2I(N86GW ZB~N2DBQFQ4](https://user-images.githubusercontent.com/40221744/149139899-6d64077f-af00-4662-853f-0bb91cf13f08.png)

或者是其他的结构？

你能否详细的描述一下你的需求，是希望打包出怎么样的目录结构，与现在的差异在什么地方？

**Comment by ckvv** [comment]
我是想打包成下面这张格式

**Comment by ckvv** [comment]
目录不一致的原因是因为没有处理vite配置文件
```js
//vite.config.js
{
...
build: {
  rollupOptions: {
      output: {
        entryFileNames: '[name].js',
        preserveModules: true,
        preserveModulesRoot,
      },
  }
}
...
}
```
其中`preserveModulesRoot`会修改打包的路径

**Comment by qmhc** [comment]
我注释掉你项目中 `scripts/vite.es.js` 中的 `beforeWriteFile`，执行 `pnpm run build:es` 打包出来的结果是你说的想要的结果：

![image](https://user-images.githubusercontent.com/40221744/149265748-a9abd584-a2a5-4754-9992-2d031a6683d5.png)

![image](https://user-images.githubusercontent.com/40221744/149265774-37ef2aa2-d868-43ff-a55e-52c0b8483b88.png)

我使用的是 windows 系统下 vscode，你的 `beforeWriteFile` 在 windows 系统下并没有生效（由于路径中 `'/'` 和 `'\'` 的区别），注释掉之后打包出来的结果是一样的。

反而我通过 `path.resolve()` 处理路径后，使你的 `beforeWriteFile` 生效，打包后出来的结果是你说的不想要的结果：

![image](https://user-images.githubusercontent.com/40221744/149266260-4da6d3ee-878d-45f5-863d-438a3f3e2f84.png)

![image](https://user-images.githubusercontent.com/40221744/149266238-fddd0c82-d125-465a-8076-4917205945f5.png)

你是在怎么的环境下发生这样的问题，我这边确实是无法复现。

**Comment by ckvv** [comment]
这个也不正确,es目录下统一多了一个下src目录
![](https://user-images.githubusercontent.com/40221744/149265748-a9abd584-a2a5-4754-9992-2d031a6683d5.png)
这个是我现在生成的的正确的目录
https://cdn.jsdelivr.net/npm/@ckpack/v-ui/es/

**Comment by qmhc** [comment]
不使用插件直接打包出来的结构如下：

![image](https://user-images.githubusercontent.com/40221744/149276005-2982796d-1623-4696-b9eb-109cf5f84817.png)

![image](https://user-images.githubusercontent.com/40221744/149276049-de841554-10fb-4124-b17c-cf1f5fb8da9b.png)

在 `es` 下也是含有 `src` 目录的，是否有一些外部的参数或环境影响，或者有一些额外的步骤？

**Comment by ckvv** [comment]
这个和在我的机器上（mac）的打包结果不同，看结果似乎是因为在Windows上的`preserveModulesRoot `参数没有生效，周末我在window机器上面测试一下，

**Comment by agileago** [comment]
插件生成出来的类型文件始终带着src目录，这是问题所在

**Comment by ckvv** [comment]
这个似乎是vite的问题，我在那边提了个issue
https://github.com/vitejs/vite/issues/6509

**Comment by binvb** [comment]
@qmhc  可以指定生成路径吗? 我也遇到这个问题，我是调用 vite 的build方法进行打包的，而dts总是自动生成跟开发环境一样的目录,e.g.
```
// 生产环境
-- packages
   --- AComponent
   --- BComponent
-- src
   -- app.vue
// 打包目录
-- dist
   -- AComponent
   -- BCompoenent
// dst output
-- dist
   --packages
  --src
...
```

**Comment by ckvv** [comment]
@binvb 
你可以参考这个
https://github.com/ckpack/v-ui/blob/c21a8819694f129e7dd4adb40ea581c687940d39/scripts/vite.es.js#L14-L23

**Comment by qmhc** [comment]
相关问题仍在等待 vite 分流，插件层面存在暂时解决方案，我先修改标题并关闭这个 issue 以免产生误导。

@agileago 如果你的问题仍未解决，你可以打开一个新的 issue，并提供具体的配置和环境信息，如果可以提供一个最小的复现项目，将更有助于更快地定位问题。
