### ISSUE TITLE
How to infer component emitted event types?

### ISSUE THREAD

**Issue by x-255** [qmhc/vite-plugin-dts#56]
![image](https://user-images.githubusercontent.com/37900860/156719902-1f191822-5a56-43ce-84f0-2de5662eebfc.png)
![image](https://user-images.githubusercontent.com/37900860/156719990-2f4a8385-3ab4-421c-90c7-e00cf161bdfe.png)

我这里的onAdd应该是`(value: number) => void`，但生成的结果确是`((...args: any[]) => any) | undefined`，我想知道这是插件的问题还是vite打包的配置问题，应该怎么解决呢

**Comment by qmhc** [comment]
`defineEmits` 使用 `ts` 的形式只能定义返回值 `emit` 的类型，想要定义对外事件的类型目前只能用过用 `js` 的方法传入一个验证对象：

```ts
const emit = defineEmits({
  // 该函数的入参和事件完全一样，vue 内部会通过 infer 获取参数类型并赋值给 onAdd
  add: (vaule: number) => true
})
```

最后会得到事件类型声明如下：

```ts
{
  onAdd?: ((value: number) => any) | undefined
}
```

**Comment by x-255** [comment]
> `defineEmits`使用`ts`的类型定义只能使用过一次的返回值`emit`事件的当前类型，定义一个唯一的类型`js`验证对象：
> 
> ```ts
> const  emit  =  defineEmits (函数的函数和事件完全一样，vue 会通过 infer 获取类型参数输入并给定参数onAdd 
>   add : number ) = > true } )
>     
> ```
> 
> 最后会发生的事件类型声明如下：
> 
> ```ts
> { 
>   onAdd ?: ( (值: number )  =>  any )  |  未定义
> }
> ```

有用，谢谢老哥
