### ISSUE TITLE
支持react吗

### ISSUE THREAD

**Issue by birdmanmandbir** [qmhc/vite-plugin-dts#57]
rt

**Comment by qmhc** [comment]
没有额外的 `.d.ts` 声明时，会按照 `typescript` 原有的行为对 `tsx` 进行解析。

如果有相应的工具函数 (例如 vue3 中是借助 `defineComponent`) 是可以推导出相应的组件类型的。

插件的对 vue 的核心处理仅仅是把 vue 文件转化为 ts 文件交由 `typescript` 编译。

**Comment by qmhc** [comment]
该 issue 两周未有后续回复，并且不是 bug 或 feature 相关，我暂时先关闭该 issue，后续有新的进展将重新打开。
