### ISSUE TITLE
How to use `root` correctly?

### ISSUE THREAD

**Issue by hatton** [qmhc/vite-plugin-dts#59]
Thanks for building this and sharing it!

My directory structure looks like this

```
My-Component/
    dist/
    lib/
    some-other-stuff/
    tsconfig.json
```

My vitejs build options are

```
 build: {
    lib: {
      entry: path.resolve(__dirname, 'lib/index.ts'),
      name: 'my-component',
      fileName: (format) => `my-component.${format}.js`,
    }
  },
```

If I use the plugin with the default options, vite-plugin-dts creates the files:
```
dist/
    lib/
        <stuff>.d.ts
```

That's good. But what I want to achieve is

```
dist/
    typings/
        <stuff>.d.ts
```

So I tried this

```
dts({
      root: 'lib',
      outputDir: 'dist/typings',
      tsConfigFilePath: '../tsconfig.json',
    }),
```

This runs without any errors:

```
[vite:dts] Start generate declaration files...
[vite:dts] Declaration files built in 5776ms.
```

However, now my `dist` directory does contain any output from the plugin. Setting `logDiagnostics:true` does not cause the plugin to tell me what it is doing or where it is putting the files.

So my question is, how do I set the options so that I can get the output structure I need?
Thanks!

**Comment by qmhc** [comment]
`root` option is using for monorepo in some cases, not necessary to change it usually.

Is your `vite.config.ts` in 'lib' dir ?
(it would be better for `vite.config.ts` and `tsconfig.json` in the same dir, defaults in root)

Normally you set `outputDir: 'dist/typings'`, you will get like following paths after building:

`{root}/dist/typings/lib/<stuff>.d.ts`

And the type entry is the file with the same name as `lib.entry`: `{root}/dist/typings/lib/index.d.ts`

You can set `"types": "dist/typings/lib/index.d.ts"` in `package.json` to make it effective.

It's helpful that you can provide a reproductive repo.

**Comment by guoyunhe** [comment]
Same issue here. I am using Vite in a Node.js script, so here is no `vite.config.ts` in the library repo.

The actual output is:

```md
dist
├── index.cjs.js
├── index.esm.js
├── index.umd.js
├── src
|   ├── Button.d.ts
|   └── index.d.ts
└── style.css
```

The `dist/src` folder is not necessary.

Expected output should be:

```md
dist
├── index.cjs.js
├── index.esm.js
├── Button.d.ts
├── index.d.ts
├── index.umd.js
└── style.css
```

**Comment by qmhc** [comment]
Currently you can use `entryRoot` option to specify a entry root, the output relative paths will be calculated according to it, and it will be auto calculated as the smallest public path of all files if it is not set.

```js
expect(
  queryPublicPath(['E:\\project\\src\\lib\\a.d.ts', 'E:\\project\\src\\lib\\b.d.ts'])
).toBe('E:\\project\\src\\lib')

// outputs: 'dist/a.d.ts' and 'dist/b.d.ts'
```
