### ISSUE TITLE
resolve.alias doesn't work is this plugin

### ISSUE THREAD

**Issue by viclafouch** [qmhc/vite-plugin-dts#60]
Hello ! 

It looks like aliases are not correctly transformed in d.ts files.. All the JavaScript code is ok. It's just my d.ts files.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/23353836/158796671-fb32a29d-09aa-420e-81cb-338f4cc40db6.png">

Here my vite config : 

```ts
import { defineConfig } from 'vitest/config'
import tsconfigPaths from 'vite-tsconfig-paths'
import react from '@vitejs/plugin-react'
import peerDepsExternal from 'rollup-plugin-peer-deps-external'
import dts from 'vite-plugin-dts'

const path = require('path')

// https://vitejs.dev/config/
export default defineConfig({
  test: {
    environment: 'jsdom',
    globals: true
  },
  build: {
    sourcemap: true,
    target: 'esnext',
    minify: false,
    lib: {
      entry: path.resolve(__dirname, 'src/index.tsx'),
      name: 'Mui-phone-number',
      fileName: format => `mui-phone-number.${format}.js`
    },
    rollupOptions: {
      output: {
        sourcemapExcludeSources: true,
        globals: {
          react: 'React',
          '@mui/material/InputAdornment': 'InputAdornment',
          '@mui/material/TextField': 'TextField',
          '@mui/material/IconButton': 'IconButton',
          '@mui/material/styles': 'styles',
          'react/jsx-runtime': 'jsxRuntime',
          '@mui/material/Menu': 'Menu',
          '@mui/material/MenuItem': 'MenuItem',
          '@mui/material/Typography': 'Typography',
          '@mui/material/ListItemIcon': 'ListItemIcon',
          '@mui/material/ListItemText': 'ListItemText'
        }
      }
    }
  },
  plugins: [
    peerDepsExternal(),
    react(),
    tsconfigPaths(),
    dts({
      insertTypesEntry: true
    })
  ]
})

```

Is anyone has the same issue ?

**Comment by qmhc** [comment]
I initially think this may be some unrobust when using with the `vite-tsconfig-paths`.

Normally it is as expected when using `resolve.alias` in the vite config file.

This is one of the main tasks for next version, I still need more time for futher testing, thanks for your patience.

**Comment by qmhc** [comment]
I had read the source codes of `vite-tsconfig-paths` in last weekend.

It's using some external resolvers to resolve the paths which defined in `tsconfig.ts` that makes others plugins cannot perceive through vite's hooks.

That is a bad news, it means that this plugins cannot make some cooperations with other plugins.

**Comment by viclafouch** [comment]
Oo good catch, so I guess, the better thing to do for now is to rewrite the aliases into the resolve.alias option ?

**Comment by qmhc** [comment]
I did a simple test and it is work well with `vite-aliases`, you can follow up if there are problems.

Also you can use the `resolve.alias` directly, is well.

**Comment by viclafouch** [comment]
Thank you very much @qmhc ! You can close the issue ;)

**Comment by gyzerok** [comment]
@viclafouch would you mind sharing your config? It seems like emitted typescript declarations do not work with `vite-aliases`.

**Comment by mathews-cometchat** [comment]
I have the same issue as well.

**Comment by DaftPaul** [comment]
same issue here I think we should re open it

**Comment by zhouxinxing** [comment]
Is there no one to maintain it  ?

**Comment by qmhc** [comment]
@DaftPaul  @zhouxinxing Now please use `pathsToAliases` option of the plugin and you don't need to add any extra plugin.
