### ISSUE TITLE
Value in `outputDir` is not respected

### ISSUE THREAD

**Issue by sionzee** [qmhc/vite-plugin-dts#62]
Hello,

since 1.0.0 the value in `outputDir` is not respected,
in my case I have there `./dist` but all .d.ts files are spread across source files.

```javascript
dts({
  include: ['./index.ts', './src'],
  outputDir: './dist/'
})
```

The dts files after build:
```
/index.dts
/src/whatever.dts
/src/....
```

// Edit: Adding vite.config.ts
```typescript
export default defineConfig({
  test: {
    globals: true
  },
  build: {
    lib: {
      entry: './index.ts',
      name: 'shared',
      formats: ['es'],
      fileName: () => 'index.js'
    },
    rollupOptions: {
      external: ['debug']
    }
  },
  plugins: [
    dts({
      include: ['./index.ts', './src'],
      outputDir: './dist/'
    })
  ]
})

```

**Comment by qmhc** [comment]
This is a simple test:

![image](https://user-images.githubusercontent.com/40221744/159599706-3e877924-0c6b-4168-a1ee-6f71234218a3.png)

After built:

![image](https://user-images.githubusercontent.com/40221744/159599856-3220a053-8d62-48ca-b7b5-8e90ef578de9.png)

Maybe you need to provide further information.

**Comment by freyonism** [comment]
Hi, I also stumbled across this issue.

Here is my reproduction for this issue. Tough, I don't know if this is correct one. 
[Repro](https://github.com/freyonism/vite-plugin-dts-issue62-repro)

Screenshoots: 
1. Output in dist (outputDir)
![Screenshot from 2022-03-23 10-32-39](https://user-images.githubusercontent.com/93385249/159618677-81921381-b582-4706-a8e2-f91b1a74855f.png)

2. output dir ignored
![Screenshot from 2022-03-23 10-33-06](https://user-images.githubusercontent.com/93385249/159618743-81919e9f-7f42-484d-a102-0b73cfd232e6.png)

**Comment by qmhc** [comment]
@freyonism it is both work well in windows system.

Please provide some information about your os and env.

**Comment by qmhc** [comment]
@freyonism it is both work well in windows system.

Please provide more information about your os an env.

**Comment by freyonism** [comment]
Ah yes, in windows it generates types correctly.
![image](https://user-images.githubusercontent.com/93385249/159661718-da941bdd-936c-4e7a-8796-ee652dd6b844.png)


My env for the reproduction:

- OS: Pop OS 21.10
- Node: v16.14.2

**Comment by sionzee** [comment]
I'm using Windows 11 with WSL 2.0, Node v17.4.0
```
wsl --version
WSL version: 0.56.1.0
Kernel version: 5.10.93.2
WSLg version: 1.0.30
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.588
```

I'm sorry for not providing reproduction case, I'm busy at work. I will be able to give it some time afternoon (around 7PM)

**Comment by sionzee** [comment]
Nvm, I see the source code is small and simple so I gave it a quick try.
- `outputDir` is pointing to right folder after ensuring absolute path

Later in the code it does:
```
filePath = (0, import_path3.resolve)(outputDir, (0, import_path3.relative)(entryRoot, cleanVueFileName ? filePath.replace(".vue.d.ts", ".d.ts") : filePath));
```
and the result of this is:
```
outputDir = "<projectRoot>/dist"
entryRoot = "<projectRoot>"
filePath = "<projectRoot>/src/whatever.ts"
result = "<projectRoot>/src/whatever.d.ts"
```

**Comment by qmhc** [comment]
This issue has been located on mac and linux systems, will be fixed later.

**Comment by qmhc** [comment]
I testing it is work well in linux and max systems, but not sure is the same in windows 11.

**Comment by MarioLuLu7** [comment]
wsl2 in windows11, invalid.

**Comment by JaLe29** [comment]
Same problem on windows 11..
