### ISSUE TITLE
setup 语法不会导出 vue.d.ts 声明

### ISSUE THREAD

**Issue by zhl1232** [qmhc/vite-plugin-dts#63]
![image](https://user-images.githubusercontent.com/30594030/160049863-be5ed88c-68ac-4ec3-add1-8beccdc6d122.png)

**Comment by qmhc** [comment]
这是 `vue` 在 `3.2.27` 开始出现的一个问题，在 `pnpm` 项目中，如果 `node_modules` 不在 `cwd` 目录下，在构建类型文件时会引发 `@vue/shared` 的类型，就像本项目的 `example` 这种结构，暂时不确定具体问题是哪一方引起的（或许让 cwd 保持在根目录可以解决）

目前将本项目开发依赖的 `vue` 版本回退到 `3.2.26`，`example` 可以正常运行，对于其他项目的正常开发使用并不会产生影响（其他项目依赖自己的 `vue` 版本）。
