### ISSUE TITLE
rollupTypes: true - error during build

### ISSUE THREAD

**Issue by Qualterink** [qmhc/vite-plugin-dts#72]
Hi,

when I set attribute 'rollupTypes': true, then I got an error

[vite:dts] Start rollup declaration files...
error during build:
Error: Internal Error: The "default" symbol has a ts.SyntaxKind.ExportAssignment declaration which is not (yet?) supported by API Extractor

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.

"vite": "^2.9.5",
"vite-plugin-dts": "^1.1.1"

**Comment by qmhc** [comment]
Can you provide a reproduce repo?

**Comment by qmhc** [comment]
Can you provide a reproduce repo?

**Comment by Qualterink** [comment]
Hi,

I created a repo

https://github.com/Qualterink/reproduce-errror-vite-plugin-dts

System settings:

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal


Node - v16.14.2

**Comment by qmhc** [comment]
@Qualterink I clone your reproduce repo, and run `vite build`, it work without any error.

**Comment by evoactivity** [comment]
I have just ran into this on 3.2.0. The problem was having hyphens in my name, I whitespace characters will also cause the same issue.

```js
import { resolve } from "path";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";

export default defineConfig({
  build: {
    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, "src/main.ts"),
      name: "breaks-with-hyphens-here",

      // the proper extensions will be added
      fileName: "this-can-be-hyphenated"
    },
  },
  plugins: [
    dts({
      rollupTypes: true,
      insertTypesEntry: true,
    }),
  ],
  test: {
    coverage: {
      provider: "v8",
    },
  },
});
```

If I turn off rollupTypes I can see name is used in the file like this
```ts
export * from './main'
import breaks-with-hyphens-here from './main'
export default breaks-with-hyphens-here
```
which is not valid and breaks the rollup action from working.
