### ISSUE TITLE
Can add a configuration to control not transforming the aliases ?

### ISSUE THREAD

**Issue by glitchboyl** [qmhc/vite-plugin-dts#73]
Hi dalao.
This plugin is awesome, and it helps me a lot. But I still have trouble with it.
So here is the thing, I am using this plugin in a monorepo. Assume my `tsconfig.json` sets alias like this:
```json
"paths": {
  "@monorepo/packageA": ["packages/packageA/index.ts"],
  "@monorepo/packageB": ["packages/packageB/index.ts"],
}
```
`packages/packageA/index.ts` has import something from '@monorepo/packageB'

After I run `vite build` and the plugin is takes effect, build file import path from **'@monorepo/packageB'** change to **relative path of '@monorepo/packageB'**.

Obviously I don't expect that happened. And I am not sure if I missed some configurations. So I read the source code.
Althought I haven't fully understand the source code, but I think [this line](https://github.com/qmhc/vite-plugin-dts/blob/main/src/plugin.ts#L366) is the key of my issue.

I think I can pr this but I need you to provide me a `configName`.

Thanks for the awesome plugin again! Hope you have a good day.

**Comment by qmhc** [comment]
Thanks for your PR intention.

I think I need a litter time to consider this design, please wait a moment.

**Comment by qmhc** [comment]
After initial consideration, I think the option should be named `aliasesExclude`. It should be a string array, and is used to exclude specified import paths when transform aliases.

You also could share your consideration.

**Comment by glitchboyl** [comment]
> After initial consideration, I think the option should be named `aliasesExclude`. It should be a string array, and is used to exclude specified import paths when transform aliases.
> 
> You also could share your consideration.

LGTM. Also I suppose need add a configuration which can overwrite tsconfig, don't you think?

**Comment by glitchboyl** [comment]
`@microsoft/api-extractor` just happen to have that API
```
ExtractorConfig.prepare({
  compiler: {
    overrideTsconfig: {} //  we can override tsconfig in here
  }
})
```

**Comment by qmhc** [comment]
@glitchboyl `compilerOptions` in plugin options can override the `compilerOptions` in `tsconfig.json`, if this is not adequate. I think it should be created a specified config file by using `tsConfigFilePath`.

As for rollup type files, is currently not support override the `compilerOptions`, we can discuss it in a new issue (#74).
