### ISSUE TITLE
Support override `compilerOptions` of `@microsoft/api-extractor` when rollup types

### ISSUE THREAD

**Issue by qmhc** [qmhc/vite-plugin-dts#74]

**Comment by glitchboyl** [comment]
Actually, I think `rollupTypes` that function effect is not as well as I thought. 
In my case, when I used it in monorepo, the generate result is always unsatisfactory. I don't even know how to config it.
After I tried so many times I have to give up to use it. 🤕

**Comment by qmhc** [comment]
@glitchboyl For monorepo case, start a build process for each package maybe the best way currently.

`@microsoft/api-extractor` ask an unique entry to rollup type files, if want to rollup type files for each package in one process, it needs to create multiple instance to implement.

But, when using lib mode in `vite`, it only support only one entry, you need to config the `build.rollupOptions.input` if you want to add mutiple entry. This is a rare case which needs to weigh whether it is supported.

You also can share your case by your project, I can try to help you.

**Comment by glitchboyl** [comment]
> @glitchboyl For monorepo case, start a build process for each package maybe the best way currently.
> 
> `@microsoft/api-extractor` ask an unique entry to rollup type files, if want to rollup type files for each package in one process, it needs to create multiple instance to implement.
> 
> But, when using lib mode in `vite`, it only support only one entry, you need to config the `build.rollupOptions.input` if you want to add mutiple entry. This is a rare case which needs to weigh whether it is supported.
> 
> You also can share your case by your project, I can try to help you.

Thank you for your kindness. 💜

Yeah, I agree with your opinion. So can we just create a temporary whole-project-tsc, and try to manual setup the `@microsoft/api-extractor` entry?
This is my [solution](https://github.com/Awesome-Creators/vueposu/blob/main/scripts/build.ts#L69-L123) inspired by you. Thanks again.

**Comment by qmhc** [comment]
After consideration, the case which rollups to each package is relatively rare, and it just a bit beyond the scope of this plugins.

So, for now just support override `compilerOptions` when rollup up.
