### ISSUE TITLE
error TS2307: Cannot find module './index.vue' or its corresponding type declarations.

### ISSUE THREAD

**Issue by xiuxiuye** [qmhc/vite-plugin-dts#76]
在学您的文章：https://segmentfault.com/a/1190000040127796 遇到下面问题，不知该如何解决，所以来求助您，看是否知道如何解决。
问题描述：
使用vite创建了一个vue-ts工程，根据您文章， 想自己生成类型声明文件，然后在执行到下面代码时
`
const diagnostics = project.getPreEmitDiagnostics()
// 输出解析过程中的错误信息
 console.log(project.formatDiagnosticsWithColorAndContext(diagnostics))
`
控制台打印出下面的报错：
`
src/components/Button/index.ts:2:20 - error TS2307: Cannot find module './index.vue' or its corresponding type declarations.
`
下面是src/components/Button/index.ts的内容
`
import Button from './index.vue'

export default Button
`
可以看到，index.vue就是个普通的vue文件

下面这个是我的执行脚本文件的代码（和您的文章里代码基本保持一致）：
const path = require('path')
const fs = require('fs-extra')
const glob = require('fast-glob')
const { Project } = require('ts-morph')
const { parse, compileScript } = require('@vue/compiler-sfc')

let index = 1

const buildTypes = async () => {
  // 这部分内容具体可以查阅 ts-morph 的文档
  // 这里仅需要知道这是用来处理 ts 文件并生成类型声明文件即可
  const project = new Project({
    compilerOptions: {
      declaration: true,
      emitDeclarationOnly: true,
      noEmitOnError: true,
      allowJs: true, // 如果想兼容 js 语法需要加上
      outDir: 'dist' // 可以设置自定义的打包文件夹，如 'types'
    },
    tsConfigFilePath: path.resolve(__dirname, '../../tsconfig.json'),
    skipAddingFilesFromTsConfig: true
  })

  // 获取 src 下的 .vue 和 .ts 文件
  const files = await glob(['src/components/Button/index.ts'])
  const sourceFiles = []

  await Promise.all(
    files.map(async file => {
      if (/\.vue$/.test(file)) {
        // 对于 vue 文件，借助 @vue/compiler-sfc 的 parse 进行解析
        const sfc = parse(await fs.promises.readFile(file, 'utf-8'))
        // 提取出 script 中的内容
        const { script, scriptSetup } = sfc.descriptor
        if (script || scriptSetup) {
          let content = ''
          let isTs = false

          if (script && script.content) {
            content += script.content

            if (script.lang === 'ts') isTs = true
          }

          if (scriptSetup) {
            const compiled = compileScript(sfc.descriptor, {
              id: `${index++}`
            })

            content += compiled.content

            if (scriptSetup.lang === 'ts') isTs = true
          }

          sourceFiles.push(
            // 创建一个同路径的同名 ts/js 的映射文件
            project.createSourceFile(file + (isTs ? '.ts' : '.js'), content)
          )
        }
      } else {
        // 如果是 ts 文件则直接添加即可
        sourceFiles.push(project.addSourceFileAtPath(file))
      }
    })
  )

  const diagnostics = project.getPreEmitDiagnostics()
  // 输出解析过程中的错误信息
  console.log(project.formatDiagnosticsWithColorAndContext(diagnostics))
}

**Comment by qmhc** [comment]
你好，首先感谢你阅读我的文章。

这里是用于报告与该项目（插件）相关问题的板块，你提出的问题与该项目无关，因此我会先关闭这个 `issue`。

对于外部社区文章中的疑问，你可以使用该社区的评论功能，或者可以使用私信功能进行沟通，我都将乐意为你解答。

对于你的这个提问，最好可以提供一个复现的项目，这可以让别人高效地帮你定位问题，减少提问者与解答者双方的时间消耗与沟通成本（代码是程序猿最好的沟通手段）。根据你目前已提供的信息，我暂时没看出端详，同时我猜测有可能在 `tsconfig.json` 的配置上出现了问题。

最后，如果你在写完一些内容之后，可以校对一下 markdown 生成的格式那就再好不过了！
