### ISSUE TITLE
rollupTypes won't rollup types in node_modules

### ISSUE THREAD

**Issue by nodegin** [qmhc/vite-plugin-dts#79]
Hi, so I have a library contains something like

```js
import { DropzoneOptions } from 'react-dropzone'

export interface DropzoneOptionsWithExtra extends DropzoneOptions {
  extraProp: any;
}
```

then after I build via vite, I am got something exactly same,
while I guess I would expect something to be rolled up:

```js
type DropzoneOptions = Pick<React.HTMLProps<HTMLElement>, PropTypes> & {
  ...
};

export interface DropzoneOptionsWithExtra extends DropzoneOptions {
  extraProp: any;
}
```

due to this nature, my main project which uses this library doesn't install `react-dropzone` as dependency,

it causes `DropzoneOptionsWithExtra` only has `extraProp` but not anything from `DropzoneOptions` because `DropzoneOptions` is not found

**Comment by qmhc** [comment]
Could you provide a reproduction?

Or maybe you can try to add it as a dev dependency.
