### ISSUE TITLE
Weird behaviour possibly related to aliases + type modifier

### ISSUE THREAD

**Issue by lucas-labs** [qmhc/vite-plugin-dts#80]
Ok, this is a long one, sorry for that. I'm trying to explain this issue the best I can with most details I've learnt. Feel free to ask me anything! 

Also, even though I'm not familiar with the source code, if someone could give me a tip about this issue (like where to start looking) I could try to solve it and send a PR.

Anyways, here we go...

## Reproduction
All the code snippets in this issue are part of the following repo (I'll link specifics files too for easier navigation)
[https://github.com/lucas-labs/vue3-vsl/tree/dts-issue-repro](https://github.com/lucas-labs/vue3-vsl/tree/dts-issue-repro)

## Issue description
I have two components: `VirtualScroller.vue`, which is the main ("parent") component and `ScrollerItem.vue` which is a secondary ("child") component, used by VirtualScroller.

In VirtualScroller (aka main component) I'm importing a few types and it's child ScrollerItem:

> [VirtualScroller.vue (click to go to the file)](https://github.com/lucas-labs/vue3-vsl/blob/9bafd33bd4b1e55c42df94c41b7487777dbdc34c/src/components/VirtualScroller.vue#L53-L60?plain=1)

```vue
<script setup lang="ts">
    import {
        type ItemIdType,
        type DataKeyFunction,
        type ScrollingDirection,
        type VirtualListRange,
        SlotType
    } from '@/common/types';
    
    // this one is another component
    import ScrollerItem from './ScrollerItem.vue';

    ...
</script>
```

> Notice that I'm both using `@` alias and mixing `type` modifier with non-type import (`SlotType`)

The generated .d.ts looks like this:
> [VirtualScroller.vue.d.ts](https://github.com/lucas-labs/vue3-vsl/blob/9bafd33bd4b1e55c42df94c41b7487777dbdc34c/dist/src/components/VirtualScroller.vue.d.ts#L1-L3?plain=1)
```typescript
// ItemIdType and AnObject are comming from ScrollerItem (I'll explain why later on)
import type { ItemIdType, AnObject, type DataKeyFunction } from '../common/types';
```

### Three issues here:
1. Its not importing `ScrollerItem` , but instead redifining it with `DefineComponent` (I think this is desired behaviour but I add it here just to check that out)
2. Its using `import type` with `type` modifier, which I guess is not correct:
    `ERR: The 'type' modifier cannot be used on a named import when 'import type' is used on its import statement.`
3. Most of my imports are missing (e.g `ScrollingDirection`, `VirtualListRange`)

Also notice `ItemIdType`, `AnObject` and `DataKeyFunction` are actually beign imported just fine!
 
#### But why? Why some are imported and some are not?

Turns out in `ScrollerItem.vue` I'm not using aliases: 

> [ScrollerItem.vue](https://github.com/lucas-labs/vue3-vsl/blob/9bafd33bd4b1e55c42df94c41b7487777dbdc34c/src/components/ScrollerItem.vue#L8-L10?plain=1)
```vue
<script setup lang="ts">
    import { EventType, type AnObject, type ItemIdType } from '../common/types';
</script>
```

Therefore its .d.ts imports are ok:

> [ScrollerItem.vue.d.ts](https://github.com/lucas-labs/vue3-vsl/blob/dts-issue-repro/dist/src/components/ScrollerItem.vue.d.ts?plain=1)
```ts
import { type AnObject, type ItemIdType } from '../common/types';
...
```

Thanks to that, in my first component (VirtualScroller.vue) `AnObject` and `ItemIdType` are both beign imported, whilst other types aren't.

#### What about `DataKeyFunction`. Why that one is also being imported?
Turns out inside [`VirtualScroller.vue`](https://github.com/lucas-labs/vue3-vsl/blob/9bafd33bd4b1e55c42df94c41b7487777dbdc34c/src/components/VirtualScroller.vue#L72?plain=true) I'm using `DataKeyFunction` to define a type like this:
```ts
type VirtualScrollerProps = {
  dataKey: string | DataKeyFunction;
  direction?: ScrollingDirection;
}
```

Notice the `string | DataKeyFunction`. If I delete `string | `, then DataKeyFunction will also be missed from the .d.ts. Just like `ScrollingDirection`. 

In fact if I define direction to be something like this, then it will be imported in the .d.ts file... weird.

```ts
 direction?: ScrollingDirection | ScrollingDirection; 
```

**Comment by qmhc** [comment]
You can add following to your plugin options to check diagnostics: 

```ts
dts({
  skipDiagnostics: false,
  logDiagnostics: true
})
```
