### ISSUE TITLE
rollupTypes: true - Unable to analyze the export "default" in  file

### ISSUE THREAD

**Issue by partiality** [qmhc/vite-plugin-dts#81]
如果入口文件不存在  export default  object;  形式的导出     那么在生成.d.ts文件的时候就会报
Error: Internal Error: Unable to analyze the export "default" in
D:/learn-project/vite-plugin-dts-main/example/types/src/index.d.ts   的错误

问题出现在   ./src/plugin.ts   文件  431行代码
原代码          let content = `import ${libName} from '${filePath}'\nexport default ${libName}\nexport * from '${filePath}'\n`
建议修改为   let content = `export * from '${filePath}'\n`  或
                      let content = `import * as ${libName} from '${filePath}'\nexport default ${libName}\nexport * from '${filePath}'\n`

**Comment by qmhc** [comment]
@partiality 我想复核一下这个问题，当时出现这个问题是从外部引入打包后的包才会出现，还是打包的过程中就会出现？

因为这个改动引发了 #86 的问题。
