### ISSUE TITLE
编译后的声明文件中有".vue"的引入, 但是对应的文件并没有复制到编译后的目录中

### ISSUE THREAD

**Issue by any86** [qmhc/vite-plugin-dts#84]
### 编译前:
```typescript
// main.ts
import Curd from '@/Curd.vue'
export * from '@/types';
export default Curd;
```
### 编辑后
```typescript
// main.d.ts
import Curd from './Curd.vue';
export * from './types';
export default Curd;
```
编译后的Curd.vue是找不到的啊, 这个是预期吗? 实际上倒也不影响啥, 只是编辑器会提示找不到"./Curd.vue"

![image](https://user-images.githubusercontent.com/8264787/178403107-47f44a54-b2b5-4338-946d-5a627b5c849f.png)

### 目录结构
![image](https://user-images.githubusercontent.com/8264787/178402762-eaaa0d28-97f2-4597-87f9-46333601502d.png)

**Comment by any86** [comment]
补充下配置:
```typescript
  plugins: [vue(), dts({
    insertTypesEntry: true, copyDtsFiles: false
  })],
```

**Comment by qmhc** [comment]
编译后，应该会有一个文件为 `Curd.vue.d.ts` 的，如果这个文件存在则没问题，可能是编辑器刷新的不及时。

**Comment by any86** [comment]
https://github.com/any86/v-curd
我把编译后的dist文件夹也传上来了, 没有`Curd.vue.d.ts`, 麻烦看下是我使用不当, 还是`dts`对目录结构有些限制

**Comment by qmhc** [comment]
那应该是编译过程出现了 ts 错误，你可以把 `skipDiagnostics: false` 和 `logDiagnostics: true` 两个选上加上，看看诊断信息。

**Comment by any86** [comment]
确实有报错, 都是关于`_sfc_main`的, 不知道什么意思

![image](https://user-images.githubusercontent.com/8264787/178404468-63071414-cbf6-483a-8a5f-bb0cc7305ba7.png)

**Comment by any86** [comment]
已经最小化了代码: https://github.com/any86/v-curd/blob/beda41a6965ed85a71ae89583a4aca890c578b17/src/Curd.vue
问题很明显了, 如果引入了node_module中的库暴露的类型, 就会报错, 比如我这里的ant-design-vue, 请看下是否我还需设置什么, 还是插件并没有考虑到这种情况.

**Comment by qmhc** [comment]
你这个问题和 #51 一样，你可以参考这个 [workaround](https://github.com/qmhc/vite-plugin-dts/issues/51#issuecomment-1008309418)：

![image](https://user-images.githubusercontent.com/40221744/178640953-7027d09d-64f5-450a-9ff5-5736f86dd2e0.png)

**Comment by any86** [comment]
已解决, 看了你发的链接, 实际去改path也没成功, 因为关联的包太多了, 不是只改个ant-design-vue就行的,  所以干脆不用pnpm了, 暂时规避这个问题.

**Comment by luo-geng** [comment]
> 已解决, 看了你发的链接, 实际去改path也没成功, 因为关联的包太多了, 不是只改个ant-design-vue就行的, 所以干脆不用pnpm了, 暂时规避这个问题.
今天也遇到这个问题，试了好多方法不成功，包括修改paths，没想到是pnpm的问题

**Comment by luo-geng** [comment]
> 已解决, 看了你发的链接, 实际去改path也没成功, 因为关联的包太多了, 不是只改个ant-design-vue就行的, 所以干脆不用pnpm了, 暂时规避这个问题.

今天也遇到这个问题，试了好多方法不成功，包括修改paths，没想到是pnpm的问题
