### ISSUE TITLE
vscode插件volar读取类型不对

### ISSUE THREAD

**Issue by any86** [qmhc/vite-plugin-dts#89]
![image](https://user-images.githubusercontent.com/8264787/180125719-49a6a997-5079-4253-8f6d-b89c8c263c01.png)

![image](https://user-images.githubusercontent.com/8264787/180125314-dc450846-600b-467e-be75-852ea8f877b6.png)

请问为什么volar读取的是这部分的类型, 而不是下图位置的, 虽然生成`d.ts`过程中无报错, 但是使用的时候volar提示的类型不对.  是还没有考虑兼容volar, 还是有意让开发者自己写一些代码去兼容volar

![image](https://user-images.githubusercontent.com/8264787/180125384-a8af8d7f-1287-4504-8765-3404f0f9e669.png)

**Comment by qmhc** [comment]
请你提供一下你的源代码是怎么写的

**Comment by any86** [comment]
## xx.vue
```vue

<script setup lang="ts">
export interface RProps {
  xx: string;
}

interface Props {
  r: RProps;
}
</script>
<template>
  {{ r }}
</template>
```
就这一个文件

**Comment by qmhc** [comment]
你的 `defineProps` 是怎么写的？请尽量多的提供上下文，如果能提供一个复现最好了。

**Comment by any86** [comment]
不好意思, 少写了一行, 我改好了, 就是个简单的带props的组件, 只是Props类型是自定义的

**Comment by any86** [comment]
faq我就看过了,  因为我是第二次提issue, 所以这次提之前我看了.

**Comment by any86** [comment]
我把这个文件生成的xx.d.ts发上来你看看, 你就不用编译了:

### xx.vue
```vue
<script setup lang="ts">
interface Props {
  r: {
    xx: string;
  };
}
// props
defineProps<Props>();
</script>
<template>
  {{ r }}
</template>

```

### xx.d.ts
```typescript
declare const _sfc_main: import("vue").DefineComponent<{
    r: {
        type: ObjectConstructor;
        required: true;
    };
}, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, Record<string, any>, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
    r: {
        type: ObjectConstructor;
        required: true;
    };
}>>, {}>;
export default _sfc_main;
```

**Comment by any86** [comment]
你看, 这个`r`中的`xx`字段被忽略了

**Comment by qmhc** [comment]
```vue
<script setup lang="ts">
// 尽管没有直接使用 props，你仍需要接收 defineProps 的返回值
const props = defineProps<{
  color: 'blue' | 'red'
}>()
</script>

<template>
  <div>{{ color }}</div
</template>
```

你试试这个是否有用。

以前还有一个问题是 vue compiler 对 ts 方式定义的 props 会抹掉类型信息导致丢失，需要用 js 的方式去定义，现在不确定这个问题是否还存在。

**Comment by any86** [comment]
看来我是把2个问题当成一个问题了, 第二个问题通过`props`变量解决了, 还是说第1个问题,我把`color`的描述改一下:
```vue
<script setup lang="ts">
// color改成对象
const props = defineProps<{
  color: {a:string,b:number};
}>()
</script>

<template>
  <div>{{ color }}</div>
</template>
```

生成d.ts:

```typescript
declare const _sfc_main: import("vue").DefineComponent<{
    color: {
        type: ObjectConstructor;
        required: true;
    };
}, {
    props: {
        color: {
            a: string;
            b: number;
        };
    };
}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, Record<string, any>, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
    color: {
        type: ObjectConstructor;
        required: true;
    };
}>>, {}>;
export default _sfc_main;

```

我在业务代码中用他的时候:
![image](https://user-images.githubusercontent.com/8264787/180148465-ff37955d-9867-4648-9e86-fa46c7170899.png)

volar并不会获取到正确color的定义, 只能简单得到他是个`Object`

**Comment by any86** [comment]
![image](https://user-images.githubusercontent.com/8264787/180148894-aa34dbce-f80b-427d-b037-d5f8ad412679.png)

我传入的对象没有a,b字段他也不会报错的

**Comment by qmhc** [comment]
那说明这个问题还是存在：

> 以前还有一个问题是 vue compiler 对 ts 方式定义的 props 会抹掉类型信息导致丢失，需要用 js 的方式去定义，现在不确定这个问题是否还存在。

compiler 会根据 ts 类型反推一个 js 的 props 定义，然后编译时原本的类型信息就缺失了。

这块目前我还没有找到很好的解决办法，只能回退为 js 写法：

```ts
import type { PropType } from 'vue'

const props = defineProps({
  color: Object as PropType<{ a: string, b: number }>
})
```

**Comment by any86** [comment]
能解决就行, 我试试, 谢谢

**Comment by any86** [comment]
解决了.
