### ISSUE TITLE
insertTypesEntry 入口文件为 index.es.d.ts 还是 index.d.ts 呢

### ISSUE THREAD

**Issue by rorry121** [qmhc/vite-plugin-dts#92]
版本：1.3.1

根据 README 指示

```
  // Whether generate types entry file
  // When true will from package.json types field if exists or `${outputDir}/index.d.ts`
  // Force true when `rollupTypes` is effective
  // Default: false
  insertTypesEntry?: boolean
```
我的 package.json 文件没有指定 types 入口，dts 插件相关配置如下：
```
        outputDir: 'dist/v2',
        insertTypesEntry: true,
```
按理说  `dist/v2` 下，应该有 index.d.ts，但是目前来看，index.es.d.ts 是有的， index.d.ts 却可能在`dist/v2`下的其他目录，如  `dist/v2/src/index.d.ts`

想确认下 index.es.d.ts 是根据什么生成的呢？ `dist/v2` 一定有  index.es.d.ts 是可靠的吗

**Comment by qmhc** [comment]
可以看[这里](https://github.com/qmhc/vite-plugin-dts/blob/0fbe5c17a1996a4775b037d32858503b8f458f3d/src/plugin.ts#L170)，package.json 未设置时会相使用 `resolve(outputDirm, indexName)`。

**Comment by rorry121** [comment]
thx
