### ISSUE TITLE
Setup.vue中引入第三方组件后（如ant-design-vue），Setup.vue.d.ts生成失败

### ISSUE THREAD

**Issue by T-MAC-T** [qmhc/vite-plugin-dts#94]
### 复现步骤：

1. `git clone https://github.com/qmhc/vite-plugin-dts.git`
2. `pnpm i`
3. `pnpm add ant-design-vue`
4. 修改 `/example/components/Setup.vue`,（步骤1和步骤2）
```js
<template>
  <div class="setup" @click="inc">
    {{ count }}
  </div>
  <HelloWorld msg="111"></HelloWorld>

  <!-- 2：引入Button组件 -->
  <Button>test</Button>

</template>

<script setup lang="ts">
    import { defineProps, ref } from 'vue'
    import HelloWorld from './HelloWorld.vue'

    // 步骤1：导入Button
    import { Button } from 'ant-design-vue'

    const props = defineProps({
      count: {
        type: Number,
        default: 0
      }
    })
    
    const emit = defineEmits(['on-add'])
    
    const currentCount = ref(props.count)
    
    const inc = () => {
      currentCount.value++
      emit('on-add', currentCount.value)
    }
</script>

```  

5. `pnpm test:e2e`

 ### 结果
`/example/dist/example/components/`目录下没有生成 Setup.vue.d.ts文件

**Comment by qmhc** [comment]
你应该使用一个单独的应用项目来测试这个问题，你可以添加 `skipDiagnostics: false` 和 `logDiagnostics: true` 来查看这个过程有没有发生类型错误，同时在 pnpm 中使用软链接进行第三方库类型推导有已知的局限性，可以参考 FAQ 第三个问题。

**Comment by T-MAC-T** [comment]
@qmhc 多谢回复
我新建了一个最小复现仓库：https://github.com/T-MAC-T/vite-plugin-dts-setup-antd.
如果将模板中的Button组件注释掉，声明文件可以生成成功。如果引入Button，则生成失败
```js
<script setup lang="ts">
// Need to access the defineProps returned value to
// infer types although you never use the props directly
import { Button } from "ant-design-vue";
const props = defineProps<{
  color: "blue" | "red";
}>();
</script>

<template>
  <div>{{ color }}</div>

  <!-- 注释Button组件后，可以生成helloworld的声明文件 -->
  <Button>test</Button>
</template>
```

**Comment by qmhc** [comment]
你的 `tsconfig.json` 的 `paths` 配置不正确，是在 `compilerOptions.paths`，不是根级。

同时 antd-vue 可能打包的时候类型没处理好，引用了 @vue/runtime-core 的类型，因此你需要 `pnpm i -D @vue/runtime-core`

**Comment by T-MAC-T** [comment]
@qmhc 安装@vue/runtime-core后可以就可以了，再次感谢
