### ISSUE TITLE
Lost the `exclude` field in the extended config

### ISSUE THREAD

**Issue by wjq990112** [qmhc/vite-plugin-dts#95]
Monorepo sub packages usually extend the `tsconfig.json` in the root workspace.
Sometimes the root `tsconfig.json` has globally `exclude` and `include` fields, but when we use this plugin in the subpackage, these fields in root `tsconfig.json` are lost.

`tsconfig.json` in the workspace:
```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "esnext",
    "declaration": true,
    "moduleResolution": "node",
    "types": ["vitest/globals"]
  },
  "exclude": ["**/node_modules"]
}
```

`tsconfig.json` in the sub package:
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": "src",
    "outDir": "dist"
  },
  "exclude": ["*.config.ts"]
}
```

Maybe these lines: https://github.com/qmhc/vite-plugin-dts/blob/main/src/plugin.ts#L275-L276

**Comment by qmhc** [comment]
Hi, thanks first.

Here has one question, from the `extends` [document](https://www.typescriptlang.org/tsconfig#extends) that `include` and `exclude` from the inheriting config will overwrite the base config rather then merge.

I think the behavior of parsing should follow the original.

So the issue should be: should parse `include` or `exclude` from the base config when them missing from the inheriting config.

**Comment by wjq990112** [comment]
OK, I'll fix it after work.

**Comment by wjq990112** [comment]
It's a point that I have overlooked.

**Comment by wjq990112** [comment]
Fixed. @qmhc
