### ISSUE TITLE
Plugin doesn't work with Vite watch mode

### ISSUE THREAD

**Issue by rokgerzelj** [qmhc/vite-plugin-dts#99]
When running the Vite build process in watch mode (`vite build --watch`) to trigger a rebuild on source file changes, the plugin will crash if a rebuild is triggered when the plugin is actively running.

To reproduce: 
1. Start vite in watch mode `vite build --watch`
2. Save two source code changes in quick succession, so that the second one occurs while vite-plugin-dts is generating declaration files (see below, the line `[vite:dts] Start generate declaration files...`)
3. The plugin will crash

```
build started...
✓ 37 modules transformed.
dist/index.mjs   14.45 KiB / gzip: 3.12 KiB
dist/index.mjs.map 30.94 KiB
dist/style.css   16.69 KiB / gzip: 2.65 KiB
built in 118ms.

[vite:dts] Start generate declaration files...

build started...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, mkdir '/Users/user1/project/components/dist/alert'] {
  errno: -2,
  code: 'PLUGIN_ERROR',
  syscall: 'mkdir',
  path: '/Users/user1/project/components/dist/alert',
  pluginCode: 'ENOENT',
  plugin: 'vite:dts',
  hook: 'closeBundle'
}
```

**Comment by abencun-symphony** [comment]
I've noticed the same behavior. Is there any way this could be fixed, does Vite have a mechanism where it can gracefully stop what the plugins are doing when in watch mode?

**Comment by lokhmakov** [comment]
Temporary solution to add `emptyOutDir: false` into `build` section.

**Comment by segevfiner** [comment]
This is quite annoying. Probably need to use Rollup hooks a bit differently to fix this. I wonder if using `writeBundle` instead or returning a promise from `closeWatcher` will help.
